import { DurableWorkflowSchema } from '@ellipse/shared';

export const DURABLE_WORKFLOW_TEMPLATES = DurableWorkflowSchema.array().parse([
  {
    id: 'project_bootstrap',
    label: 'Project Bootstrap',
    runtime: 'hybrid',
    objective: 'Create the canonical project shell, design documents, workspace skeleton, and first production queues.',
    triggers: ['new_project_created', 'workspace_seed_requested'],
    recovery_strategy: ['resume_from_last_completed_step', 'rebuild_missing_workspace_outputs', 'notify_producer_agent'],
    steps: [
      {
        id: 'bootstrap_intent_capture',
        label: 'Capture intent',
        kind: 'analysis',
        owner: 'producer',
        inputs: ['prompt', 'source_images'],
        outputs: ['project_record', 'intent_summary'],
        automation_targets: ['cortex.planFromPromptAsync'],
      },
      {
        id: 'bootstrap_docs',
        label: 'Generate founding documents',
        kind: 'generation',
        owner: 'game_design',
        depends_on: ['bootstrap_intent_capture'],
        inputs: ['intent_summary'],
        outputs: ['pitch', 'gdd', 'art_direction', 'technical_design'],
        automation_targets: ['workspace.documents'],
      },
      {
        id: 'bootstrap_workspace',
        label: 'Seed workspace',
        kind: 'integration',
        owner: 'build_release',
        depends_on: ['bootstrap_docs'],
        inputs: ['project_record', 'founding_documents'],
        outputs: ['workspace_tree', 'preview_gdl', 'ops_manifests'],
        automation_targets: ['tools/seed-echoes-workspace.mjs'],
      },
    ],
  },
  {
    id: 'asset_family_pipeline',
    label: 'Asset Family Pipeline',
    runtime: 'temporal',
    objective: 'Turn image references and prompts into validated runtime-ready character, prop, UI, FX, and environment packs.',
    triggers: ['asset_work_order_created', 'asset_revision_requested'],
    recovery_strategy: ['retry_failed_stage', 'fallback_to_remote_gpu_worker', 'open_manual_qc_gate'],
    steps: [
      {
        id: 'asset_cutout',
        label: 'Cutout and cleanup',
        kind: 'generation',
        owner: 'asset_direction',
        inputs: ['source_images', 'asset_prompt'],
        outputs: ['alpha_mask', 'cutout_clean'],
        automation_targets: ['sam2', 'rembg', 'cleanup_worker'],
      },
      {
        id: 'asset_parts',
        label: 'Split parts and rig plan',
        kind: 'generation',
        owner: 'animation',
        depends_on: ['asset_cutout'],
        inputs: ['cutout_clean', 'style_constraints'],
        outputs: ['part_layers', 'rig_spec'],
        automation_targets: ['hero-runtime-pack', 'animation_agent'],
      },
      {
        id: 'asset_runtime_exports',
        label: 'Build runtime exports',
        kind: 'export',
        owner: 'integration',
        depends_on: ['asset_parts'],
        inputs: ['part_layers', 'rig_spec'],
        outputs: ['runtime_atlas', 'animation_manifest', 'qa_report'],
        automation_targets: ['pipeline.asset_factory'],
      },
    ],
  },
  {
    id: 'scene_assembly',
    label: 'Scene Assembly',
    runtime: 'temporal',
    objective: 'Build playable levels from boards, level kits, triggers, and runtime composition rules.',
    triggers: ['scene_backlog_item_ready', 'systems_board_saved'],
    recovery_strategy: ['resume_from_scene_snapshot', 'diff_scene_sources', 'notify_level_design'],
    steps: [
      {
        id: 'scene_wireframe',
        label: 'Wireframe and anchors',
        kind: 'analysis',
        owner: 'level_design',
        inputs: ['world_board', 'world_composition'],
        outputs: ['wireframe_map', 'anchor_points'],
        automation_targets: ['construction_stack'],
      },
      {
        id: 'scene_layout',
        label: 'Layout and collisions',
        kind: 'integration',
        owner: 'gameplay_programming',
        depends_on: ['scene_wireframe'],
        inputs: ['wireframe_map', 'tileset_manifests', 'trigger_graph'],
        outputs: ['layout', 'scene_assembly', 'collision_map'],
        automation_targets: ['scene_runtime_builder'],
      },
      {
        id: 'scene_validation',
        label: 'Validate flow',
        kind: 'validation',
        owner: 'qa',
        depends_on: ['scene_layout'],
        inputs: ['scene_assembly', 'encounters'],
        outputs: ['scene_validation_report'],
        automation_targets: ['qa_validation_suite'],
      },
    ],
  },
  {
    id: 'runtime_integration',
    label: 'Runtime Integration',
    runtime: 'hybrid',
    objective: 'Bind gameplay systems, story, audio, and VFX into a preview runtime and a shipping runtime target.',
    triggers: ['scene_validated', 'runtime_target_changed'],
    recovery_strategy: ['rebuild_preview_bundle', 'rollback_last_runtime_patch', 'switch_runtime_adapter'],
    steps: [
      {
        id: 'runtime_bind_systems',
        label: 'Bind systems',
        kind: 'integration',
        owner: 'gameplay_programming',
        inputs: ['runtime_systems', 'scene_assembly', 'story_graph', 'audio_graph'],
        outputs: ['preview_runtime_bundle'],
        automation_targets: ['ellipse_engine'],
      },
      {
        id: 'runtime_export_shipping',
        label: 'Export shipping target',
        kind: 'export',
        owner: 'build_release',
        depends_on: ['runtime_bind_systems'],
        inputs: ['preview_runtime_bundle', 'build_targets'],
        outputs: ['shipping_export_manifest'],
        automation_targets: ['godot_adapter', 'build_targets'],
      },
    ],
  },
  {
    id: 'qa_release_gate',
    label: 'QA and Release Gate',
    runtime: 'hybrid',
    objective: 'Run production gates before promoting a slice or build target.',
    triggers: ['build_requested', 'milestone_gate_requested'],
    recovery_strategy: ['open_fix_batch', 'pause_release_lane', 'require_human_signoff'],
    steps: [
      {
        id: 'qa_asset_gate',
        label: 'Asset gate',
        kind: 'validation',
        owner: 'qa',
        inputs: ['asset_outputs', 'asset_cutting_qa'],
        outputs: ['asset_gate_report'],
        automation_targets: ['qa_validation_suite'],
      },
      {
        id: 'qa_runtime_gate',
        label: 'Runtime gate',
        kind: 'validation',
        owner: 'qa',
        depends_on: ['qa_asset_gate'],
        inputs: ['preview_runtime_bundle', 'mobile_presets'],
        outputs: ['runtime_gate_report'],
        automation_targets: ['playtest_checks', 'performance_checks'],
      },
      {
        id: 'qa_release_handoff',
        label: 'Release handoff',
        kind: 'handoff',
        owner: 'build_release',
        depends_on: ['qa_runtime_gate'],
        inputs: ['gate_reports', 'shipping_export_manifest'],
        outputs: ['release_candidate'],
        automation_targets: ['build_release_agent'],
      },
    ],
  },
]);

export function getDurableWorkflowCatalog() {
  return DURABLE_WORKFLOW_TEMPLATES.map((workflow) => structuredClone(workflow));
}
