/**
 * Export GDL → projet Godot minimal (.tscn + project.godot).
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { GameDefinition } from '@ellipse/shared';

export interface GodotExportResult {
  outDir: string;
  files: string[];
}

export async function exportGdlToGodot(
  gdl: GameDefinition,
  outDir: string,
  projectName = 'EllipseExport',
): Promise<GodotExportResult> {
  await mkdir(outDir, { recursive: true });
  const files: string[] = [];

  const projectGodot = `; Generated by Ellipse godot-adapter
config_version=5

[application]
config/name="${projectName}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.2", "Forward Plus")

[rendering]
textures/canvas_textures/default_texture_filter=0
`;
  await writeFile(join(outDir, 'project.godot'), projectGodot, 'utf-8');
  files.push('project.godot');

  const title = gdl.meta?.title ?? 'Game';
  const w = (gdl.meta as { resolution?: number[] })?.resolution?.[0] ?? 720;
  const h = (gdl.meta as { resolution?: number[] })?.resolution?.[1] ?? 1280;

  const mainTscn = `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="1"]

[node name="Main" type="Node2D"]
script = ExtResource("1")

[node name="Title" type="Label" parent="."]
offset_right = ${w}.0
offset_bottom = 40.0
text = "${title.replace(/"/g, '\\"')}"
horizontal_alignment = 1

[node name="Player" type="CharacterBody2D" parent="."]
position = Vector2(${w / 2}, ${h * 0.7})

[node name="Sprite" type="Sprite2D" parent="Player"]
`;
  await mkdir(join(outDir, 'scenes'), { recursive: true });
  await mkdir(join(outDir, 'scripts'), { recursive: true });
  await writeFile(join(outDir, 'scenes', 'main.tscn'), mainTscn, 'utf-8');
  files.push('scenes/main.tscn');

  const systems = (gdl.systems ?? []).map((s) => `"${s}"`).join(', ');
  const mainGd = `extends Node2D
# Ellipse export — systems: [${systems}]

func _ready():
\tprint("Ellipse → Godot: ${title.replace(/"/g, '\\"')}")
`;
  await writeFile(join(outDir, 'scripts', 'main.gd'), mainGd, 'utf-8');
  files.push('scripts/main.gd');

  const manifest = {
    source: 'ellipse-godot-adapter',
    generated_at: new Date().toISOString(),
    gdl_title: title,
    systems: gdl.systems ?? [],
    entities: gdl.entities?.map((e) => e.id) ?? [],
  };
  await writeFile(join(outDir, 'ellipse_manifest.json'), JSON.stringify(manifest, null, 2), 'utf-8');
  files.push('ellipse_manifest.json');

  return { outDir, files };
}
