import { toWorkspaceFile } from './constants.mjs';

export const BOARD_SOURCES = [
  {
    id: 'pitch',
    label: 'Pitch global et boucle de jeu',
    role: 'pitch',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_29_03 (1).png',
    workspace_file: 'pitch_veloria.png',
    concept_use: 'Vision produit, boucle de jeu, HUD de combat, direction visuelle premium.',
    tags: ['vertical-mobile', 'combat-hud', 'premium-dark-fantasy', 'hero-roster'],
  },
  {
    id: 'hub_levels',
    label: 'Ambiances, hub et niveaux',
    role: 'world',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_29_03 (3).png',
    workspace_file: 'ambiances_hub_niveaux.png',
    concept_use: 'Hub, ladder des niveaux, production rules, ennemis et hazards principaux.',
    tags: ['hub', 'level-ladder', 'hazards', 'enemy-lineup'],
  },
  {
    id: 'heroines_ii',
    label: 'Planches héroïnes II',
    role: 'heroine_expansion',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_29_03 (2).png',
    workspace_file: 'planches_heroines_ii.png',
    concept_use: 'Héroïnes additionnelles, rôles, armes, ultimes et palette.',
    tags: ['hero-roster', 'weapons', 'ultimates', 'roles'],
  },
  {
    id: 'gameplay_mobile_aureline',
    label: 'Gameplay mobile Auréline',
    role: 'gameplay',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_28_44 (1).png',
    workspace_file: 'gameplay_mobile_aureline.png',
    concept_use: 'HUD combat, bénédictions, lisibilité du combat, tutoriel de boucle.',
    tags: ['combat-preview', 'hud', 'blessings', 'aureline'],
  },
  {
    id: 'gameplay_elite_morgane',
    label: 'Gameplay phase élite Morgane',
    role: 'gameplay',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_28_44 (2).png',
    workspace_file: 'gameplay_phase_elite_morgane.png',
    concept_use: 'Dash, élite / mini-boss, danger de lane, lisibilité du combo.',
    tags: ['elite-combat', 'morgane', 'dash', 'miniboss'],
  },
  {
    id: 'main_roster_v2',
    label: 'Personnages principaux — version détaillée',
    role: 'hero_roster',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_27_50 (2).png',
    workspace_file: 'personnages_principaux_v2.png',
    concept_use: 'Roster jouable principal, armes iconiques, ultimes, silhouette canonique.',
    tags: ['hero-roster', 'main-cast', 'weapons', 'ultimates'],
  },
  {
    id: 'main_roster_v1',
    label: 'Personnages principaux — version alternative',
    role: 'hero_roster',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_27_30.png',
    workspace_file: 'personnages_principaux_v1.png',
    concept_use: 'Pose alternative, check de cohérence stylistique du roster.',
    tags: ['hero-roster', 'alt-poses', 'style-lock'],
  },
  {
    id: 'runes_sigils',
    label: 'Runes et sigilles',
    role: 'systems',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_27_51 (5).png',
    workspace_file: 'runes_sigilles.png',
    concept_use: 'Meta-progression, gravure, builds et raretés.',
    tags: ['runes', 'sigils', 'buildcraft', 'rarities'],
  },
  {
    id: 'relics_summons',
    label: 'Reliques et objets invocables',
    role: 'systems',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_27_52 (6).png',
    workspace_file: 'reliques_objets_invocables.png',
    concept_use: 'Relics permanentes, objets de lane et invocations en run.',
    tags: ['relics', 'summons', 'lane-objects', 'progression'],
  },
  {
    id: 'support_roster',
    label: 'Personnages de soutien',
    role: 'support_roster',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_27_51 (3).png',
    workspace_file: 'personnages_soutien.png',
    concept_use: 'Alliées et déclencheurs de soutien.',
    tags: ['supports', 'ally-trigger', 'passives'],
  },
  {
    id: 'equipment_sets',
    label: 'Équipements et sets',
    role: 'systems',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_27_51 (4).png',
    workspace_file: 'equipements_sets.png',
    concept_use: 'Slots, pièces de set, synergies et stat profile.',
    tags: ['equipment', 'sets', 'stats', 'rarities'],
  },
  {
    id: 'environment_boards',
    label: 'Planches environnements',
    role: 'world',
    source_path: 'c:/Users/phili/Downloads/VELORIA/ChatGPT Image 20 juin 2026, 19_27_50 (1).png',
    workspace_file: 'planches_environnements.png',
    concept_use: 'Bibliothèque des arènes, lanes et props réutilisables.',
    tags: ['environments', 'lanes', 'props', 'mobile-first'],
  },
];

export const HEROES = [
  {
    key: 'aureline',
    id: '82000000-0000-4000-8000-000000000001',
    title: 'Aureline',
    display_title: 'Aureline — Lanciere Sacree',
    role_text: 'Burst / Percee',
    weapon: 'Lance Celeste',
    archetype: 'Lumiere divine',
    pack_root: '03_assets/characters/heroines/hero__aureline-sacred-lancer',
    preview_file: '03_assets/characters/heroines/hero__aureline-sacred-lancer/02_cutouts/aureline_keyart.png',
    board: 'personnages_principaux_v2.png',
    crop: { x: 0.005, y: 0.09, width: 0.155, height: 0.55 },
    lane_style: 'frontline-pierce',
    blessing_bias: ['sacred_crit', 'piercing_arc', 'guard_break'],
  },
  {
    key: 'morgane',
    id: '82000000-0000-4000-8000-000000000002',
    title: 'Morgane',
    display_title: 'Morgane — Duelliste Corbeau',
    role_text: 'Dash / Assassinat',
    weapon: 'Lames Jumelles',
    archetype: 'Assassine nocturne',
    pack_root: '03_assets/characters/heroines/hero__morgane-raven-duelist',
    preview_file: '03_assets/characters/heroines/hero__morgane-raven-duelist/02_cutouts/morgane_keyart.png',
    board: 'personnages_principaux_v2.png',
    crop: { x: 0.172, y: 0.09, width: 0.155, height: 0.55 },
    lane_style: 'reactive-dash',
    blessing_bias: ['shadow_dash', 'combo_chain', 'execute_window'],
  },
  {
    key: 'selka',
    id: '82000000-0000-4000-8000-000000000003',
    title: 'Selka',
    display_title: 'Selka — Cantatrice Occulte',
    role_text: 'Zone / Charme',
    weapon: 'Baton Lunaire',
    archetype: 'Sirene occulte',
    pack_root: '03_assets/characters/heroines/hero__selka-occult-chanter',
    preview_file: '03_assets/characters/heroines/hero__selka-occult-chanter/02_cutouts/selka_keyart.png',
    board: 'personnages_principaux_v2.png',
    crop: { x: 0.338, y: 0.09, width: 0.155, height: 0.55 },
    lane_style: 'zone-control',
    blessing_bias: ['eclipse_zone', 'charm_field', 'energy_drain'],
  },
  {
    key: 'isolde',
    id: '82000000-0000-4000-8000-000000000004',
    title: 'Isolde',
    display_title: 'Isolde — Veuve Carmin',
    role_text: 'Tank / Saignement',
    weapon: 'Hallebarde et Bouclier',
    archetype: 'Guerriere maudite',
    pack_root: '03_assets/characters/heroines/hero__isolde-crimson-widow',
    preview_file: '03_assets/characters/heroines/hero__isolde-crimson-widow/02_cutouts/isolde_keyart.png',
    board: 'personnages_principaux_v2.png',
    crop: { x: 0.502, y: 0.09, width: 0.155, height: 0.55 },
    lane_style: 'bleed-anchor',
    blessing_bias: ['bleed_ring', 'guard_wall', 'thorns_retaliation'],
  },
  {
    key: 'roxane',
    id: '82000000-0000-4000-8000-000000000005',
    title: 'Roxane',
    display_title: 'Roxane — Arbaletriere du Bastion',
    role_text: 'Distance / Critique',
    weapon: 'Arbalete Redemptive',
    archetype: 'Tireuse d elite',
    pack_root: '03_assets/characters/heroines/hero__roxane-bastion-crossbow',
    preview_file: '03_assets/characters/heroines/hero__roxane-bastion-crossbow/02_cutouts/roxane_keyart.png',
    board: 'personnages_principaux_v2.png',
    crop: { x: 0.668, y: 0.09, width: 0.155, height: 0.55 },
    lane_style: 'ranged-crit',
    blessing_bias: ['bolt_storm', 'marked_target', 'crit_halo'],
  },
  {
    key: 'liora',
    id: '82000000-0000-4000-8000-000000000006',
    title: 'Liora',
    display_title: 'Liora — Oracle de Minuit',
    role_text: 'Malediction / Zone',
    weapon: 'Orbe Lunaire',
    archetype: 'Prophetesse astrale',
    pack_root: '03_assets/characters/heroines/hero__liora-midnight-oracle',
    preview_file: '03_assets/characters/heroines/hero__liora-midnight-oracle/02_cutouts/liora_keyart.png',
    board: 'personnages_principaux_v2.png',
    crop: { x: 0.834, y: 0.09, width: 0.155, height: 0.55 },
    lane_style: 'curse-zone',
    blessing_bias: ['void_orbit', 'malediction_spread', 'astral_burst'],
  },
];

export const SUPPORTS = [
  {
    key: 'celestine',
    id: '82000000-0000-4000-8000-000000000011',
    title: 'Celestine',
    display_title: "Celestine — Pretresse d'Aube",
    role_text: 'Soin / Bouclier',
    trigger: 'Toutes les 7 attaques',
    pack_root: '03_assets/characters/supports/support__celestine-dawn-priestess',
    preview_file: '03_assets/characters/supports/support__celestine-dawn-priestess/02_cutouts/celestine_support_card.png',
    board: 'personnages_soutien.png',
    crop: { x: 0.005, y: 0.09, width: 0.29, height: 0.41 },
  },
  {
    key: 'nymea',
    id: '82000000-0000-4000-8000-000000000012',
    title: 'Nymea',
    display_title: 'Nymea — Dryade des Epines',
    role_text: 'Controle / Poison',
    trigger: 'Quand un ennemi traverse une voie',
    pack_root: '03_assets/characters/supports/support__nymea-thorn-dryad',
    preview_file: '03_assets/characters/supports/support__nymea-thorn-dryad/02_cutouts/nymea_support_card.png',
    board: 'personnages_soutien.png',
    crop: { x: 0.31, y: 0.09, width: 0.29, height: 0.41 },
  },
  {
    key: 'vesper',
    id: '82000000-0000-4000-8000-000000000013',
    title: 'Vesper',
    display_title: 'Vesper — Danse-Lame du Loup',
    role_text: 'Assassinat / Dash',
    trigger: 'Quand un ennemi passe sous 20% PV',
    pack_root: '03_assets/characters/supports/support__vesper-wolf-blade',
    preview_file: '03_assets/characters/supports/support__vesper-wolf-blade/02_cutouts/vesper_support_card.png',
    board: 'personnages_soutien.png',
    crop: { x: 0.61, y: 0.09, width: 0.24, height: 0.41 },
  },
  {
    key: 'ilyane',
    id: '82000000-0000-4000-8000-000000000014',
    title: 'Soeur Ilyane',
    display_title: 'Soeur Ilyane — Purification / Protection',
    role_text: 'Purification / Protection',
    trigger: 'Quand le personnage subit un controle fort',
    pack_root: '03_assets/characters/supports/support__ilyane-sacred-ward',
    preview_file: '03_assets/characters/supports/support__ilyane-sacred-ward/02_cutouts/ilyane_support_card.png',
    board: 'personnages_soutien.png',
    crop: { x: 0.005, y: 0.50, width: 0.29, height: 0.38 },
  },
  {
    key: 'maera',
    id: '82000000-0000-4000-8000-000000000015',
    title: 'Maera des Cendres',
    display_title: 'Maera des Cendres — Porte-Etendard du Crepuscule',
    role_text: 'Brulure / Banniere',
    trigger: 'Quand le personnage inflige des degats de zone',
    pack_root: '03_assets/characters/supports/support__maera-cinder-standard',
    preview_file: '03_assets/characters/supports/support__maera-cinder-standard/02_cutouts/maera_support_card.png',
    board: 'personnages_soutien.png',
    crop: { x: 0.31, y: 0.50, width: 0.29, height: 0.38 },
  },
  {
    key: 'elsinor',
    id: '82000000-0000-4000-8000-000000000016',
    title: 'Elsinor la Corneille',
    display_title: "Elsinor la Corneille — Murmureuse d'Ombre",
    role_text: 'Malediction / Drain',
    trigger: "Quand l'heroine attaque un elite",
    pack_root: '03_assets/characters/supports/support__elsinor-shadow-crow',
    preview_file: '03_assets/characters/supports/support__elsinor-shadow-crow/02_cutouts/elsinor_support_card.png',
    board: 'personnages_soutien.png',
    crop: { x: 0.61, y: 0.50, width: 0.24, height: 0.38 },
  },
];

export const ENEMIES = [
  {
    key: 'fallen_knight',
    id: '82000000-0000-4000-8000-000000000021',
    title: 'Chevalier dechu',
    display_title: 'Chevalier dechu',
    role_text: 'Bruiser de lane',
    pack_root: '03_assets/characters/enemies/enemy__fallen-knight',
    preview_file: '03_assets/characters/enemies/enemy__fallen-knight/02_cutouts/fallen_knight_preview.png',
    board: 'gameplay_mobile_aureline.png',
    crop: { x: 0.36, y: 0.15, width: 0.27, height: 0.32 },
  },
  {
    key: 'tomb_hound',
    id: '82000000-0000-4000-8000-000000000022',
    title: 'Chien des tombes',
    display_title: 'Chien des tombes',
    role_text: 'Charge rapide',
    pack_root: '03_assets/characters/enemies/enemy__tomb-hound',
    preview_file: '03_assets/characters/enemies/enemy__tomb-hound/02_cutouts/tomb_hound_preview.png',
    board: 'gameplay_mobile_aureline.png',
    crop: { x: 0.26, y: 0.24, width: 0.13, height: 0.18 },
  },
  {
    key: 'gargoyle',
    id: '82000000-0000-4000-8000-000000000023',
    title: 'Gargouille',
    display_title: 'Gargouille',
    role_text: 'Pique aerienne',
    pack_root: '03_assets/characters/enemies/enemy__gargoyle',
    preview_file: '03_assets/characters/enemies/enemy__gargoyle/02_cutouts/gargoyle_preview.png',
    board: 'gameplay_mobile_aureline.png',
    crop: { x: 0.56, y: 0.18, width: 0.18, height: 0.2 },
  },
  {
    key: 'fanatic_sister',
    id: '82000000-0000-4000-8000-000000000024',
    title: 'Soeur fanatique',
    display_title: 'Soeur fanatique',
    role_text: 'Canalisation / Malus',
    pack_root: '03_assets/characters/enemies/enemy__fanatic-sister',
    preview_file: '03_assets/characters/enemies/enemy__fanatic-sister/02_cutouts/fanatic_sister_preview.png',
    board: 'ambiances_hub_niveaux.png',
    crop: { x: 0.64, y: 0.70, width: 0.1, height: 0.18 },
  },
  {
    key: 'shadow_acolyte',
    id: '82000000-0000-4000-8000-000000000025',
    title: 'Acolyte des ombres',
    display_title: 'Acolyte des ombres',
    role_text: 'Occultiste',
    pack_root: '03_assets/characters/enemies/enemy__shadow-acolyte',
    preview_file: '03_assets/characters/enemies/enemy__shadow-acolyte/02_cutouts/shadow_acolyte_preview.png',
    board: 'ambiances_hub_niveaux.png',
    crop: { x: 0.64, y: 0.80, width: 0.1, height: 0.16 },
  },
];

export const BOSSES = [
  {
    key: 'bourreau',
    id: '82000000-0000-4000-8000-000000000031',
    title: 'Bourreau',
    display_title: 'Bourreau — Boss de tranche',
    role_text: 'Boss / Jugement',
    pack_root: '03_assets/characters/bosses/boss__bourreau-crepuscule',
    preview_file: '03_assets/characters/bosses/boss__bourreau-crepuscule/02_cutouts/bourreau_preview.png',
    board: 'gameplay_phase_elite_morgane.png',
    crop: { x: 0.39, y: 0.12, width: 0.29, height: 0.36 },
  },
];

export const ENVIRONMENTS = [
  {
    key: 'pavillon_veilles',
    id: '82000000-0000-4000-8000-000000000041',
    title: 'Pavillon des Veilles',
    display_title: 'Hub — Pavillon des Veilles',
    role_text: 'Hub compact circulaire',
    pack_root: '03_assets/environments/hub__pavillon-des-veilles',
    preview_file: '03_assets/environments/hub__pavillon-des-veilles/02_cutouts/pavillon_hub_preview.png',
    board: 'ambiances_hub_niveaux.png',
    crop: { x: 0.235, y: 0.09, width: 0.28, height: 0.28 },
  },
  {
    key: 'ruined_cloister',
    id: '82000000-0000-4000-8000-000000000042',
    title: 'Cloitre en ruine',
    display_title: 'Cloitre en ruine',
    role_text: 'Level 01 starter arena',
    pack_root: '03_assets/environments/arena__ruined-cloister',
    preview_file: '03_assets/environments/arena__ruined-cloister/02_cutouts/ruined_cloister_preview.png',
    board: 'planches_environnements.png',
    crop: { x: 0.02, y: 0.12, width: 0.17, height: 0.2 },
  },
  {
    key: 'pyre_road',
    id: '82000000-0000-4000-8000-000000000043',
    title: 'Route des Buchers',
    display_title: 'Route des Buchers',
    role_text: 'Flame sweep lane hazard',
    pack_root: '03_assets/environments/arena__pyre-road',
    preview_file: '03_assets/environments/arena__pyre-road/02_cutouts/pyre_road_preview.png',
    board: 'planches_environnements.png',
    crop: { x: 0.35, y: 0.12, width: 0.17, height: 0.2 },
  },
  {
    key: 'statue_garden',
    id: '82000000-0000-4000-8000-000000000044',
    title: 'Jardin des statues',
    display_title: 'Jardin des statues',
    role_text: 'Stone garden and spike hazard',
    pack_root: '03_assets/environments/arena__statue-garden',
    preview_file: '03_assets/environments/arena__statue-garden/02_cutouts/statue_garden_preview.png',
    board: 'planches_environnements.png',
    crop: { x: 0.675, y: 0.12, width: 0.17, height: 0.2 },
  },
  {
    key: 'drowned_port',
    id: '82000000-0000-4000-8000-000000000045',
    title: 'Port des noyes',
    display_title: 'Port des noyes',
    role_text: 'Flooded dock arena',
    pack_root: '03_assets/environments/arena__drowned-port',
    preview_file: '03_assets/environments/arena__drowned-port/02_cutouts/drowned_port_preview.png',
    board: 'planches_environnements.png',
    crop: { x: 0.02, y: 0.52, width: 0.17, height: 0.2 },
  },
  {
    key: 'candle_crypt',
    id: '82000000-0000-4000-8000-000000000046',
    title: 'Crypte des chandelles',
    display_title: 'Crypte des chandelles',
    role_text: 'Occult interior arena',
    pack_root: '03_assets/environments/arena__candle-crypt',
    preview_file: '03_assets/environments/arena__candle-crypt/02_cutouts/candle_crypt_preview.png',
    board: 'planches_environnements.png',
    crop: { x: 0.35, y: 0.52, width: 0.17, height: 0.2 },
  },
  {
    key: 'crepuscule_throne',
    id: '82000000-0000-4000-8000-000000000047',
    title: 'Trone du crepuscule',
    display_title: 'Trone du crepuscule',
    role_text: 'Endgame throne arena',
    pack_root: '03_assets/environments/arena__crepuscule-throne',
    preview_file: '03_assets/environments/arena__crepuscule-throne/02_cutouts/crepuscule_throne_preview.png',
    board: 'planches_environnements.png',
    crop: { x: 0.675, y: 0.52, width: 0.17, height: 0.2 },
  },
];

export const SYSTEM_ASSETS = [
  {
    key: 'combat_hud',
    id: '82000000-0000-4000-8000-000000000051',
    title: 'Combat HUD mobile',
    display_title: 'HUD combat vertical',
    role: 'ui',
    kind: 'ui',
    pack_root: '03_assets/ui/ui__combat-hud-shell',
    preview_file: '03_assets/ui/ui__combat-hud-shell/02_cutouts/combat_hud_preview.png',
    board: 'gameplay_mobile_aureline.png',
    crop: { x: 0.29, y: 0.08, width: 0.43, height: 0.76 },
  },
  {
    key: 'rune_blade',
    id: '82000000-0000-4000-8000-000000000052',
    title: 'Rune de lame',
    display_title: 'Rune de lame',
    role: 'relic',
    kind: 'prop',
    pack_root: '03_assets/props/relics/relic__blade-rune',
    preview_file: '03_assets/props/relics/relic__blade-rune/02_cutouts/blade_rune_preview.png',
    board: 'runes_sigilles.png',
    crop: { x: 0.01, y: 0.17, width: 0.13, height: 0.3 },
  },
  {
    key: 'mirror_watchers',
    id: '82000000-0000-4000-8000-000000000053',
    title: 'Miroir des veilles',
    display_title: 'Miroir des veilles',
    role: 'relic',
    kind: 'prop',
    pack_root: '03_assets/props/relics/relic__mirror-of-watchers',
    preview_file: '03_assets/props/relics/relic__mirror-of-watchers/02_cutouts/mirror_watchers_preview.png',
    board: 'reliques_objets_invocables.png',
    crop: { x: 0.02, y: 0.13, width: 0.11, height: 0.33 },
  },
  {
    key: 'veille_set',
    id: '82000000-0000-4000-8000-000000000054',
    title: "Set Veille de l'Aube",
    display_title: "Set Veille de l'Aube",
    role: 'armor',
    kind: 'prop',
    pack_root: '03_assets/props/equipment/equipment__veille-aube-set',
    preview_file: '03_assets/props/equipment/equipment__veille-aube-set/02_cutouts/veille_set_preview.png',
    board: 'equipements_sets.png',
    crop: { x: 0.06, y: 0.55, width: 0.2, height: 0.22 },
  },
];

export const ALL_ASSETS = [
  ...HEROES.map((hero) => ({ ...hero, role: 'hero', kind: 'character', status: 'source_ready' })),
  ...SUPPORTS.map((support) => ({ ...support, role: 'companion', kind: 'character', status: 'source_ready' })),
  ...ENEMIES.map((enemy) => ({ ...enemy, role: 'enemy', kind: 'character', status: 'source_ready' })),
  ...BOSSES.map((boss) => ({ ...boss, role: 'boss', kind: 'character', status: 'source_ready' })),
  ...ENVIRONMENTS.map((environment) => ({ ...environment, role: 'environment', kind: 'environment', status: 'source_ready' })),
  ...SYSTEM_ASSETS.map((asset) => ({ ...asset, status: asset.role === 'ui' ? 'concept' : 'source_ready' })),
];

export const RARITY_TIERS = [
  { id: 'common', label: 'Commune', color: '#8e8e90' },
  { id: 'uncommon', label: 'Peu commune', color: '#7cbf5e' },
  { id: 'rare', label: 'Rare', color: '#4f7cff' },
  { id: 'epic', label: 'Epique', color: '#a65cff' },
  { id: 'legendary', label: 'Legendaire', color: '#ffbf4d' },
  { id: 'mythic', label: 'Mythique', color: '#d14d4d' },
];

export const RUNES = [
  { key: 'blade_rune', title: 'Rune de Lame', family: 'offensive', rarity: 'legendary', slot: 'weapon', effect: '+18% degats physiques, chance de saignement.' },
  { key: 'predator_sigil', title: 'Sigille du Predateur', family: 'offensive', rarity: 'mythic', slot: 'weapon', effect: '+25% degats critiques, rend 1% PV sur critique.' },
  { key: 'guard_rune', title: 'Rune de Garde', family: 'defensive', rarity: 'rare', slot: 'armor', effect: '+25% garde, reduit les degats subis.' },
  { key: 'moon_rune', title: 'Rune Lunaire', family: 'defensive', rarity: 'rare', slot: 'relic', effect: '+8% resistance magique, reduit les degats de competences ennemies.' },
  { key: 'grace_rune', title: 'Rune de Grace', family: 'support', rarity: 'uncommon', slot: 'jewel', effect: '+12% soin recu.' },
  { key: 'eclipse_rune', title: 'Rune d Eclipse', family: 'corrupted', rarity: 'epic', slot: 'weapon', effect: '+20% degats, mais augmente les degats subis de 10%.' },
];

export const RELICS = [
  { key: 'mirror_watchers', title: 'Miroir des Veilles', rarity: 'mythic', passive: '+25% DGT critiques apres 6 vagues ; nuit -10% DGT subis.' },
  { key: 'martyrs_bell', title: 'Cloche des Martyrs', rarity: 'mythic', passive: 'Les ennemis proches subissent 15% des PV max en degats sacres a chaque vague.' },
  { key: 'thorn_crown', title: "Couronne d'Epines", rarity: 'legendary', passive: '+20% vol de vie ; les ennemis qui vous touchent saignent.' },
  { key: 'dawn_incense', title: "Encensoir d'Aube", rarity: 'legendary', passive: 'Les competences beneficient de 12% d acceleration et +1 charge d ultime au depart.' },
];

export const SUMMONS = [
  { key: 'grace_totem', title: 'Totem de Grace', rarity: 'mythic', lane_effect: 'Soin de proximite pendant 8 s.' },
  { key: 'spectral_blade', title: 'Lame Spectrale', rarity: 'mythic', lane_effect: 'Degats massifs sur une lane, ignore 30% de la defense.' },
  { key: 'cinder_banner', title: 'Banniere de Cendre', rarity: 'legendary', lane_effect: '+20% DGT allies et +15% vitesse d attaque pendant 12 s.' },
  { key: 'watch_altar', title: 'Autel de Veille', rarity: 'rare', lane_effect: '+15% DGT critiques des allies pendant 3 vagues.' },
];

export const EQUIPMENT_SETS = [
  {
    key: 'veille_aube',
    title: "Veille de l'Aube",
    fantasy: 'sacred',
    pieces: ['Lance de l Aurore', 'Cuirasse de l Aube', 'Insigne de l Ordre', 'Reliquaire de Lumiere', 'Marche des Auriges', 'Couronne Solaire'],
    bonuses: [
      '2 pieces: +15% DGT sacres, +10% soin.',
      '4 pieces: quand une benediction est active, +25% Crit et regenere 5% PV toutes les 2 s.',
    ],
  },
  {
    key: 'messe_corbeaux',
    title: 'Messe des Corbeaux',
    fantasy: 'shadow',
    pieces: ['Faucille du Crepuscule', 'Manteau des Corbeaux', 'Sigille du Lamentin', 'Coeur d Echo', 'Pas du Predateur', 'Diademe des Ombres'],
    bonuses: [
      '2 pieces: +15% DGT ombre, +10% vol de vie.',
      '4 pieces: les competences marquent les ennemis, +20% DGT contre marques.',
    ],
  },
  {
    key: 'bastion_crepuscule',
    title: 'Bastion du Crepuscule',
    fantasy: 'iron-crimson',
    pieces: ['Hallebarde du Bastion', 'Armure de Saignement', 'Insigne du Jugement', 'Talisman du Flambeau'],
    bonuses: [
      '2 pieces: +20% Garde, +10% PV max.',
      '4 pieces: sous 30% PV, gagne un bouclier absorbant 20% des PV max et inflige +25% DGT pendant 6 s.',
    ],
  },
];

export const LEVEL_LADDER = [
  {
    key: 'level_01',
    title: 'Cloitre en Ruine',
    hazard: 'Effondrement',
    enemy: 'Chevalier dechu',
    lane_palette: ['stone', 'ivory', 'ember'],
  },
  {
    key: 'level_02',
    title: 'Route des Buchers',
    hazard: 'Flammes balayantes',
    enemy: 'Chien des tombes',
    lane_palette: ['coal', 'amber', 'ash'],
  },
  {
    key: 'level_03',
    title: 'Jardin des Statues',
    hazard: 'Piques sortantes',
    enemy: 'Gargouille',
    lane_palette: ['emerald', 'stone', 'silver'],
  },
  {
    key: 'level_04',
    title: 'Port des Noyes',
    hazard: 'Marevague',
    enemy: 'Soeur fanatique',
    lane_palette: ['steel', 'indigo', 'mist'],
  },
  {
    key: 'level_05',
    title: 'Crypte des Chandelles',
    hazard: 'Cercle occulte',
    enemy: 'Acolyte des ombres',
    lane_palette: ['violet', 'gold', 'shadow'],
  },
  {
    key: 'level_06',
    title: 'Trone du Crepuscule',
    hazard: 'Lames oscillantes',
    enemy: 'Bourreau',
    lane_palette: ['crimson', 'black', 'bronze'],
  },
];

export const LEVEL_01_LAYOUT = {
  slug: 'level_01_cloitre_en_ruine',
  title: 'Cloitre en Ruine',
  mode: 'vertical_lane_arena',
  resolution: { width: 1080, height: 1920 },
  safe_zone: { top: 1460, height: 360 },
  enemy_spawn_band: { top: 160, height: 360 },
  lane_count: 3,
  lanes: [
    { id: 'lane_left', x: 170, width: 220, label: 'Voie gauche' },
    { id: 'lane_center', x: 430, width: 220, label: 'Voie centrale' },
    { id: 'lane_right', x: 690, width: 220, label: 'Voie droite' },
  ],
  anchor_points: {
    heroine_spawn: { x: 540, y: 1540 },
    boss_spawn: { x: 540, y: 360 },
    blessing_overlay: { x: 540, y: 1210 },
    summon_slots: [
      { x: 260, y: 1180, lane: 'lane_left' },
      { x: 540, y: 1180, lane: 'lane_center' },
      { x: 820, y: 1180, lane: 'lane_right' },
    ],
  },
  hazard: {
    id: 'collapsing_floor',
    label: 'Effondrement',
    telegraph_duration_ms: 1400,
    collapse_duration_ms: 3200,
    affected_lanes: ['lane_left', 'lane_center', 'lane_right'],
    rule: 'Une seule lane se fracture a la fois ; priorité a la lane la plus peuplee.',
  },
  art_modules: {
    background: 'arena__ruined-cloister',
    foreground_props: ['ruined-pillars', 'prayer-banners', 'candle-altars'],
    combat_hud: 'ui__combat-hud-shell',
  },
};

export const LEVEL_01_ENCOUNTERS = {
  stage: 'vertical_slice',
  heroine_default: 'aureline',
  total_waves: 12,
  blessing_breaks_after_waves: [3, 6, 9],
  waves: [
    { wave: 1, enemies: [{ type: 'fallen_knight', lane: 'lane_center', count: 1 }] },
    { wave: 2, enemies: [{ type: 'fallen_knight', lane: 'lane_left', count: 1 }, { type: 'fallen_knight', lane: 'lane_right', count: 1 }] },
    { wave: 3, enemies: [{ type: 'tomb_hound', lane: 'lane_left', count: 1 }, { type: 'fallen_knight', lane: 'lane_center', count: 1 }, { type: 'tomb_hound', lane: 'lane_right', count: 1 }] },
    { wave: 4, enemies: [{ type: 'fallen_knight', lane: 'lane_left', count: 2 }, { type: 'fallen_knight', lane: 'lane_right', count: 2 }] },
    { wave: 5, enemies: [{ type: 'fanatic_sister', lane: 'lane_center', count: 1 }, { type: 'tomb_hound', lane: 'lane_left', count: 1 }, { type: 'tomb_hound', lane: 'lane_right', count: 1 }] },
    { wave: 6, enemies: [{ type: 'gargoyle', lane: 'lane_center', count: 1 }, { type: 'fallen_knight', lane: 'lane_left', count: 1 }, { type: 'fallen_knight', lane: 'lane_right', count: 1 }] },
    { wave: 7, enemies: [{ type: 'fallen_knight', lane: 'lane_left', count: 2 }, { type: 'fallen_knight', lane: 'lane_center', count: 2 }, { type: 'fallen_knight', lane: 'lane_right', count: 2 }] },
    { wave: 8, enemies: [{ type: 'shadow_acolyte', lane: 'lane_left', count: 1 }, { type: 'tomb_hound', lane: 'lane_center', count: 2 }, { type: 'shadow_acolyte', lane: 'lane_right', count: 1 }] },
    { wave: 9, enemies: [{ type: 'gargoyle', lane: 'lane_left', count: 1 }, { type: 'gargoyle', lane: 'lane_right', count: 1 }, { type: 'fallen_knight', lane: 'lane_center', count: 2 }] },
    { wave: 10, enemies: [{ type: 'fallen_knight', lane: 'lane_center', count: 1, variant: 'elite_prior' }, { type: 'tomb_hound', lane: 'lane_left', count: 1 }, { type: 'tomb_hound', lane: 'lane_right', count: 1 }], hazard: 'collapsing_floor' },
    { wave: 11, enemies: [{ type: 'fanatic_sister', lane: 'lane_left', count: 1 }, { type: 'shadow_acolyte', lane: 'lane_right', count: 1 }, { type: 'fallen_knight', lane: 'lane_center', count: 2 }], hazard: 'collapsing_floor' },
    { wave: 12, boss: { type: 'bourreau', phase_count: 3, spawn_lane: 'lane_center' }, adds: [{ type: 'tomb_hound', lane: 'lane_left', count: 1 }, { type: 'tomb_hound', lane: 'lane_right', count: 1 }] },
  ],
};

export const LEVEL_01_BLESSINGS = [
  { id: 'sacred_edge', label: 'Lame Celeste', rarity: 'heroic', effect: '+20% degats, vos frappes percent les ennemis.' },
  { id: 'divine_grace', label: 'Grace Divine', rarity: 'benefique', effect: '+15% vitesse attaque, soigne 1% PV a chaque vague.' },
  { id: 'iron_will', label: 'Volonte de Fer', rarity: 'solide', effect: '+10% resistance, +1 garde au debut de la prochaine vague.' },
  { id: 'shadow_step', label: 'Pas d Ombre', rarity: 'epic', effect: 'Apres un dash, prochaine attaque critique garantie.' },
  { id: 'lunar_echo', label: 'Echo Lunaire', rarity: 'epic', effect: 'Les competences laissent une zone persistante 2 s de plus.' },
  { id: 'ember_contract', label: 'Contrat de Cendre', rarity: 'corrupted', effect: '+25% degats, mais chaque wave retire 2% PV max.' },
];

export const PRODUCTION_RULES = {
  pillars: [
    'Une heroine a l ecran, trois lanes lisibles.',
    'Runs de 3 minutes maximum avec tension montante.',
    'Peu d ennemis simultanes, silhouettes claires.',
    'Un hazard unique par arene.',
    'HUD premium leger, actions telegraphiees.',
    'Reutilisation modulaire des props et des decors.',
  ],
  constraints: {
    target_platforms: ['mobile', 'web'],
    preferred_resolution: 'portrait-first',
    simultaneous_enemies_soft_cap: 5,
    hazard_per_arena: 1,
    ui_density: 'lightweight',
  },
  palette: ['or_sacre', 'violet_occulte', 'pourpre', 'carmin', 'bronze', 'indigo', 'noir'],
};

export const REFERENCE_INDEX_PATHS = BOARD_SOURCES.map((board) => board.workspace_file);

export const PREP_MANIFEST = {
  project_title: 'Veloria — Veille des Lames',
  focus: 'Préproduction complète du jeu vertical mobile dark fantasy premium.',
  outputs: [
    toWorkspaceFile('01_inputs', 'references', 'reference-index.json'),
    toWorkspaceFile('02_design', 'specs', 'veloria-concept-bible.md'),
    toWorkspaceFile('03_assets', 'registry', 'studio-asset-catalog.json'),
    toWorkspaceFile('04_scenes', 'level_01', 'scene-assembly.json'),
    toWorkspaceFile('05_runtime', 'config', 'veloria-runtime-bundle.json'),
  ],
};
