import {createRuins,command,stepRuins,selectHero,interact,objective,findPath,canWalk,distance,KITS,WALK_AREAS,COLLIDERS} from './ruins-rules.mjs';
import {createRuinsScene} from './ruins-scene.mjs';
import {ruinsBonuses,startRuinsRun,finishRuinsRun} from './ruins-profile.mjs';
let storage;try{storage=localStorage;}catch{storage=null;}
const $=id=>document.getElementById(id),state=createRuins(ruinsBonuses(storage)),keys=new Set(),reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,saveKey='shadow-echoes:ruins:v1';let scene,raf,last=performance.now(),lastUi=0,day=false,sound=false,audio,lastEvent=-1,noticeUntil=0,resultShown=false,pausedBeforeRules=false,endTime=0,runId=null,tracked=false,dir={x:0,z:-1},touch={x:0,z:0},tacticalView=false;
const clock=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function notice(text){$('notice').textContent=text;$('notice').classList.add('visible');noticeUntil=performance.now()+2400;}
function ping(type){if(!sound)return;try{audio??=new AudioContext();void audio.resume();const o=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime;o.type=type==='hurt'?'triangle':'sine';o.frequency.setValueAtTime(type==='hurt'?115:type==='clear'?520:type==='spell'?390:250,t);o.frequency.exponentialRampToValueAtTime(type==='clear'?780:110,t+.16);gain.gain.setValueAtTime(.055,t);gain.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(t+.23);o.onended=()=>{o.disconnect();gain.disconnect();};}catch{sound=false;$('sound').textContent='Son indisponible';}}
function pause(value){if(state.status!=='playing')return;state.paused=value;keys.clear();touch={x:0,z:0};$('pause-overlay').hidden=!value;$('pause').textContent=value?'Reprendre':'Pause';$('pause').setAttribute('aria-pressed',String(value));}
function action(name){if(command(state,name,dir)){ping('action');updateUi();}else if(name==='ultimate'&&state.party[state.selected].energy<100)notice('Le super demande 100 énergie.');}
function switchHero(i){if(selectHero(state,i)){updateUi();notice(`${KITS[state.party[i].id].name} mène le groupe.`);}}
function minimap(){const c=$('map'),ctx=c.getContext('2d'),sx=x=>80+x*6,sy=z=>15+(z+28)*4;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#425460';for(const [a,b,d,e]of WALK_AREAS)ctx.fillRect(sx(a),sy(d),(b-a)*6,(e-d)*4);ctx.fillStyle='#192331';for(const o of COLLIDERS)ctx.fillRect(sx(o.x-o.w/2),sy(o.z-o.d/2),o.w*6,o.d*4);for(const e of state.enemies)if(e.hp>0){ctx.fillStyle=e.boss?'#f29976':'#d9677e';ctx.beginPath();ctx.arc(sx(e.x),sy(e.z),e.boss?4:2.8,0,Math.PI*2);ctx.fill();}state.party.forEach((h,i)=>{if(h.hp<=0)return;ctx.fillStyle=i===state.selected?'#ffdf9f':'#a7cfe0';ctx.beginPath();ctx.arc(sx(h.x),sy(h.z),i===state.selected?3.5:2,0,Math.PI*2);ctx.fill();});ctx.fillStyle='#b9c9cc';ctx.font='9px Arial';ctx.fillText('ARÈNE',62,9);}
function updateUi(){const h=state.party[state.selected],kit=KITS[h.id];$('hero-name').textContent=kit.name;$('health').textContent=`${Math.ceil(h.hp)} / ${h.maxHp} PV${h.shield?' · '+Math.ceil(h.shield)+' bouclier':''}`;$('energy').textContent=`✧ ${Math.floor(h.energy)} / 100`;$('objective').textContent=objective(state);$('time').textContent=clock(state.time);$('stage').textContent=['ENTRÉE DES RUINES','LE PONT & LES VESTIGES','ARÈNE DU SEUIL'][state.stage];
 for(const [i,b]of [...$('party').children].entries()){b.setAttribute('aria-pressed',String(i===state.selected));b.classList.toggle('fallen',state.party[i].hp<=0);b.querySelector('progress').value=state.party[i].hp;b.title=`${KITS[state.party[i].id].name} · ${Math.ceil(state.party[i].hp)} PV`;}
 for(const [i,b]of [...$('actions').children].entries()){b.querySelector('span').textContent=i===0?'Attaque':i<4?kit.skills[i-1]:i===4?kit.ultimate:'Esquive';b.querySelector('small').textContent=h.cooldowns[i]>.05?`${h.cooldowns[i].toFixed(1)} s`:i===4?'100 ✧':'';b.disabled=state.status!=='playing'||state.paused||h.cooldowns[i]>.05||(i===4&&h.energy<100);}
 $('rest').hidden=state.rested||!state.cleared.includes(1)||distance(h,{x:3,z:-10})>2.6||state.status!=='playing';$('boss').hidden=state.stage!==2||state.status!=='playing';$('boss-health').value=state.enemies.at(-1).hp;minimap();
}
function finish(){if(resultShown)return;resultShown=true;keys.clear();const won=state.status==='won',survivors=state.party.filter(h=>h.hp>0).length;$('result-kicker').textContent=won?'LE SEUIL EST LIBÉRÉ':'LES ÉCHOS VOUS RAMÈNENT';$('result-title').textContent=won?'Le serment tient.':'Le Voile a résisté.';$('result-stats').textContent=`${clock(state.time)} · ${state.kills} / 7 ennemis vaincus · ${survivors} Mythiques debout.`;
 const result=tracked?finishRuinsRun(storage,runId,won,{time:state.time,survivors}):{ok:false,reason:'unavailable'};
 if(won)try{const old=JSON.parse(storage.getItem(saveKey)||'null');const valid=old&&Number.isFinite(old.best)&&Number.isSafeInteger(old.wins)&&old.wins>=0;storage.setItem(saveKey,JSON.stringify({version:1,wins:(valid?old.wins:0)+1,best:Math.min(valid?old.best:Infinity,state.time),last:new Date().toISOString()}));}catch{}
 if(result.ok&&won){const r=result.reward;$('save-note').textContent=`Carnet mis à jour : +${r.gold} or · +${r.sigils} sceau · +${r.xp} XP de compte · +${r.essence} essence · +${r.heroXP.seraphine.amount} XP pour chaque Mythique${r.equipment.length?' · équipement trouvé':''}${r.relic?' · relique trouvée':''}.`;
 }else if(result.ok)$('save-note').textContent='Défaite enregistrée. Aucune récompense attribuée.';
 else $('save-note').textContent=result.reason==='replaced'?'Une autre épreuve a remplacé cette session : aucune récompense attribuée.':'Le carnet est indisponible : aucune récompense attribuée. Exportez votre sauvegarde depuis la Citadelle.';
 setTimeout(()=>$('result').showModal(),900);
}
try{
 scene=createRuinsScene($('scene'),state,{reduced});
 $('party').innerHTML=state.party.map((h,i)=>`<button data-hero="${i}" aria-pressed="${i===0}"><img src="../../03_assets/characters/${h.id}/presentation-v1.png" alt=""><strong>${KITS[h.id].name}</strong><progress max="${h.maxHp}" value="${h.hp}" aria-label="Vie de ${KITS[h.id].name}"></progress></button>`).join('');
 updateUi();$('welcome').showModal();try{const r=JSON.parse(storage.getItem(saveKey)||'null');if(r&&Number.isFinite(r.best)&&Number.isSafeInteger(r.wins))$('record').textContent=`Record local : ${r.wins} traversée(s) · meilleur temps ${clock(r.best)}`;}catch{}
 $('start').onclick=()=>{runId=crypto.randomUUID();tracked=startRuinsRun(storage,runId).ok;$('welcome').close();state.status='playing';scene.renderer.domElement.focus();ping('clear');updateUi();if(!tracked)notice('Carnet indisponible : traversée sans récompense.');};$('welcome').addEventListener('cancel',e=>e.preventDefault());
 $('pause').onclick=()=>pause(!state.paused);$('resume').onclick=()=>pause(false);
 $('rules').onclick=()=>{pausedBeforeRules=state.paused;pause(true);$('rules-dialog').showModal();};const closeRules=()=>{if(state.status==='playing')pause(pausedBeforeRules);};$('rules-dialog').addEventListener('close',closeRules);$('close-rules').onclick=()=>$('rules-dialog').close();
 $('camera').onclick=()=>{tacticalView=!tacticalView;scene.setCameraPreset(tacticalView?'tactical':'three-quarter');$('camera').textContent=tacticalView?'Vue 3/4':'Vue témoin';$('camera').setAttribute('aria-pressed',String(tacticalView));$('zoom').value=tacticalView?'5.5':'10';scene.setZoom(+$('zoom').value);scene.render(0);notice(tacticalView?'Cadrage latéral surélevé : aperçu visuel, combat en temps réel inchangé.':'Cadrage trois quarts restauré.');};
 if(new URLSearchParams(location.search).get('camera')==='tactical')$('camera').click();
 $('light').onclick=()=>{day=!day;scene.setDay(day);scene.render(0);$('light').textContent=day?'Nuit':'Aube';$('light').setAttribute('aria-pressed',String(day));};$('zoom').oninput=e=>{scene.setZoom(+e.target.value);scene.render(0);};
 $('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Son : oui':'Son : non';$('sound').setAttribute('aria-pressed',String(sound));if(sound)ping('clear');};
 $('rest').onclick=()=>{if(interact(state)){notice('Le groupe retrouve ses forces.');ping('spell');updateUi();}};$('retry').onclick=()=>location.reload();
 $('party').onclick=e=>{const b=e.target.closest('[data-hero]');if(b)switchHero(+b.dataset.hero);};$('actions').onclick=e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action);};
 scene.renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0||state.paused||state.status!=='playing')return;const p=scene.point(e.clientX,e.clientY);if(p){state.path=findPath(state.party[state.selected],p,(x,z)=>canWalk(state,x,z));if(!state.path.length)notice('Ce passage est fermé ou hors du chemin.');}scene.renderer.domElement.focus();});
 const movement=['KeyW','KeyA','KeyS','KeyD','KeyZ','KeyQ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'];
 window.addEventListener('keydown',e=>{if($('welcome').open||$('rules-dialog').open||$('result').open||e.target instanceof HTMLInputElement)return;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)pause(!state.paused);return;}if(state.paused||state.status!=='playing')return;if(movement.includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.repeat)return;const mapped={KeyJ:'basic',Digit1:'skill1',Digit2:'skill2',Digit3:'skill3',KeyR:'ultimate',Space:'dodge'}[e.code];if(mapped){e.preventDefault();action(mapped);}if(e.code==='KeyE')$('rest').click();if(e.code==='Tab'){e.preventDefault();for(let k=1;k<=4;k++){const i=(state.selected+k)%4;if(state.party[i].hp>0){switchHero(i);break;}}}});
 window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});
 for(const b of document.querySelectorAll('[data-dir]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch={up:{x:0,z:-1},down:{x:0,z:1},left:{x:-1,z:0},right:{x:1,z:0}}[b.dataset.dir];};for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>{touch={x:0,z:0};});}
 function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;const has=(...codes)=>codes.some(c=>keys.has(c)),x=Number(has('KeyD','ArrowRight'))-Number(has('KeyA','KeyQ','ArrowLeft'))+touch.x,z=Number(has('KeyS','ArrowDown'))-Number(has('KeyW','KeyZ','ArrowUp'))+touch.z,input=scene.screenToWorld(x,z);if(x||z)dir=input;stepRuins(state,dt,input);const ended=['won','lost'].includes(state.status);if(ended)endTime+=dt;if(!document.hidden&&!state.paused&&(state.status==='playing'||(ended&&endTime<3.5)))scene.render(dt);
  if(now-lastUi>100){updateUi();lastUi=now;for(const event of state.events)if(event.seq>lastEvent){if(event.type==='clear'){notice(event.stage===0?'Le pont est ouvert.':event.stage===1?'Les ruines sont libérées. Une source vous attend.':'Le Gardien tombe.');ping('clear');}if(event.type==='notice')notice(event.text);if(['spell','hurt'].includes(event.type))ping(event.type);lastEvent=event.seq;}}
  if(now>noticeUntil)$('notice').classList.remove('visible');if(['won','lost'].includes(state.status))finish();raf=requestAnimationFrame(frame);
 }raf=requestAnimationFrame(frame);
 window.addEventListener('pagehide',e=>{if(!e.persisted){cancelAnimationFrame(raf);scene.dispose();void audio?.close();}});
}catch(error){$('error').hidden=false;$('error').textContent='La scène 3D n’a pas pu démarrer. Vérifiez que WebGL 2 est disponible, puis rechargez la page. '+error.message;console.error(error);}
