import {renderHeroSheet} from './hero-sheet.mjs';
import {mountLivingPortrait} from './hero-actor-3d.mjs';
import {EQUIPMENT,SLOTS,RITUALS} from './edition-data.mjs';
import {ENCOUNTERS,KITS} from './ruins-rules.mjs';
import {mountRitual,transitionView} from './cinematic.mjs';
import {HEROES} from './heroes.mjs';
import {MODES,RELICS,QUESTS,ART} from './citadel-data.mjs';
import * as P from './profile.mjs';
import {mountActivity} from './activity-view.mjs';
const $=id=>document.getElementById(id),view=$('view'),fmt=n=>n.toLocaleString('fr-FR'),art=id=>`../../03_assets/characters/${id}/presentation-v1.png`;
let storage;try{storage=localStorage;}catch{storage={getItem(){throw Error();},setItem(){throw Error();}};}
const initial=P.readProfile(storage);let profile=initial.profile,route='',cleanup=()=>{},activeGame=null,toastTimer,audio,modalCleanup=()=>{},generation=0;
let ritualTier=1;
const gearArt=i=>`<span class="gear-art" style="--col:${i%3};--row:${Math.floor(i/3)}" aria-hidden="true"></span>`;
const gearEffect=e=>[e.attack?`+${Math.round(e.attack*100)} % dégâts`:'',e.health?`+${Math.round(e.health*100)} % vie`:''].filter(Boolean).join(' · ');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const itemArt=i=>`<span class="item-art" style="--col:${i%3};--row:${Math.floor(i/3)}" aria-hidden="true"></span>`;
const heroName=id=>HEROES.find(h=>h.id===id)?.name??'Mythique';
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3800);}
function persist(){const ok=P.saveProfile(storage,profile);$('save-state').textContent=ok?'✧ Progression sauvegardée':'Session en mémoire · exportez votre sauvegarde';updateBar();return ok;}
function mutate(fn){const fresh=P.readProfile(storage);if(!fresh.unavailable&&!fresh.recovered&&fresh.profile.revision>profile.revision)profile=fresh.profile;const result=fn(profile);persist();return result;}
function updateBar(){$('gold').textContent=fmt(profile.gold);$('sigils').textContent=fmt(profile.sigils);$('rank').textContent=`Voyageur · niveau ${1+Math.floor(profile.xp/300)}`;$('sound-toggle').setAttribute('aria-pressed',String(profile.settings.sound));$('sound-toggle').setAttribute('aria-label',profile.settings.sound?'Couper le son':'Activer le son');document.documentElement.classList.toggle('still',!profile.settings.motion||reduced.matches);}
function sound(kind='click'){if(!profile.settings.sound)return;try{audio??=new AudioContext();void audio.resume();const now=audio.currentTime;const notes=kind==='win'?[392,494,587]:kind==='summon'?[220,330,440,660]:kind==='fail'?[147,110]:[330];notes.forEach((hz,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),at=now+i*.12;osc.type='sine';osc.frequency.value=hz;gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(.09,at+.025);gain.gain.exponentialRampToValueAtTime(.0001,at+.5);osc.connect(gain);gain.connect(audio.destination);osc.start(at);osc.stop(at+.52);osc.onended=()=>{osc.disconnect();gain.disconnect();};});}catch{toast('Le son est indisponible sur ce navigateur.');}}
function portrait(host,id){return mountLivingPortrait(host,id,{motion:()=>profile.settings.motion&&!reduced.matches});}
function closeModal(){modalCleanup();modalCleanup=()=>{};$('modal').close();}
function modal(html){closeModal();$('modal-content').innerHTML=html;$('modal').showModal();}
$('modal-close').onclick=closeModal;$('modal').addEventListener('cancel',()=>{modalCleanup();modalCleanup=()=>{};});
function heading(kicker,title,text=''){return `<div class="page-heading"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1></div>${text?`<p>${text}</p>`:''}</div>`;}
function modeCard(m,compact=false){const completed=profile.modes[m.id]?.wins>0;return `<button class="mode-card ${compact?'compact':''} mode-${m.id}" data-mode="${m.id}" style="--accent:${m.color}"><span class="mode-number">${String(MODES.indexOf(m)+1).padStart(2,'0')} <small>${completed?'✓ ACCOMPLI':'NIVEAU 01'}</small></span><span class="mode-icon">${m.icon}</span><div><small>${m.kind} · ${m.duration}</small><h3>${m.name}</h3><p>${m.place}</p></div><span class="card-arrow">↗</span></button>`;}
function hub(){const completed=Object.values(profile.modes).filter(s=>s.wins>0).length;view.innerHTML=`<section class="hub-scene"><div class="hub-shade"></div><div class="embers" aria-hidden="true"></div><div class="hub-title"><p class="eyebrow">LE MONDE BRISÉ · CHAPITRE I</p><h1>La Citadelle<br>des Échos.</h1><p>Des mondes brisés.<br>Une lumière à préserver.</p><a class="gold-button" href="./ruins.html">Explorer le Pont des Serments <span>→</span></a></div><div class="hub-companion" aria-label="Votre Mythique"></div><button class="map-pin sanctuary" data-route="summon"><b>✧</b><span>Sanctuaire<small>INVOCATIONS</small></span></button><button class="map-pin gate" data-route="activities"><b>⚔</b><span>Portes du monde<small>10 AVENTURES</small></span></button><button class="map-pin archive" data-route="relics"><b>◇</b><span>Salle des reliques<small>${profile.relics.length} / 6 RETROUVÉES</small></span></button><button class="map-pin tavern" data-route="activities/mini"><b>⚄</b><span>La taverne du Voile<small>JEUX & RENCONTRES</small></span></button><div class="hub-chapter"><span>VOTRE CHRONIQUE</span><b>${completed}<small> / 10</small></b><p>Premiers niveaux accomplis</p><div class="progress"><i style="width:${completed*10}%"></i></div><a href="#quests">Voir les serments →</a></div><div class="hub-caption"><span>✦ CITÉ SOUS LA LUNE ROUGE</span><span>Quatre Mythiques vous accompagnent.</span></div></section><section class="home-bottom"><div class="section-title"><div><p class="eyebrow">AU-DELÀ DES REMPARTS</p><h2>Chaque chemin laisse un écho.</h2></div><a href="#activities">Toutes les activités →</a></div><a class="ruins-entry" href="./ruins.html"><span>NOUVEAU · NIVEAU JOUABLE EN 2,5D</span><strong>Le Pont des Serments</strong><small>Quatre héros · ruines à explorer · gardien à vaincre</small><b>Entrer dans les ruines →</b></a><div class="mode-strip">${MODES.map(m=>modeCard(m,true)).join('')}</div></section>`;cleanup=portrait(view.querySelector('.hub-companion'),profile.selected);}
function activities(filter='all'){const visible=filter==='mini'?MODES.filter(m=>!['campaign','survival'].includes(m.id)):MODES;view.innerHTML=`<section class="page-inner">${heading('LES PORTES DU MONDE','Choisissez votre histoire.','Un premier niveau complet par activité.<br>Des récompenses communes, des chemins différents.')}<div class="filter-tabs"><a href="#activities" class="${filter==='all'?'active':''}">Toutes les activités · 10</a><a href="#activities/mini" class="${filter==='mini'?'active':''}">Mini-jeux & expéditions · 8</a></div><div class="mode-grid">${visible.map(m=>modeCard(m)).join('')}</div></section>`;}
function heroes(id=profile.selected,tab='info',node='edge'){cleanup=renderHeroSheet(view,profile,id,tab,node,portrait);}
function summonPage(){const ritual=RITUALS.find(r=>r.id===ritualTier);view.innerHTML=`<section class="summon-scene"><div class="summon-copy"><p class="eyebrow">LE SANCTUAIRE DES SERMENTS</p><h1>Une âme répond<br>à votre appel.</h1><p>Invoquez l’écho d’un Mythique.<br>Renforcez les liens qui unissent vos quatre héros.</p><div class="summon-rates">${HEROES.map(h=>`<span style="--accent:${h.accent}">${h.symbol} ${h.name}<b>25 %</b></span>`).join('')}</div><p class="muted">Les quatre héros sont disponibles dès le départ.<br>Les probabilités restent identiques pour les trois rituels.</p><div class="ritual-options" role="group" aria-label="Niveau du rituel">${RITUALS.map(r=>`<button data-ritual="${r.id}" aria-pressed="${r.id===ritualTier}"><b>${r.id} · ${r.name}</b><span>${r.cost} ✦ · ${r.fragments} fragments</span></button>`).join('')}</div><p class="ritual-description">${ritual.description}</p><button id="invoke" class="gold-button" ${profile.sigils<ritual.cost?'disabled':''}>Invoquer un Mythique <span>${ritual.cost} ✦</span></button><button data-buy-sigil>Obtenir un sceau · 150 or</button><small>Monnaies gagnées en jeu · aucun achat réel</small></div><div class="summon-altar"><div class="orbit o1"></div><div class="orbit o2"></div><div class="altar-gem">✧</div><span class="altar-floor"></span><p>LE VOILE ÉCOUTE</p></div><div class="summon-history"><p class="eyebrow">DERNIERS ÉCHOS</p><div>${profile.history.length?profile.history.slice(0,8).map(id=>`<img src="${art(id)}" alt="${heroName(id)}" title="${heroName(id)}">`).join(''):'Votre premier appel attend.'}</div></div></section>`;}
function invoke(){const ritual=RITUALS.find(r=>r.id===ritualTier),roll=crypto.getRandomValues(new Uint32Array(1))[0]/4294967296;const id=mutate(p=>P.summon(p,roll,ritual.id));if(!id){toast('Sceaux insuffisants pour ce rituel.');return;}const h=HEROES.find(h=>h.id===id);summonPage();modal('<div id="ritual-host"></div>');modalCleanup=mountRitual($('ritual-host'),h,ritual,portrait,{reduced:reduced.matches||!profile.settings.motion,onSound:()=>sound('summon')});}

function relics(){view.innerHTML=`<section class="page-inner">${heading('LA SALLE DES RELIQUES','Les mémoires du monde.',`${profile.relics.length} reliques retrouvées sur 6.<br>Une relique par héros, un porteur par relique.`)}<div class="relic-grid">${RELICS.map(r=>{const owned=profile.relics.includes(r.id),owner=HEROES.find(h=>profile.heroes[h.id].relic===r.id);return `<article class="relic-card ${owned?'owned':'locked'}">${itemArt(r.index)}<p class="eyebrow">${owned?'RELIQUE RETROUVÉE':'À DÉCOUVRIR'}</p><h2>${r.name}</h2><p class="relic-effect">${r.desc}</p><p class="muted">Première victoire · ${r.source}</p>${owned?`<label>Porteur<select data-equip="${r.id}" aria-label="Porteur de ${r.name}"><option value="">Non équipée</option>${HEROES.map(h=>`<option value="${h.id}" ${owner?.id===h.id?'selected':''}>${h.name}</option>`).join('')}</select></label>`:`<button data-mode="${MODES.find(m=>m.relic===r.id).id}">Trouver cette relique →</button>`}</article>`;}).join('')}</div><p class="page-note">Les bonus de vie et de dégâts s’appliquent à la campagne et aux épreuves de combat. Les jeux de mémoire, d’adresse et de hasard conservent les mêmes règles pour tous.</p></section>`;}
function equipment(id=profile.selected){const h=HEROES.find(h=>h.id===id)??HEROES[0];view.innerHTML=`<section class="page-inner">${heading('L’ARMURERIE DES VEILLEURS','L’héritage se porte.', 'Arme, armure et accessoire · une pièce, un porteur.')}<div class="equipment-heroes">${HEROES.map(x=>`<a href="#equipment/${x.id}" class="${h.id===x.id?'active':''}">${x.name}</a>`).join('')}</div><div class="equipment-summary"><h2>${h.name}</h2><p>${Math.round(KITS[h.id].hp*P.heroBonuses(profile,h.id).health)} PV · +${Math.round((P.heroBonuses(profile,h.id).attack-1)*100)} % dégâts</p></div><div class="equipment-slots">${Object.entries(SLOTS).map(([slot,label])=>{const e=EQUIPMENT.find(e=>e.id===profile.heroes[h.id].gear[slot]);return `<article class="gear-slot">${e?gearArt(e.index):'<span class="empty-slot">◇</span>'}<div><small>${label}</small><strong>${e?.name??'Libre'}</strong><span>${e?gearEffect(e):'Choisissez une pièce ci-dessous.'}</span></div>${e?`<button data-unequip="${slot}" data-owner="${h.id}" aria-label="Retirer ${e.name}">×</button>`:''}</article>`;}).join('')}</div><div class="equipment-grid">${EQUIPMENT.filter(e=>!e.hero||e.hero===h.id).map(e=>{const owned=profile.equipment.includes(e.id),owner=HEROES.find(x=>profile.heroes[x.id].gear[e.slot]===e.id);return `<article class="equipment-card ${owned?'owned':''}">${gearArt(e.index)}<p class="eyebrow">${SLOTS[e.slot]} · ${owned?'DANS LE CARNET':'À RETROUVER'}</p><h2>${e.name}</h2><p class="relic-effect">${gearEffect(e)}</p><p>${e.desc}</p><p class="muted">${owner?'Porteur : '+owner.name:e.source?'Victoire : '+MODES.find(m=>m.id===e.source).name:'Arme du Mythique'}</p>${owned?`<button class="gold-button" data-item="${e.id}" data-owner="${h.id}" ${owner?.id===h.id?'disabled':''}>${owner?.id===h.id?'Équipé':owner?'Transférer à '+h.name:'Équiper'}</button>`:`<button data-buy-item="${e.id}" data-owner="${h.id}" ${profile.gold<e.price?'disabled':''}>Forger · ${e.price} or</button><button data-mode="${e.source}">Gagner en aventure →</button>`}</article>`;}).join('')}</div><p class="page-note">Les bonus se cumulent avec les niveaux et la relique, jusqu’à ×2. Ils sont appliqués au lancement du combat. Les équipements ne modifient pas encore la tenue illustrée du héros.</p></section>`;}
function codex(){view.innerHTML=`<section class="page-inner">${heading('LE GRIMOIRE DU COMBATTANT','Connaître son adversaire.','Le Pont des Serments · sept adversaires · trois rencontres en 2,5D')}<div class="bestiary">${ENCOUNTERS.map((e,i)=>`<article style="--accent:${i===2?'#f29976':'#ce6977'}"><div class="enemy-portrait" style="--enemy:${i}"></div><p class="eyebrow">RENCONTRE 0${i+1} · ${e.role}</p><h2>${e.name}</h2><strong>${fmt(e.hp)} PV par adversaire</strong><p>${e.rule}</p></article>`).join('')}</div><div class="rules-grid"><article><h2>Attaque et compétences</h2><p>J : attaque de base et gain d’énergie à l’impact. 1, 2 et 3 : trois compétences avec recharges propres. Consultez la fiche de chaque Mythique pour ses valeurs actuelles.</p></article><article><h2>Super et compagnons</h2><p>R : super à 100 énergie. Tab change le héros actif ; les trois autres suivent et attaquent automatiquement à proximité.</p></article><article><h2>Déplacement et esquive</h2><p>ZQSD, WASD, flèches ou clic au sol pour avancer en profondeur. Espace : esquive avec 0,4 seconde de protection et 2,4 secondes de recharge. Quittez les cercles d’impact annoncés.</p></article><article><h2>Portes, source et victoire</h2><p>Les portes s’ouvrent après chaque rencontre. La source après la seconde restaure le groupe une fois. Vainquez le Gardien ; si les quatre héros tombent, la traversée est perdue. L’ascension, les talents, l’équipement et les reliques du carnet modifient le combat.</p></article></div><a class="gold-button" href="./ruins.html">Entrer dans le Pont des Serments →</a></section>`;}
function quests(){view.innerHTML=`<section class="page-inner">${heading('VOTRE CHRONIQUE','Les serments du voyageur.','Des objectifs permanents.<br>Aucune échéance, aucun rendez-vous imposé.')}<div class="quest-list">${QUESTS.map(q=>{const n=P.questProgress(profile,q),claimed=profile.claimed.includes(q.id);return `<article class="quest-card"><span class="quest-emblem">${claimed?'✓':'✧'}</span><div><h2>${q.name}</h2><p>${q.desc}</p><div class="progress"><i style="width:${Math.min(100,n/q.target*100)}%"></i></div><small>${Math.min(n,q.target)} / ${q.target}</small></div><div class="quest-reward"><span>${q.gold} ◈ · ${q.sigils} ✦</span><button data-quest="${q.id}" ${claimed||n<q.target?'disabled':''}>${claimed?'Récompense reçue':'Recevoir'}</button></div></article>`;}).join('')}</div><h2 class="journal-title">Votre atlas des aventures</h2><div class="journal-grid">${MODES.map(m=>`<article><b>${m.icon}</b><span><strong>${m.name}</strong><small>${profile.modes[m.id]?.wins??0} victoire(s) · record ${fmt(profile.modes[m.id]?.best??0)}</small></span><button data-mode="${m.id}">Jouer →</button></article>`).join('')}</div></section>`;}
function settings(){view.innerHTML=`<section class="page-inner settings-page">${heading('À VOTRE RYTHME','Le carnet du voyageur.')}<div class="settings-grid"><section><h2>Ambiance & accessibilité</h2><label class="setting"><span>Effets sonores<small>Signaux doux, invocations et récompenses.</small></span><input id="setting-sound" type="checkbox" ${profile.settings.sound?'checked':''}></label><label class="setting"><span>Animations de présentation<small>Héros, particules et apparitions. Les actions de jeu restent lisibles.</small></span><input id="setting-motion" type="checkbox" ${profile.settings.motion?'checked':''}></label><p class="muted">La préférence « réduire les animations » de votre appareil est également respectée. Les activités se mettent en pause lorsque vous quittez l’onglet.</p></section><section><h2>Votre sauvegarde</h2><p>Le carnet est enregistré sur ce navigateur. Exportez-le pour le garder ou le transférer sur un autre appareil.</p><div class="button-row"><button class="gold-button" data-export>Exporter le carnet</button><label class="file-button">Importer un carnet<input id="import-save" type="file" accept="application/json,.json"></label></div><p class="muted">L’import présente le carnet avant de remplacer la progression actuelle.</p></section><section><h2>Cette première édition</h2><p>10 premiers niveaux · 4 Mythiques · 3 gardiens · 9 équipements · 6 reliques · 3 rituels d’invocation · sauvegarde locale.</p><p class="muted">Version solo jouable. Animations détaillées, équilibrage, musiques et extension de campagne restent en production. Les services en ligne des maquettes ne sont pas inclus.</p><a href="./heroes.html" target="_blank" rel="noopener">Atelier des références ↗</a></section></div></section>`;}
function introduction(id){const mode=MODES.find(m=>m.id===id);if(!mode)return;activeGame?.pause(true);const first=!profile.modes[id]?.wins;modal(`<div class="level-brief" style="--accent:${mode.color}"><span class="brief-icon">${mode.icon}</span><p class="eyebrow">${mode.kind} · NIVEAU 01 · ${mode.duration}</p><h2>${mode.place}</h2><p>${mode.desc}</p><div class="rules"><h3>Votre objectif</h3><p>${mode.rules}</p></div><p class="level-loot">${first?'Première victoire':'Nouvelle victoire'} · ${first?mode.gold:Math.round(mode.gold*.35)} ◈ ${first?'· 1 ✦':''}${first&&mode.relic?` · ${RELICS.find(r=>r.id===mode.relic).name}`:''}</p><button class="gold-button" data-start="${id}">Entrer dans ${mode.name.toLowerCase()} →</button><small>Aucun coût d’entrée. Une défaite ne retire aucune ressource.</small></div>`);}
function startMode(id){closeModal();if(id==='campaign'){location.assign('./ruins.html');return;}if(location.hash!==`#play/${id}`)location.hash=`play/${id}`;else renderRoute();}
function play(id){const mode=MODES.find(m=>m.id===id);if(!mode){location.hash='hub';return;}if(id==='campaign'){location.replace('./ruins.html');return;}const runId=crypto.randomUUID();mutate(p=>P.beginRun(p,id,runId));view.innerHTML=`<section class="play-page"><div class="play-heading"><a href="#activities">← Les portes du monde</a><h1>${mode.name}</h1><button data-instructions="${id}">Règles & commandes</button></div><div id="game-host" class="game-host"></div><p class="play-hint">${mode.rules}</p></section>`;
 let finished=false;function end(won,score){if(finished)return;finished=true;activeGame?.destroy();activeGame=null;const reward=mutate(p=>P.finishRun(p,runId,won,score));if(!reward){toast('Cette session a été remplacée dans un autre onglet.');location.hash='hub';return;}result(mode,reward,score);}
 activeGame=mountActivity($('game-host'),mode,profile,end,sound);cleanup=()=>{activeGame?.destroy();activeGame=null;};
}
function result(mode,reward,score){cleanup();cleanup=()=>{};view.innerHTML=`<section class="result-page ${reward.won?'won':''}"><div class="result-emblem">${reward.won?'✥':'☽'}</div><p class="eyebrow">${mode.name} · NIVEAU 01</p><h1>${reward.won?'Un nouvel écho.':'Le voyage continue.'}</h1><p>${reward.won?'Votre victoire rejoint les mémoires de la citadelle.':'Les ombres ont remporté cette épreuve. Vos ressources restent intactes.'}</p>${reward.won?`<div class="reward-row"><span><b>${reward.gold}</b>OR ◈</span><span><b>${reward.sigils}</b>SCEAU ✦</span><span><b>${reward.xp}</b>EXPÉRIENCE</span></div>${reward.relic?`<div class="new-relic">${itemArt(RELICS.find(r=>r.id===reward.relic).index)}<p>RELIQUE RETROUVÉE<strong>${RELICS.find(r=>r.id===reward.relic).name}</strong><a href="#relics">Choisir son porteur →</a></p></div>`:''}`:'<p class="muted">Relisez les commandes et essayez une autre approche.</p>'}${reward.heroXP?`<div class="hero-xp-rewards">${Object.entries(reward.heroXP).map(([id,x])=>`<a href="#heroes/${id}"><strong>${heroName(id)}</strong>+${x.amount} XP${x.levels?`<small>Niveau ${x.level} atteint · talents disponibles</small>`:''}</a>`).join('')}</div><p class="muted">+${reward.essence} essence(s) d’ascension</p>`:''}${reward.equipment?.length?`<div class="equipment-rewards">${reward.equipment.map(id=>{const e=EQUIPMENT.find(x=>x.id===id);return `<a href="#equipment">${gearArt(e.index)}<strong>${e.name}</strong><span>Équipement obtenu →</span></a>`;}).join('')}</div>`:''}<div class="button-row"><a class="gold-button" href="#hub">Retour à la citadelle</a><button data-start="${mode.id}">Rejouer le niveau</button></div></section>`;sound(reward.won?'win':'fail');}
function renderRoute(){generation++;cleanup();cleanup=()=>{};closeModal();const [name='hub',id,tab,node]=location.hash.slice(1).split('/');route=name||'hub';document.querySelectorAll('[data-nav]').forEach(a=>{const on=a.dataset.nav===route||route==='play'&&a.dataset.nav==='activities';a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 if(route==='hub')hub();else if(route==='activities')activities(id);else if(route==='heroes')heroes(id,tab,node);else if(route==='summon')summonPage();else if(route==='relics')relics();else if(route==='equipment')equipment(id);else if(route==='codex')codex();else if(route==='quests')quests();else if(route==='settings')settings();else if(route==='play')play(id);else {location.hash='hub';return;}
 if(route==='hub')view.querySelector('.ruins-entry')?.insertAdjacentHTML('afterend','<a class="tactics-entry" href="./tactics.html"><span>EN COURS · CAMPAGNE TACTIQUE</span><strong>Les Ruines de l’Aube</strong><small>Quatre Mythiques · trois couloirs · embranchements sans retour</small><b>Essayer l’expédition →</b></a>');
 window.scrollTo(0,0);updateBar();transitionView(view,route,reduced.matches||!profile.settings.motion);view.focus({preventScroll:true});}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-route]');if(!b)return;if(b.dataset.route){location.hash=b.dataset.route;return;}if(b.dataset.mode){introduction(b.dataset.mode);return;}if(b.dataset.start){startMode(b.dataset.start);return;}if(b.dataset.closeModal!==undefined){closeModal();return;}if(b.dataset.instructions){const m=MODES.find(m=>m.id===b.dataset.instructions);activeGame?.pause(true);modal(`<div class="level-brief"><p class="eyebrow">${m.name}</p><h2>Règles & commandes</h2><p>${m.rules}</p><button class="gold-button" data-close-modal>J’ai compris</button></div>`);return;}
 if(b.dataset.learn){if(mutate(p=>P.learnTalent(p,b.dataset.owner,b.dataset.learn))){sound('win');renderRoute();toast('Talent appris. Ses bonus seront actifs au prochain combat.');}return;}if(b.dataset.resetTalents){mutate(p=>P.resetTalents(p,b.dataset.resetTalents));renderRoute();toast('Tous les points de talent ont été rendus.');return;}if(b.dataset.ascend){if(mutate(p=>P.ascendHero(p,b.dataset.ascend))){sound('summon');renderRoute();view.querySelector('.ascension-stars')?.animate([{transform:'scale(.8)',filter:'brightness(2)'},{transform:'scale(1)',filter:'brightness(1)'}],{duration:700});toast('Ascension accomplie. Le nouveau palier est ouvert.');}return;}if(b.dataset.enhance){if(mutate(p=>P.enhanceItem(p,b.dataset.enhance))){sound();renderRoute();toast('Équipement amélioré.');}return;}if(b.dataset.ritual){ritualTier=Number(b.dataset.ritual);summonPage();return;}if(b.dataset.item){const item=EQUIPMENT.find(x=>x.id===b.dataset.item);if(mutate(p=>P.equipItem(p,b.dataset.owner,item.slot,item.id))){equipment(b.dataset.owner);sound();toast('Équipement mis à jour.');}return;}if(b.dataset.unequip){mutate(p=>P.equipItem(p,b.dataset.owner,b.dataset.unequip,null));equipment(b.dataset.owner);return;}if(b.dataset.buyItem){toast(mutate(p=>P.buyItem(p,b.dataset.buyItem))?'Objet forgé et ajouté à l’armurerie.':'Or insuffisant ou objet déjà possédé.');equipment(b.dataset.owner);return;}if(b.id==='invoke'){invoke();return;}if(b.dataset.buySigil!==undefined){toast(mutate(P.buySigil)?'Un sceau rejoint votre réserve.':'Il vous faut 150 pièces d’or.');summonPage();return;}
 if(b.dataset.select){mutate(p=>{p.selected=b.dataset.select;});toast(`${heroName(b.dataset.select)} mènera vos aventures.`);renderRoute();return;}
 if(b.dataset.upgrade){const ok=mutate(p=>P.upgradeHero(p,b.dataset.upgrade));toast(ok?'Le lien se renforce. Niveau supérieur.':'Il vous faut 20 fragments et l’or indiqué.');if(ok){sound('win');renderRoute();}return;}
 if(b.dataset.quest){if(mutate(p=>P.claimQuest(p,b.dataset.quest))){sound('win');quests();toast('Récompense reçue.');}return;}
 if(b.dataset.export!==undefined){const blob=new Blob([JSON.stringify(profile,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='shadow-echoes-carnet.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
});
document.addEventListener('change',async e=>{const t=e.target;if(t.dataset.sheetEquip){mutate(p=>P.equipItem(p,t.dataset.owner,t.dataset.sheetEquip,t.value||null));sound();renderRoute();toast('Équipement mis à jour.');return;}if(t.dataset.equip){mutate(p=>{if(t.value)P.equipRelic(p,t.value,t.dataset.equip);else for(const h of Object.values(p.heroes))if(h.relic===t.dataset.equip)h.relic=null;});sound();relics();toast('Les liens de la relique ont été mis à jour.');}
 if(t.id==='setting-sound'||t.id==='setting-motion'){mutate(p=>{p.settings[t.id==='setting-sound'?'sound':'motion']=t.checked;});sound();}
 if(t.id==='import-save'){const file=t.files?.[0];if(!file)return;if(file.size>100000){toast('Ce carnet est trop volumineux.');return;}const parsed=P.parseProfile(await file.text());if(!parsed){toast('Carnet invalide ou version non prise en charge. Progression conservée.');return;}modal(`<div class="level-brief"><p class="eyebrow">IMPORTER UN CARNET</p><h2>Retrouver ce voyage ?</h2><p>${Object.values(parsed.modes).filter(m=>m.wins>0).length} niveaux terminés · ${parsed.gold} or · ${parsed.relics.length} reliques.</p><p>Cette opération remplacera le carnet actuel dans ce navigateur. Exportez-le d’abord si vous souhaitez le conserver.</p><button id="confirm-import" class="gold-button">Remplacer par ce carnet</button></div>`);$('confirm-import').onclick=()=>{profile=parsed;profile.active=null;persist();closeModal();toast('Votre carnet a été restauré.');renderRoute();};t.value='';}
});
$('sound-toggle').onclick=()=>{mutate(p=>{p.settings.sound=!p.settings.sound;});sound();};
window.addEventListener('hashchange',renderRoute);reduced.addEventListener('change',updateBar);
window.addEventListener('storage',e=>{if(e.key!==P.PROFILE_KEY)return;const fresh=P.parseProfile(e.newValue);if(!fresh)return;const changedRun=profile.active&&fresh.active?.id!==profile.active.id;profile=fresh;updateBar();if(changedRun&&route==='play'){location.hash='hub';toast('La session a changé dans un autre onglet. Le carnet a été synchronisé.');}else if(route!=='play')renderRoute();});
if(initial.recovered){try{storage.setItem(`${P.PROFILE_KEY}:recovery`,storage.getItem(P.PROFILE_KEY));}catch{}toast('Un carnet illisible a été conservé à part. Une nouvelle aventure commence.');}
if(initial.unavailable)toast('Stockage indisponible : utilisez l’export pour conserver votre aventure.');
persist();renderRoute();
