import {HEROES} from './heroes.mjs';
import {HERO_TARGETS,TARGET_ROOT} from './target-references.mjs';
import {MOTIONS} from './hero-motion-3d.mjs';
import {HeroActor3D} from './hero-actor-3d.mjs';
const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion:reduce)');let actor,heroId='seraphine',clip='idle',elapsed=0,paused=reduced.matches,group='Tous',last=performance.now(),stopped=false;
function buttons(){const entries=Object.entries(MOTIONS).filter(([,m])=>group==='Tous'||m.group===group);$('motions').innerHTML=entries.map(([id,m])=>`<button data-motion="${id}" aria-pressed="${id===clip}">${m.label}<span>${m.loop?'↻':m.duration+' s'}</span></button>`).join('');$('categories').innerHTML=['Tous',...new Set(Object.values(MOTIONS).map(m=>m.group))].map(g=>`<button data-group="${g}" aria-pressed="${group===g}">${g==='Tous'?'Tous · '+Object.keys(MOTIONS).length:g}</button>`).join('');$('current-motion').textContent=MOTIONS[clip].label;}
function select(id){heroId=id;actor?.destroy();actor=new HeroActor3D($('actor'),id,{interactive:true});const h=HEROES.find(h=>h.id===id);document.documentElement.style.setProperty('--accent',h.accent);$('hero-name').textContent=h.name;$('hero-title').textContent=h.title;$('hero-role').textContent='MYTHIQUE · '+h.role;$('reference').querySelector('img').src=TARGET_ROOT+HERO_TARGETS[id];$('reference').querySelector('figcaption').innerHTML=`Cible du 25 septembre · <a href="./targets.html?board=${id==='seraphine'?'seraphine-final':id}">Agrandir la planche ↗</a>`;$('roster').innerHTML=HEROES.map(x=>`<button data-hero="${x.id}" aria-pressed="${x.id===id}"><img src="../../03_assets/characters/${x.id}/presentation-v1.png" alt=""><span><strong>${x.name}</strong><small>${x.role}</small></span></button>`).join('');elapsed=0;actor.draw(clip,0);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.hero)select(b.dataset.hero);if(b.dataset.motion){clip=b.dataset.motion;elapsed=0;paused=false;buttons();}if(b.dataset.group){group=b.dataset.group;buttons();}if(b.id==='pause')paused=!paused;if(b.id==='replay'){elapsed=0;paused=false;}if(b.id==='front')actor.turn=0;if(b.id==='reference-toggle'){$('reference').hidden=!$('reference').hidden;b.setAttribute('aria-expanded',String(!$('reference').hidden));}$('pause').textContent=paused?'Reprendre':'Pause';$('pause').setAttribute('aria-pressed',String(paused));});
function frame(now){if(stopped)return;const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(!document.hidden){if(!paused)elapsed+=dt*Number($('speed').value);const def=MOTIONS[clip],time=def.loop?elapsed:Math.min(elapsed,def.duration);actor.draw(clip,time);}requestAnimationFrame(frame);}
try{select(new URLSearchParams(location.search).get('hero')&&HEROES.some(h=>h.id===new URLSearchParams(location.search).get('hero'))?new URLSearchParams(location.search).get('hero'):'seraphine');buttons();requestAnimationFrame(frame);}catch(e){$('actor').textContent='Le rendu 3D n’a pas pu démarrer : '+e.message;}
window.addEventListener('pagehide',e=>{if(!e.persisted){stopped=true;actor?.destroy();}});
