import * as T from './vendor/three.module.js';
import {mergeGeometries} from './vendor/BufferGeometryUtils.js';
import {createHeroModel} from './hero-model-3d.mjs';
import {sampleHeroPose,MOTIONS} from './hero-motion-3d.mjs';
import {WALK_AREAS,OBSTACLES,TORCH_SPOTS,KITS} from './ruins-rules.mjs';
const V=(x,y,z)=>new T.Vector3(x,y,z);
export function createRuinsScene(host,state,{reduced=false}={}){
 const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.4));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Les ruines du Pont des Serments, scène jouable en trois dimensions');renderer.domElement.tabIndex=0;
 const scene=new T.Scene();scene.background=new T.Color('#141b2b');scene.fog=new T.FogExp2('#141b2b',.019);const camera=new T.OrthographicCamera(-12,12,9,-9,.1,150),look=V(0,0,9),ray=new T.Raycaster(),floor=new T.Plane(V(0,1,0),0);
 const ambient=new T.HemisphereLight('#b5d7ea','#343047',2);scene.add(ambient);const sun=new T.DirectionalLight('#b7d4ee',2.6);sun.position.set(-12,25,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-18,right:18,top:20,bottom:-20,near:.1,far:70});sun.shadow.bias=-.001;scene.add(sun,sun.target);
 const material=(color,opts={})=>new T.MeshStandardMaterial({color,roughness:.85,...opts});
 const stone=material('#77818a'),edge=material('#465360'),dark=material('#26323e'),gold=material('#a88956',{metalness:.65,roughness:.4}),moss=material('#334e48'),glow=material('#e8ac65',{emissive:'#ffb45f',emissiveIntensity:3}),cyan=material('#76d1d2',{emissive:'#469596',emissiveIntensity:1.3});
 // Original code-generated mineral texture, no illustration projected onto the scene.
 const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=256;const tc=textureCanvas.getContext('2d');let seed=1739;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};tc.fillStyle='#c8cbd0';tc.fillRect(0,0,256,256);for(let i=0;i<14000;i++){const v=145+Math.floor(rnd()*95);tc.fillStyle=`rgba(${v},${v+3},${v+5},${.1+rnd()*.25})`;tc.fillRect(rnd()*256,rnd()*256,1+rnd()*4,1+rnd()*3);}tc.strokeStyle='#747e86';tc.lineWidth=1;for(let i=0;i<8;i++){let x=rnd()*256,y=rnd()*256;tc.beginPath();tc.moveTo(x,y);for(let n=0;n<6;n++){x+=rnd()*28-10;y+=rnd()*24-7;tc.lineTo(x,y);}tc.stroke();}tc.strokeStyle='#e3e2dd';tc.strokeRect(3,3,250,250);tc.strokeStyle='#778087';tc.strokeRect(0,0,256,256);const stoneTexture=new T.CanvasTexture(textureCanvas);stoneTexture.colorSpace=T.SRGBColorSpace;stoneTexture.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());stone.map=stoneTexture;edge.map=stoneTexture;
 const boxGeo=new T.BoxGeometry(1,1,1),sphereGeo=new T.IcosahedronGeometry(1,1),pillarGeo=new T.CylinderGeometry(.34,.45,1,8),ringGeo=new T.TorusGeometry(1,.025,5,48);
 function mesh(g,m,pos=[0,0,0],scale=[1,1,1],parent=scene){const o=new T.Mesh(g,m);o.position.set(...pos);o.scale.set(...scale);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 const box=(pos,scale,mat=stone,parent=scene)=>mesh(boxGeo,mat,pos,scale,parent);
 function ring(x,y,z,r,mat=gold,parent=scene){const o=mesh(ringGeo,mat,[x,y,z],[r,r,r],parent);o.rotation.x=-Math.PI/2;return o;}
 const occluders=[];
 function column(x,z,height=4){const group=new T.Group();scene.add(group);const cm={stone:stone.clone(),edge:edge.clone(),gold:gold.clone()};box([x,.25,z],[1.25,.5,1.25],cm.edge,group);mesh(pillarGeo,cm.stone,[x,height/2,z],[1,height,1],group);box([x,height-.12,z],[.95,.28,.95],cm.gold,group);box([x,height+.12,z],[1.2,.25,1.2],cm.edge,group);for(const a of [-1,1])box([x+a*.31,height/2,z+.29],[.065,height-.4,.08],cm.gold,group);group.userData.fadeMaterials=Object.values(cm);occluders.push(group);}
 function arch(x,z,width=5,height=4.5){column(x-width/2,z,height*.72);column(x+width/2,z,height*.72);for(let i=0;i<13;i++){const a=(i/12)*Math.PI,px=x+Math.cos(a)*width/2,py=height*.72+Math.sin(a)*height*.42;const o=box([px,py,z],[width/10,.5,.6],i%3?stone:gold);o.rotation.z=a-Math.PI/2;}mesh(new T.OctahedronGeometry(.22),cyan,[x,height*1.2,z]);}
 // Large stone islands with actual thickness over a moving sea of mist.
 for(const [a,b,c,d]of WALK_AREAS){box([(a+b)/2,-.65,(c+d)/2],[b-a,1.3,d-c],edge);box([(a+b)/2,-1.35,(c+d)/2],[b-a-.45,.35,d-c-.3],dark);}
 const tiles=new Map();for(const [a,b,c,d]of WALK_AREAS)for(let x=Math.ceil(a);x<b;x++)for(let z=Math.ceil(c);z<d;z++)tiles.set(`${x},${z}`,[x+.5,z+.5]);
 const inst=new T.InstancedMesh(boxGeo,stone,tiles.size),dummy=new T.Object3D();let n=0;
 for(const [x,z]of tiles.values()){const noise=(Math.sin(x*43+z*17)*437.2)%1;dummy.position.set(x,-.04+noise*.016,z);dummy.scale.set(.97,.16,.97);dummy.rotation.y=noise*.012;dummy.updateMatrix();inst.setMatrixAt(n,dummy.matrix);inst.setColorAt(n++,new T.Color().setHSL(.57,.09,.26+Math.abs(noise)*.13));}inst.receiveShadow=true;scene.add(inst);
 for(const o of OBSTACLES){column(o.x,o.z,o.z<-15?4.7:3.4);box([o.x,.12,o.z],[o.w,.2,o.d],moss);}
 // Broken parapets frame the walkway without hiding its hazards.
 for(const side of [-1,1])for(let z=-2;z<7;z+=1.5){box([side*2.43,.38,z],[.25,.7,1.28],edge);if(Math.round(z*2)%3!==0){box([side*2.43,.86,z],[.4,.2,1.32],gold);}}
 for(const side of [-1,1])for(let z=-26;z<=-18;z+=3.7)column(side*7.4,z,2.6+(Math.sin(z)*.5));
 arch(0,6.1,5,4);arch(0,-12.5,5.4,4.7);arch(0,-26.3,5.8,6.3);
 for(const x of [-6,6]){arch(x,-11,2.7,3.1);box([x,1.4,-11],[2.4,2.6,.4],dark);}
 // Rose window and radial tracery form a focal point behind the guardian.
 const rose=new T.Group();rose.position.set(0,4.6,-26.6);scene.add(rose);mesh(new T.CircleGeometry(1.65,48),material('#525b74',{emissive:'#51466b',emissiveIntensity:.6,side:T.DoubleSide}),[0,0,0],[1,1,1],rose);mesh(new T.TorusGeometry(1.68,.1,8,48),gold,[0,0,.1],[1,1,1],rose);for(let i=0;i<10;i++){const a=i/10*Math.PI*2,o=box([Math.sin(a)*.81,Math.cos(a)*.81,.16],[.055,1.62,.055],gold,rose);o.rotation.z=-a;const petal=mesh(new T.TorusGeometry(.39,.026,5,24),cyan,[Math.sin(a)*.95,Math.cos(a)*.95,.12],[.75,1.35,1],rose);petal.rotation.z=-a;}
 // Geometric reliefs and concentric ritual marks in the final arena.
 for(const r of [3.5,4.1,5.7])ring(0,.075,-22,r,r===4.1?cyan:gold);
 for(let i=0;i<12;i++){const a=i/12*Math.PI*2,o=box([Math.sin(a)*4.8,.09,-22+Math.cos(a)*4.8],[.11,.06,.48],gold);o.rotation.y=a;}
 const gates=[6,-12.4].map(z=>{const g=new T.Group();scene.add(g);g.position.z=z;for(let x=-2.3;x<=2.3;x+=.5){box([x,1.4,0],[.055,2.8,.08],gold,g);mesh(new T.ConeGeometry(.12,.35,4),gold,[x,2.95,0],[1,1,1],g);}for(const y of [.6,2.1])box([0,y,0],[4.9,.08,.08],gold,g);return g;});
 const torches=[];for(const [x,z]of TORCH_SPOTS){box([x,.55,z],[.32,1.1,.32],dark);mesh(new T.CylinderGeometry(.32,.15,.22,8),gold,[x,1.16,z]);const flame=mesh(new T.OctahedronGeometry(.17),glow,[x,1.52,z],[1,1.9,1]);torches.push(flame);const halo=mesh(new T.SphereGeometry(.3,8,6),new T.MeshBasicMaterial({color:'#ffa84d',transparent:true,opacity:.06,depthWrite:false}),[x,1.5,z],[2,2,2]);halo.castShadow=false;}
 const spring=new T.Group();scene.add(spring);spring.position.set(3,0,-10);mesh(new T.CylinderGeometry(.85,1,.22,12),gold,[0,.18,0],[1,1,1],spring);const crystal=mesh(new T.OctahedronGeometry(.34),cyan,[0,1,0],[1,1.8,1],spring);ring(0,.3,0,.65,cyan,spring);
 const warmLights=[0,1,2].map(()=>{const light=new T.PointLight('#ffad67',8,7,2);scene.add(light);return light;});
 // Small fragments and pale grasses keep the edges irregular; none block the route.
 const fragments=new T.InstancedMesh(boxGeo,edge,140);for(let i=0;i<140;i++){const area=WALK_AREAS[i%WALK_AREAS.length],[a,b,c,d]=area,x=i%2?a+.15+rnd()*.4:b-.15-rnd()*.4,z=c+rnd()*(d-c);dummy.position.set(x,.12,z);dummy.scale.set(.12+rnd()*.3,.08+rnd()*.18,.15+rnd()*.35);dummy.rotation.set(rnd()*.3,rnd()*6,rnd()*.3);dummy.updateMatrix();fragments.setMatrixAt(i,dummy.matrix);}fragments.receiveShadow=true;scene.add(fragments);
 const grassMat=material('#71877b',{side:T.DoubleSide}),grass=new T.InstancedMesh(new T.ConeGeometry(.045,.35,3),grassMat,180);for(let i=0;i<180;i++){const [a,b,c,d]=WALK_AREAS[i%WALK_AREAS.length],x=i%2?a+.1+rnd()*.35:b-.1-rnd()*.35;dummy.position.set(x,.16,c+rnd()*(d-c));dummy.scale.set(1,.5+rnd(),1);dummy.rotation.set(rnd()*.3,0,rnd()*.5-.25);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix);}scene.add(grass);
 // Distant cliffs and a skyline of fractured spires, batched to keep draw calls bounded.
 const rocks=new T.InstancedMesh(sphereGeo,dark,120);for(let i=0;i<120;i++){const side=i%2?1:-1,z=17-(i%40)*1.3,x=side*(10+((i*7)%9));dummy.position.set(x,-2+(i%7)*.25,z);dummy.scale.set(1.7+(i%3),2.2+(i%9),1.6);dummy.rotation.set(i*.3,i*.7,.2);dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);}scene.add(rocks);
 for(let i=0;i<8;i++){const x=-15+i*4.4,z=-34-(i%3)*3,h=5+i%4*2;box([x,h/2-3,z],[1.3,h,1.4],dark);mesh(new T.ConeGeometry(1.1,3,4),edge,[x,h-1.5,z]);}
 const waterGeo=new T.PlaneGeometry(90,110,30,35);waterGeo.rotateX(-Math.PI/2);const water=mesh(waterGeo,material('#213b48',{metalness:.35,roughness:.3,transparent:true,opacity:.75}),[0,-2.3,-9]);water.castShadow=false;
 const moon=mesh(new T.SphereGeometry(2.5,24,16),new T.MeshBasicMaterial({color:'#a9d7d8'}),[-13,15,-38]);moon.castShadow=false;
 const starPositions=[];for(let i=0;i<150;i++)starPositions.push(Math.sin(i*24)*40,5+(i%17),-20-Math.abs(Math.cos(i*12))*40);const stars=new T.BufferGeometry();stars.setAttribute('position',new T.Float32BufferAttribute(starPositions,3));scene.add(new T.Points(stars,new T.PointsMaterial({color:'#d3e4ed',size:.05,transparent:true,opacity:.65})));
 // Merge static siblings per material, while preserving animated objects and column fading.
 const skipBatch=new Set([...torches,water,crystal]),parents=[];scene.traverse(o=>{if(o.children.length)parents.push(o);});
 for(const parent of parents){const groups=new Map();for(const child of [...parent.children])if(child.isMesh&&!child.isInstancedMesh&&!skipBatch.has(child)&&!child.children.length){const group=groups.get(child.material)??[];group.push(child);groups.set(child.material,group);}for(const [mat,items]of groups){if(items.length<2)continue;const geos=items.map(o=>{o.updateMatrix();const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();return g.applyMatrix4(o.matrix);});const merged=mergeGeometries(geos,false);geos.forEach(g=>g.dispose());if(!merged)continue;items.forEach(o=>parent.remove(o));mesh(merged,mat,[0,0,0],[1,1,1],parent);}}
 const heroModels=state.party.map(h=>{const m=createHeroModel(h.id),pivot=new T.Group();pivot.add(m.root);scene.add(pivot);const marker=ring(0,.11,0,.58,new T.MeshBasicMaterial({color:KITS[h.id].color,transparent:true,opacity:.65}));marker.castShadow=false;return {m,pivot,marker};});
 function enemyModel(e){const g=new T.Group();scene.add(g);const armor=material(e.boss?'#382c3c':'#344252',{metalness:.55}),lit=material(e.boss?'#eb796b':'#a18dd1',{emissive:e.boss?'#aa303b':'#7054b5',emissiveIntensity:1.5});const body=mesh(new T.CylinderGeometry(.35,.25,.72,6),armor,[0,1.17,0],[1,1,.7],g);mesh(new T.OctahedronGeometry(.25),armor,[0,1.81,0],[.8,1.25,.75],g);box([0,1.82,.19],[.3,.045,.045],lit,g);mesh(new T.OctahedronGeometry(.11),lit,[0,1.22,.23],[1,1.4,.4],g);const limbs=[];for(const s of [-1,1]){const leg=new T.Group();leg.position.set(s*.19,.84,0);g.add(leg);box([0,-.32,0],[.18,.65,.21],armor,leg);box([0,-.65,.1],[.24,.18,.36],dark,leg);limbs.push(leg);const arm=new T.Group();arm.position.set(s*.4,1.48,0);g.add(arm);mesh(new T.OctahedronGeometry(.23),armor,[0,0,0],[1,1,.85],arm);box([0,-.34,0],[.16,.62,.18],armor,arm);if(s===1){box([0,-.6,.08],[.055,1.3,.07],gold,arm);box([0,-.18,.12],[.26,.73,.08],lit,arm);}limbs.push(arm);}if(e.boss){for(let i=0;i<5;i++)mesh(new T.ConeGeometry(.08,.45+i%2*.15,5),gold,[(i-2)*.11,2.13,0],[1,1,1],g);g.scale.setScalar(1.65);}const bar=new T.Group();scene.add(bar);box([0,0,0],[1.15,.07,.08],dark,bar);const fill=box([0,0,.05],[1.1,.07,.08],lit,bar);const tell=mesh(new T.RingGeometry(.93,1,64),new T.MeshBasicMaterial({color:'#ff646b',side:T.DoubleSide,transparent:true,opacity:.9,depthWrite:false}),[0,.13,0]);tell.rotation.x=-Math.PI/2;tell.castShadow=false;const disc=mesh(new T.CircleGeometry(1,64),new T.MeshBasicMaterial({color:'#c43c58',side:T.DoubleSide,transparent:true,opacity:.16,depthWrite:false}),[0,.12,0]);disc.rotation.x=-Math.PI/2;disc.castShadow=false;return {g,limbs,body,bar,fill,tell,disc};}
 const enemies=state.enemies.map(enemyModel),effects=[];let lastEventId=0,endElapsed=0,day=false,zoom=10,cameraPreset='three-quarter';
 const cameraOffsets={'three-quarter':V(10,17,18),tactical:V(22,11,5)};
 function setDay(value){day=value;scene.background.set(day?'#657b88':'#141b2b');scene.fog.color.copy(scene.background);ambient.intensity=day?2.5:2;sun.color.set(day?'#ffe0b5':'#b7d4ee');sun.intensity=day?3:2.6;moon.visible=!day;}
 function resize(){const w=host.clientWidth,h=host.clientHeight,ratio=w/h;renderer.setSize(w,h,false);const span=ratio<1?zoom*1.2:zoom;camera.left=-span*ratio;camera.right=span*ratio;camera.top=span;camera.bottom=-span;camera.updateProjectionMatrix();}
 const observer=new ResizeObserver(()=>{resize();render(0);});observer.observe(host);resize();
 function point(clientX,clientY){const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((clientX-rect.left)/rect.width*2-1,-(clientY-rect.top)/rect.height*2+1),camera);const p=new T.Vector3();return ray.ray.intersectPlane(floor,p)?{x:p.x,z:p.z}:null;}
 function eventFx(event){if(!['spell','strike','slam','rest','damage','hurt'].includes(event.type))return;
  if(event.type==='strike'){let o;if(event.ranged){o=new T.Line(new T.BufferGeometry().setFromPoints([V(event.x,1,event.z),V(event.tx,.8,event.tz)]),new T.LineBasicMaterial({color:event.color,transparent:true}));}else{o=new T.Mesh(new T.RingGeometry(1.35,1.5,24,1,-Math.PI*.4,Math.PI*.8),new T.MeshBasicMaterial({color:event.color,transparent:true,side:T.DoubleSide,depthWrite:false}));o.rotation.set(-Math.PI/2,0,-Math.atan2(event.tz-event.z,event.tx-event.x));o.position.set(event.x,.9,event.z);}scene.add(o);effects.push({o,at:event.at,life:.26,kind:'line'});return;}
  if(['damage','hurt'].includes(event.type)){if(effects.length>30)return;const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d');ctx.font='bold 36px Georgia';ctx.textAlign='center';ctx.strokeStyle='#10111c';ctx.lineWidth=5;ctx.strokeText(String(event.amount),64,45);ctx.fillStyle=event.type==='hurt'?'#ff9494':event.color;ctx.fillText(String(event.amount),64,45);const texture=new T.CanvasTexture(c),o=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,depthTest:false}));o.position.set(event.x,2.4,event.z);o.scale.set(1.2,.6,1);scene.add(o);effects.push({o,at:event.at,life:.85,kind:'text',texture});return;}
  const o=ring(event.x,.18,event.z,.3,new T.MeshBasicMaterial({color:event.color??(event.type==='rest'?'#a4ffe1':'#ff5c70'),transparent:true,depthWrite:false}));effects.push({o,at:event.at,life:.8,kind:'ring',big:event.big});
 }
 function render(dt=0){
  if(['won','lost'].includes(state.status))endElapsed+=dt;
  const lead=state.party[state.selected],time=state.time+endElapsed;
  look.lerp(V(lead.x*.55,.5,lead.z-2),reduced?1:1-Math.exp(-dt*4));camera.position.copy(look).add(cameraOffsets[cameraPreset]);camera.lookAt(look);sun.target.position.copy(look);sun.position.copy(look).add(V(-12,25,12));
  const nearestTorches=[...torches].sort((a,b)=>a.position.distanceToSquared(V(lead.x,1,lead.z))-b.position.distanceToSquared(V(lead.x,1,lead.z)));warmLights.forEach((l,i)=>{l.position.copy(nearestTorches[i].position);l.intensity=day?3:9;});
  const targetPoint=V(lead.x,1.25,lead.z),direction=targetPoint.clone().sub(camera.position);ray.set(camera.position,direction.clone().normalize());ray.far=direction.length();const obscured=new Set(ray.intersectObjects(occluders,true).map(hit=>hit.object.parent));for(const group of occluders)for(const mat of group.userData.fadeMaterials){const opacity=obscured.has(group)?.2:1;mat.transparent=opacity<1;mat.opacity=opacity;mat.depthWrite=opacity===1;}ray.far=Infinity;
  for(const [i,h]of state.party.entries()){const {m,pivot,marker}=heroModels[i];let clip=h.clip,elapsed=time-h.clipAt;if(h.hp>0&&!h.pending&&elapsed>(MOTIONS[clip]?.duration??1.5)&&!['won','lost'].includes(state.status))clip=h.moving?'run':'idle';if(h.hp<=0)clip='death';const pose=sampleHeroPose(h.id,clip,['idle','run'].includes(clip)?time:elapsed);if(h.moving&&!['run','death','dodgeForward'].includes(clip)){const run=sampleHeroPose(h.id,'run',time);for(const b of ['thighL','thighR','shinL','shinR','footL','footR'])pose.joints[b]=run.joints[b];}m.apply(pose,reduced?0:time);pivot.position.set(h.x,0,h.z);let delta=(h.heading-pivot.rotation.y+Math.PI*3)%(Math.PI*2)-Math.PI;pivot.rotation.y+=delta*(1-Math.exp(-dt*14));marker.position.set(h.x,.11,h.z);marker.scale.setScalar(i===state.selected?.7:.4);marker.material.opacity=h.hp<=0?.1:i===state.selected?.95:.25;}
  for(const [i,e]of state.enemies.entries()){const m=enemies[i];m.g.position.set(e.x,0,e.z);m.g.rotation.y=e.heading;m.g.visible=e.hp>0||time-e.deadAt<1.2;if(e.hp<=0){m.g.rotation.z=Math.min(1.5,(time-e.deadAt)*2);m.g.position.y=-Math.max(0,time-e.deadAt-.4);}
   const pace=e.phase==='idle'?Math.sin(time*5+i)*.2:0;m.limbs[0].rotation.x=pace;m.limbs[2].rotation.x=-pace;m.limbs[1].rotation.x=e.phase==='tell'?-1.3:e.phase==='recover'?.6:pace;m.limbs[3].rotation.x=e.phase==='tell'?-2:e.phase==='recover'?.9:-pace;m.body.rotation.z=e.stun>0?Math.sin(time*20)*.06:0;m.bar.position.set(e.x,e.boss?3.8:2.3,e.z);m.bar.quaternion.copy(camera.quaternion);m.bar.visible=e.hp>0;m.fill.scale.x=Math.max(.001,e.hp/e.maxHp)*1.1;
   const active=e.phase==='tell'&&e.hp>0&&e.wave===state.stage;m.tell.visible=m.disc.visible=active;if(active){m.tell.position.set(e.aim.x,.13,e.aim.z);m.disc.position.set(e.aim.x,.12,e.aim.z);m.tell.scale.setScalar(e.radius);m.disc.scale.setScalar(e.radius);m.disc.material.opacity=.1+(1-e.timer/(e.boss?1.5:1.15))*.3;}}
  gates.forEach((g,i)=>{const target=state.cleared.includes(i)?-3.7:0;g.position.y+=(target-g.position.y)*(1-Math.exp(-dt*3));});
  for(const event of state.events)if(event.seq>lastEventId){eventFx(event);lastEventId=event.seq;}
  for(let i=effects.length-1;i>=0;i--){const f=effects[i],p=(time-f.at)/f.life;if(p>=1){scene.remove(f.o);if(f.kind!=='ring')f.o.geometry?.dispose();f.o.material.dispose();f.texture?.dispose();effects.splice(i,1);continue;}f.o.material.opacity=1-p;if(f.kind==='ring')f.o.scale.setScalar(.3+p*(f.big?6:3));if(f.kind==='text')f.o.position.y=2.4+p*.9;}
  if(!reduced){torches.forEach((f,i)=>{f.scale.y=1.8+Math.sin(time*8+i)*.35;f.rotation.y=time+i;});crystal.position.y=.95+Math.sin(time*2)*.1;crystal.rotation.y=time*.7;const p=waterGeo.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,Math.sin(time*.5+p.getX(i)*.24)*.07+Math.cos(time*.3+p.getZ(i)*.18)*.1);p.needsUpdate=true;}
  spring.visible=!state.rested;rocks.visible=cameraPreset!=='tactical';renderer.render(scene,camera);renderer.domElement.dataset.stage=String(state.stage);renderer.domElement.dataset.status=state.status;renderer.domElement.dataset.position=`${lead.x.toFixed(3)},${lead.z.toFixed(3)}`;renderer.domElement.dataset.cameraPreset=cameraPreset;
 }
 render(1);
 return {renderer,camera,scene,point,render,setDay,setZoom(v){zoom=v;resize();},setCameraPreset(value){cameraPreset=value==='tactical'?'tactical':'three-quarter';render(0);},screenToWorld(x,z){const offset=cameraOffsets[cameraPreset],length=Math.hypot(offset.x,offset.z);return {x:(x*offset.z+z*offset.x)/length,z:(z*offset.z-x*offset.x)/length};},dispose(){observer.disconnect();heroModels.forEach(h=>h.m.dispose());const gs=new Set(),ms=new Set();scene.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])if(m)ms.add(m);});gs.forEach(g=>g.dispose());ms.forEach(m=>{m.map?.dispose();m.dispose();});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();}};
}
