import {HEROES} from './heroes.mjs';
import {loadVolumeActor} from './hero-actor-3d.mjs';
import {ART,RELICS} from './citadel-data.mjs';
import {heroBonuses} from './profile.mjs';
import * as G from './activities.mjs';
const icons=['✥','♜','☽','◇','❋','⚗'];
const atlas=i=>`<span class="item-art" style="--col:${i%3};--row:${Math.floor(i/3)}" aria-hidden="true"></span>`;
export function mountActivity(host,mode,profile,onFinish,playSound=()=>{}){
 const abort=new AbortController(),{signal}=abort;let closed=false,paused=false,reported=false,frameId,unlockTimer,clock=performance.now(),holding=false,keys=new Set(),pointer=null,moving=false,heading=-.25;
 let s,canvas,ctx,images={},heroActor;const hero=HEROES.find(h=>h.id===profile.selected);const reduced=matchMedia('(prefers-reduced-motion:reduce)');const rng=G.seeded(crypto.getRandomValues(new Uint32Array(1))[0]);
 const action=['survival','caravan','race'].includes(mode.id),timed=action||mode.id==='fishing';
 if(action){s=G.createAction(mode.id,heroBonuses(profile,profile.selected),rng);s.heroId=hero.id;s.energy=0;s.auto=true;s.pose='idle';s.poseAt=0;if(mode.id==='caravan'){s.x=365;s.y=370;}}
 else s=({memory:G.createMemory,runes:G.createRunes,dice:G.createDice,alchemy:G.createAlchemy,expedition:G.createExpedition,fishing:G.createFishing}[mode.id])(rng);
 host.innerHTML=`<div class="game-toolbar"><span>${mode.place} <small>• NIVEAU 01</small></span><button data-action="pause">Pause</button></div><div class="activity-board ${mode.id}"></div><div class="activity-message" role="status" aria-live="polite"></div><div class="game-pause" hidden><h2>Le temps vous attend.</h2><p>L’activité est en pause.</p><button class="gold-button" data-action="pause">Reprendre</button></div>`;
 const board=host.querySelector('.activity-board'),message=host.querySelector('.activity-message');
 function speak(text){message.textContent=text;}
 function status(){if(s.status==='playing'||reported)return;reported=true;playSound(s.status==='won'?'win':'fail');unlockTimer=setTimeout(()=>{if(!closed)onFinish(s.status==='won',s.score??(s.total??s.loot??Math.max(0,1000-(s.tries??s.moves??s.errors??0)*20)));},450);}
 function pause(value=!paused){paused=value;keys.clear();pointer=null;holding=false;host.querySelector('.game-pause').hidden=!paused;host.querySelector('[data-action="pause"]').textContent=paused?'Reprendre':'Pause';clock=performance.now();}
 function render(){
  if(mode.id==='memory')board.innerHTML=`<div class="board-heading"><h2>Les vitraux se souviennent.</h2><span>${s.found.length/2} / 6 paires · ${s.tries} / 24 essais</span></div><div class="memory-grid">${s.cards.map((v,i)=>{const open=s.open.includes(i)||s.found.includes(i);return `<button data-card="${i}" class="memory-card ${open?'revealed':''} ${s.found.includes(i)?'matched':''}" aria-label="${open?RELICS[v].name:`Carte ${i+1}`}" ${s.found.includes(i)?'disabled':''}>${open?atlas(v):'<span class="card-sigil">✥</span>'}</button>`;}).join('')}</div>`;
  if(mode.id==='runes')board.innerHTML=`<div class="board-heading"><h2>Rallumez le sceau.</h2><span>${s.board.filter(Boolean).length} / 9 lumières · ${s.moves} / 20 coups</span></div><div class="rune-board">${s.board.map((v,i)=>`<button data-rune="${i}" aria-label="Rune ${i+1}" aria-pressed="${v}" class="rune ${v?'lit':''}">${['ᛉ','ᛟ','ᚷ','ᛞ','✥','ᛝ','ᚹ','ᛗ','ᛏ'][i]}</button>`).join('')}</div><button class="quiet" data-action="hint">Demander un indice</button>`;
  if(mode.id==='dice')board.innerHTML=`<div class="board-heading"><h2>Le destin écoute.</h2><span>Manche ${Math.min(s.round,6)} / 6 · objectif 35</span></div><div class="dice-table"><div class="die" aria-label="Résultat du dé">${s.last?['⚀','⚁','⚂','⚃','⚄','⚅'][s.last-1]:'⚄'}</div><div class="dice-scores"><p>À l’abri<strong>${s.total}</strong></p><p>Sur la table<strong>${s.pot}</strong></p></div><div class="button-row"><button class="gold-button" data-action="roll">Lancer le dé</button><button data-action="bank" ${s.pot?'':'disabled'}>Encaisser ${s.pot} points</button></div><p class="muted">Un 1 efface uniquement les points sur la table. Aucune mise.</p></div>`;
  if(mode.id==='alchemy'){const r=G.RECIPES[Math.min(2,s.recipe)];board.innerHTML=`<div class="board-heading"><h2>${r.name}</h2><span>${s.recipe} / 3 potions · ${s.errors} / 3 erreurs</span></div><div class="alchemy-layout"><div class="potion-glow">${atlas(5)}</div><div><p class="eyebrow">RECETTE DU GRIMOIRE</p><p class="recipe">${r.ingredients.map(i=>G.INGREDIENTS[i].name).join(' → ')}</p><p>Chaleur idéale : <b>${r.heat}°</b> (±5°)</p><div class="ingredients">${G.INGREDIENTS.map((v,i)=>`<button data-ingredient="${i}" style="--accent:${v.color}"><b>${v.icon}</b>${v.name}</button>`).join('')}</div><p class="chosen">${s.chosen.length?s.chosen.map(i=>G.INGREDIENTS[i].name).join(' → '):'Le creuset attend vos ingrédients.'}</p><label class="heat">Chaleur <output id="heat-value">50°</output><input id="brew-heat" type="range" min="0" max="100" value="50"></label><div class="button-row"><button class="gold-button" data-action="brew">Synthétiser</button><button data-action="empty">Vider le creuset</button></div></div></div>`;}
  if(mode.id==='expedition'){const step=G.EXPEDITION_STEPS[Math.min(s.step,4)];board.innerHTML=`<div class="expedition-path">${G.EXPEDITION_STEPS.map((_,i)=>`<span class="${i<=s.step?'visited':''}">${i<s.step?'✓':i+1}</span>`).join('')}</div><div class="expedition-story"><p class="eyebrow">ÉTAPE ${Math.min(s.step+1,5)} / 5</p><h2>${step.title}</h2><p>${step.text}</p><div class="supplies"><span>Intégrité <b>${s.hp}/12</b></span><span>Provisions <b>${s.food}</b></span><span>Trésor <b>${s.loot}</b></span></div><div class="path-choices">${step.choices.map((c,i)=>`<button data-path="${i}"><strong>${c.text}</strong><small>${c.hint}</small><span>→</span></button>`).join('')}</div></div>`;}
  status();
 }
 if(timed){board.innerHTML=`<div class="canvas-wrap"><canvas width="1000" height="560" tabindex="0" aria-label="${mode.name} : espace de jeu"></canvas><div class="enemy-targets"></div><div class="canvas-hud"><span id="game-goal"></span><span id="game-counter"></span></div></div><div class="touch-controls">${action?(mode.id==='race'?'<button data-lane="-1">↑ Allée haute</button><button data-lane="1">↓ Allée basse</button>':`${mode.id==='survival'?'<span class="direction-pad"><button data-dir="left">←</button><button data-dir="up">↑</button><button data-dir="down">↓</button><button data-dir="right">→</button></span>':''}<button data-action="base">1 · Attaque de base</button><button class="gold-button" data-action="pulse">2 · Compétence</button><button data-action="super">3 · Super · 0/100</button>${mode.id==='survival'?'<label><input data-action="auto" type="checkbox" checked> Bases assistées</label>':''}`):'<button class="gold-button" data-action="cast">Lancer la ligne</button><button data-action="reel">Maintenir pour mouliner</button>'}</div>`;
  canvas=board.querySelector('canvas');ctx=canvas.getContext('2d');
  if(action&&mode.id!=='race'){const actorHost=document.createElement('div');actorHost.className='action-hero';board.querySelector('.canvas-wrap').append(actorHost);loadVolumeActor(actorHost,hero.id,{facing:-.25}).then(a=>{if(closed){a.destroy();return;}heroActor=a;}).catch(()=>{});}

  for(const [key,url]of Object.entries({hub:ART.hub,ruins:ART.ruins,atlas:ART.atlas,enemies:'../../03_assets/enemies/guardians-v2.png',hero:`../../03_assets/characters/${profile.selected}/presentation-v1.png`})){
    const image=new Image();image.src=url;image.decode().then(()=>{if(!closed)images[key]=image;}).catch(()=>{if(!closed)speak('Une illustration n’a pas chargé ; les commandes restent disponibles.');});
  }
 }else render();
 function sprite(index,x,y,w,h){if(!images.atlas)return;const cell=images.atlas.naturalWidth/3;ctx.drawImage(images.atlas,(index%3)*cell,Math.floor(index/3)*cell,cell,cell,x-w/2,y-h/2,w,h);}
 function background(image){ctx.fillStyle='#161323';ctx.fillRect(0,0,1000,560);if(image){const scale=Math.max(1000/image.width,560/image.height);ctx.drawImage(image,(1000-image.width*scale)/2,(560-image.height*scale)/2,image.width*scale,image.height*scale);}ctx.fillStyle='#08071365';ctx.fillRect(0,0,1000,560);}
 function draw(){
  background(mode.id==='fishing'?images.hub:images.ruins);
  if(action){
   if(mode.id==='race'){for(let i=0;i<3;i++){ctx.strokeStyle='#e6c98e35';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,215+i*145);ctx.lineTo(1000,215+i*145);ctx.stroke();}sprite(7,185,155+s.lane*145+Math.sin(s.time*12)*4,155,150);}
   if(mode.id==='caravan'){sprite(6,140,365+Math.sin(s.time*3)*2,245,245);sprite(7,295,372,165,165);}
   if(mode.id==='survival'){ctx.fillStyle='#08051180';ctx.beginPath();ctx.ellipse(s.x,s.y+37,35,10,0,0,Math.PI*2);ctx.fill();if(images.hero&&!heroActor)ctx.drawImage(images.hero,s.x-45,s.y-88+Math.sin(s.time*5)*2,90,135);ctx.strokeStyle='#d8bc7877';ctx.beginPath();ctx.ellipse(s.x,s.y+40,39,12,0,0,Math.PI*2);ctx.stroke();}
   for(const e of s.enemies){if(e.touched)continue;if(e.coin){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(s.time);ctx.fillStyle='#f6dc88';ctx.shadowColor='#edbe5d';ctx.shadowBlur=18;ctx.fillRect(-10,-10,20,20);ctx.restore();}else {if(images.enemies){const index=mode.id==='caravan'?0:Math.min(2,Math.floor(s.time/20)),cell=images.enemies.width/3;ctx.drawImage(images.enemies,index*cell,0,cell,images.enemies.height,e.x-65,e.y-65+Math.sin(s.time*3+e.id)*3,130,130);}else sprite(8,e.x,e.y,110,130);if(mode.id==='caravan'){ctx.fillStyle='#160d22';ctx.fillRect(e.x-24,e.y-54,48,4);ctx.fillStyle='#b48adb';ctx.fillRect(e.x-24,e.y-54,48*Math.max(0,e.hp)/50,4);}}}
   for(const f of s.fx){ctx.save();ctx.globalAlpha=Math.min(1,f.life*3);ctx.strokeStyle=hero.accent;ctx.shadowColor=hero.accent;ctx.shadowBlur=15;ctx.lineWidth=f.kind==='bolt'?3:5;ctx.beginPath();if(f.kind==='bolt'){ctx.moveTo(f.x,f.y);ctx.lineTo(f.tx,f.ty);}else {ctx.arc(f.x,f.y,f.kind==='super'?(1-f.life/1.3)*650:f.kind==='pulse'?(1-f.life/.65)*300:f.kind==='heal'?(1-f.life)*80:25,0,Math.PI*2);}ctx.stroke();ctx.restore();}
   host.querySelector('#game-goal').textContent=mode.id==='race'?`Intégrité ${s.hp}/4 · Allée ${s.lane+1} · Éclats ${s.coins}`:mode.id==='caravan'?`Convoi ${Math.ceil(s.hp)}/${Math.round(s.maxHp)}`:`Vie ${Math.ceil(s.hp)}/${Math.round(s.maxHp)} · Vague ${Math.min(3,1+Math.floor(s.time/20))}/3`;
   const danger=s.mode==='race'?s.enemies.filter(e=>!e.coin&&!e.touched&&e.x>180&&e.x<500).sort((a,b)=>a.x-b.x)[0]:null;
   host.querySelector('#game-counter').textContent=`${Math.floor(s.time)} / ${s.duration} s${danger?' · Ombre : allée '+(danger.lane+1):''}`;
   if(s.mode==='caravan'){
    const targets=host.querySelector('.enemy-targets');const alive=new Set(s.enemies.map(e=>String(e.id)));
    for(const b of targets.children)if(!alive.has(b.dataset.enemy))b.remove();
    for(const e of s.enemies){let b=targets.querySelector('[data-enemy="'+e.id+'"]');if(!b){b=document.createElement('button');b.className='enemy-target';b.dataset.enemy=String(e.id);b.setAttribute('aria-label','Repousser le spectre '+e.id);targets.append(b);}b.style.left=(e.x/10)+'%';b.style.top=(e.y/5.6)+'%';b.disabled=e.x>970||e.hp<=0;}
   }
   const pulse=host.querySelector('[data-action="pulse"]');if(pulse){pulse.disabled=s.time<s.pulseAt;pulse.textContent=s.time<s.pulseAt?`2 · ${Math.ceil(s.pulseAt-s.time)} s`:`2 · ${hero.skills[1].name}`;const sup=host.querySelector('[data-action=super]');sup.disabled=(s.energy??0)<100;sup.textContent=`3 · ${hero.skills[2].name} · ${s.energy??0}/100`;host.querySelector('[data-action=base]').disabled=s.time<(s.baseAt??0);}
  }else{
   ctx.fillStyle='#0b2434ba';ctx.fillRect(0,300,1000,260);for(let i=0;i<12;i++){ctx.strokeStyle=`rgba(113,204,213,${.10+i%3*.025})`;ctx.beginPath();for(let x=0;x<=1000;x+=10){const y=320+i*21+Math.sin(x*.02+s.time+i)*5;x?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}
   ctx.strokeStyle='#d9bf88';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(210,120);ctx.quadraticCurveTo(490,80,600,365);ctx.stroke();ctx.fillStyle='#f2ac89';ctx.beginPath();ctx.arc(600,365+Math.sin(s.time*2)*5,7,0,Math.PI*2);ctx.fill();
   ctx.fillStyle='#080b14d9';ctx.fillRect(235,190,530,95);ctx.fillStyle='#322c3e';ctx.fillRect(260,225,480,20);
   if(s.phase==='bite'){ctx.fillStyle='#b99751';ctx.fillRect(260+480*.35,220,480*.30,30);const p=(Math.sin(s.time*2.6)+1)/2;ctx.fillStyle='#fff0bf';ctx.fillRect(260+p*480-3,212,6,46);}
   if(s.phase==='reel'){ctx.fillStyle='#467d66';ctx.fillRect(380,220,240,30);ctx.fillStyle='#fff0bf';ctx.fillRect(260+s.tension/100*480-3,212,6,46);ctx.fillStyle='#76c2bd';ctx.fillRect(260,268,s.progress/100*480,5);}
   ctx.fillStyle='#e6cf9f';ctx.textAlign='center';ctx.font='18px Georgia';ctx.fillText(s.phase==='cast'?'Les eaux attendent votre ligne.':s.phase==='bite'?'Ferrez dans la zone dorée':'Tension · restez dans la zone verte',500,209);
   host.querySelector('#game-goal').textContent=`Prises ${s.catches}/3 · Échecs ${s.misses}/5`;host.querySelector('#game-counter').textContent=s.phase==='reel'?`Tension ${Math.round(s.tension)} % · Capture ${Math.floor(s.progress)} %`:s.phase==='bite'?`Repère ${Math.round((Math.sin(s.time*2.6)+1)*50)} %`:'';
   const button=host.querySelector('[data-action="cast"]');button.textContent=s.phase==='bite'?'Ferrer maintenant':s.phase==='reel'?'Prise au bout de la ligne':'Lancer la ligne';button.disabled=s.phase==='reel';host.querySelector('[data-action="reel"]').disabled=s.phase!=='reel';if(message.textContent!==s.message)speak(s.message);
  }
 }
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(a==='pause'){pause();return;}if(paused||s.status!=='playing')return;
  if(b.dataset.enemy){const target=s.enemies.find(x=>x.id===Number(b.dataset.enemy));if(target)G.actionClick(s,target.x,target.y);return;}
  playSound('click');
  if(b.dataset.card!==undefined){G.flipMemory(s,Number(b.dataset.card));render();if(s.open.length===2&&s.status==='playing')unlockTimer=setTimeout(()=>{if(!closed){G.closeMemory(s);render();}},800);}
  if(b.dataset.rune!==undefined){G.pressRune(s,Number(b.dataset.rune));render();}
  if(a==='hint'){const hint=G.runeHint(s.board);speak(`Essayez la rune ${hint[0]+1}. Chaque choix change aussi ses voisines.`);}
  if(a==='roll'){G.rollDice(s,rng);speak(s.last===1?'Un 1 ! La manche est perdue. Les points encaissés restent à vous.':`${s.last} points. Continuer ou encaisser ?`);render();}
  if(a==='bank'){G.bankDice(s);render();}
  if(b.dataset.ingredient!==undefined){if(s.chosen.length<3)s.chosen.push(Number(b.dataset.ingredient));render();}
  if(a==='empty'){s.chosen=[];render();}
  if(a==='brew'){const ok=G.brew(s,Number(host.querySelector('#brew-heat').value));speak(ok?'Une essence parfaite.':'Le mélange est instable. Relisez la recette et la chaleur.');render();}
  if(b.dataset.path!==undefined){G.choosePath(s,Number(b.dataset.path));render();}
  if(a==='base')G.actionBase(s);if(a==='super')G.actionPower(s,true);if(a==='auto')s.auto=b.checked;if(a==='cast')G.fishingTap(s);if(a==='pulse')G.actionPulse(s);if(b.dataset.lane)G.changeLane(s,Number(b.dataset.lane));status();
 },{signal});
 host.addEventListener('change',e=>{if(e.target.dataset.action==='auto')s.auto=e.target.checked;},{signal});
 host.addEventListener('input',e=>{if(e.target.id==='brew-heat')host.querySelector('#heat-value').textContent=`${e.target.value}°`;},{signal});
 const position=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*1000,y:(e.clientY-r.top)/r.height*560};};
 host.addEventListener('pointerdown',e=>{if(paused)return;const b=e.target.closest('button');if(b?.dataset.action==='reel'){holding=true;e.preventDefault();}if(b?.dataset.dir){keys.add(b.dataset.dir);e.preventDefault();}if(e.target===canvas){canvas.focus();if(action){const p=position(e);if(mode.id==='caravan')G.actionClick(s,p.x,p.y);if(mode.id==='survival')pointer=p;}e.preventDefault();}},{signal});
 host.addEventListener('pointermove',e=>{if(pointer&&e.buttons)pointer=position(e);},{signal});
 const release=()=>{holding=false;pointer=null;keys.clear();};window.addEventListener('pointerup',release,{signal});window.addEventListener('pointercancel',release,{signal});window.addEventListener('blur',()=>pause(true),{signal});
 window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase(),map={arrowleft:'left',q:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',z:'up',w:'up',arrowdown:'down',s:'down'};if(k==='p'){pause();return;}if(paused)return;if(action&&['1','2','3'].includes(k)&&!e.repeat){e.preventDefault();if(k==='1')G.actionBase(s);else G.actionPower(s,k==='3');}if(map[k]||e.code==='Space'){e.preventDefault();if(action){keys.add(map[k]);if(!e.repeat&&mode.id==='race'&&(map[k]==='up'||map[k]==='down'))G.changeLane(s,map[k]==='up'?-1:1);if(e.code==='Space')G.actionPulse(s);}else if(mode.id==='fishing'&&e.code==='Space'){if(s.phase==='reel')holding=true;else if(!e.repeat)G.fishingTap(s);}}},{signal});
 window.addEventListener('keyup',e=>{const k=e.key.toLowerCase(),map={arrowleft:'left',q:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',z:'up',w:'up',arrowdown:'down',s:'down'};keys.delete(map[k]);if(e.code==='Space')holding=false;},{signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);},{signal});
 function frame(now){const dt=Math.min(.05,Math.max(0,(now-clock)/1000));clock=now;if(!paused&&s.status==='playing'){if(action){let x=Number(keys.has('right'))-Number(keys.has('left')),y=Number(keys.has('down'))-Number(keys.has('up'));if(pointer){x=pointer.x-s.x;y=pointer.y-s.y;if(Math.hypot(x,y)<10)x=y=0;}moving=Math.hypot(x,y)>.05;if(moving)heading=Math.atan2(x,y);G.stepAction(s,dt,{x,y});}else if(mode.id==='fishing')G.stepFishing(s,dt,holding);status();}if(timed)draw();if(heroActor){const host=heroActor.canvas.parentElement,age=s.time-s.poseAt,clip=age<({attack:.85,skill:1.25,ultimate:1.65}[s.pose]??0)?s.pose:moving&&mode.id==='survival'?'run':'idle';host.style.left=(s.x/10)+'%';host.style.top=(s.y/5.6)+'%';const actual=profile.settings.motion&&!reduced.matches?clip:'neutral',at=actual==='neutral'?0:['idle','run'].includes(clip)?s.time:age;if(heroActor.lastClip!==actual||heroActor.lastTime!==at)heroActor.draw(actual,at,1,{locomotion:moving?'run':null,locomotionTime:s.time});if(moving){const delta=Math.atan2(Math.sin(heading-heroActor.turn),Math.cos(heading-heroActor.turn));heroActor.turn+=delta*.2;}}if(!closed)frameId=requestAnimationFrame(frame);}
 if(timed)frameId=requestAnimationFrame(frame);
 return {pause,destroy(){closed=true;heroActor?.destroy();abort.abort();cancelAnimationFrame(frameId);clearTimeout(unlockTimer);host.replaceChildren();}};
}
