import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {HERO_TARGETS,TARGET_ROOT} from './target-references.mjs';
import {inspectHeroGlb} from './hero-asset-gate.mjs';
import {tuneHeroMaterials} from './hero-material-tuning.mjs';

const $=id=>document.getElementById(id),heroIds=Object.keys(HERO_TARGETS),params=new URLSearchParams(location.search),initial=params.get('hero'),initialModel=['skin','atelier','surface','silhouette','groom'].includes(params.get('model'))?params.get('model'):'legacy';
const renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;$('stage').append(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.1,100),target=new T.Vector3(0,1.1,0),front=new T.Vector3(0,1.6,5.9),threeQuarter=new T.Vector3(3.3,2.7,5.5);camera.position.copy(threeQuarter);camera.lookAt(target);
scene.add(new T.HemisphereLight('#c9d4e5','#45333e',2));const key=new T.DirectionalLight('#ffe6cf',3);key.position.set(2.7,6,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const rim=new T.DirectionalLight('#b1a5e3',2);rim.position.set(-3,3,-3);scene.add(rim);
const floor=new T.Mesh(new T.CircleGeometry(1.8,64),new T.MeshStandardMaterial({color:'#312a37',roughness:.85,metalness:.1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.03;floor.receiveShadow=true;scene.add(floor);for(const radius of [1.52,1.7]){const ring=new T.Mesh(new T.RingGeometry(radius,radius+.012,64),new T.MeshBasicMaterial({color:'#b79a6e',side:T.DoubleSide,transparent:true,opacity:.75}));ring.rotation.x=-Math.PI/2;ring.position.y=.002;scene.add(ring);}
const loader=new GLTFLoader(),reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;let active=null,token=0,paused=reduced,face=false,combatScale=false,headDetail=false,last=performance.now(),drag=null;
function positionCamera(){target.set(0,headDetail?2.12:1.1,0);camera.position.copy(target).add((face?new T.Vector3(0,.5,5.9):new T.Vector3(3.3,1.6,5.5)).multiplyScalar(headDetail?.35:combatScale?3.3:1));camera.lookAt(target);$('combat-scale').setAttribute('aria-pressed',String(combatScale));$('combat-scale').textContent=combatScale?'Taille atelier':'Taille de combat';$('head-detail').setAttribute('aria-pressed',String(headDetail));$('head-detail').textContent=headDetail?'Vue entière':'Détail visage';}
function resize(){const w=Math.max(1,$('stage').clientWidth),h=Math.max(1,$('stage').clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('stage'));resize();
function metric(name,value){const item=document.createElement('span'),number=document.createElement('b');number.textContent=String(value);item.append(number,document.createTextNode(name));$('metrics').append(item);}
function reportResult(report){$('metrics').replaceChildren();$('issues').replaceChildren();const m=report.metrics??{};for(const [name,value]of [['Peaux',m.skins??0],['Maillages déformables',m.skinnedMeshes??0],['Articulations',m.joints??0],['Clips',m.animations??0],['Sommets skinnés',m.skinnedVertices??0],['Influences multiples',`${Math.round((m.multiInfluenceRatio??0)*100)} %`]])metric(name,value);
 const messages=[...report.errors.map(text=>['error',text]),...report.warnings.map(text=>['warn',text])];if(!messages.length)messages.push(['good','Structure technique conforme. Vérifiez maintenant la fidélité artistique, les déformations et la lisibilité dans le jeu.']);for(const [type,text]of messages){const item=document.createElement('li');item.className=type;item.textContent=text;$('issues').append(item);}
 $('model-status').textContent=report.pass?'Structure conforme · revue artistique requise':'Modèle de travail · contrôle non validé';$('model-status').classList.toggle('pass',report.pass);
}
function disposeActive(){if(!active)return;active.mixer.stopAllAction();scene.remove(active.wrapper);active.model.traverse(object=>{object.geometry?.dispose();for(const material of Array.isArray(object.material)?object.material:object.material?[object.material]:[]){for(const value of Object.values(material))if(value?.isTexture)value.dispose();material.dispose();}});active=null;}
function tuneMaterials(){const roughness=Number($('roughness').value)/100,metalness=Number($('metalness').value)/100;$('roughness-value').value=`${Math.round(roughness*100)} %`;$('metalness-value').value=`${Math.round(metalness*100)} %`;$('material-count').textContent=active?`${tuneHeroMaterials(active.model,{roughness,metalness})} matières réglables`:'';}
function playClip(name){if(!active)return;const clip=active.clips.find(clip=>clip.name===name);if(!clip)return;active.mixer.stopAllAction();const action=active.mixer.clipAction(clip);action.reset();action.setLoop(['idle','idleLook','walk','run'].includes(name)?T.LoopRepeat:T.LoopOnce);action.clampWhenFinished=true;action.play();active.clip=name;}
async function load(id,file=null,variant='legacy'){const request=++token;$('model-status').textContent='Chargement du modèle…';$('model-status').classList.remove('pass');$('hero').value=id;$('skin-pilot').disabled=id!=='seraphine';$('atelier-v2').disabled=id!=='seraphine';$('surface-v3').disabled=id!=='seraphine';$('silhouette-v4').disabled=id!=='seraphine';$('groom-v4-1').disabled=id!=='seraphine';$('target').src=TARGET_ROOT+HERO_TARGETS[id];$('target').alt=`Fiche artistique de ${$('hero').selectedOptions[0].textContent}`;$('original').href=$('target').src;$('turnaround').href=`../../03_assets/characters/${id}/turnaround-v1.png`;$('source').textContent=file?`Fichier local : ${file.name}`:variant==='groom'&&id==='seraphine'?'Séraphine · cheveux V4.1 en mèches déformables, revue artistique à taille de combat':variant==='silhouette'&&id==='seraphine'?'Séraphine · silhouette V4 skinnée, cheveux/coiffe/étoffes UV et PBR, revue artistique requise':variant==='surface'&&id==='seraphine'?'Séraphine · visage/corset UV et PBR V3, revue à taille de combat requise':variant==='atelier'&&id==='seraphine'?'Séraphine · mèches et étoffes skinnées V2, revue artistique requise':variant==='skin'&&id==='seraphine'?'Séraphine · candidat skinné, revue artistique requise':'Modèle de travail actuel · volume-v1';$('candidate').value='';
 try{const path=id==='seraphine'&&variant==='groom'?`../../03_assets/characters/seraphine/modeling/seraphine-silhouette-v4-1.glb`:id==='seraphine'&&variant==='silhouette'?`../../03_assets/characters/seraphine/modeling/seraphine-silhouette-v4-optimized.glb`:id==='seraphine'&&variant==='surface'?`../../03_assets/characters/seraphine/modeling/seraphine-surface-v3.glb`:id==='seraphine'&&variant==='atelier'?`../../03_assets/characters/seraphine/modeling/seraphine-atelier-v2.glb`:id==='seraphine'&&variant==='skin'?`../../03_assets/characters/seraphine/modeling/seraphine-skin-pilot.glb`:`../../03_assets/characters/${id}/volume-v1/hero.glb`;const buffer=file?await file.arrayBuffer():await fetch(path).then(response=>{if(!response.ok)throw Error(`GLB introuvable : ${response.status}`);return response.arrayBuffer();});if(request!==token)return;const report=inspectHeroGlb(new Uint8Array(buffer),{hero:id,stage:'release'});reportResult(report);disposeActive();
  const gltf=await loader.parseAsync(buffer,'');if(request!==token){gltf.scene.traverse(o=>o.geometry?.dispose());return;}const model=gltf.scene,box=new T.Box3().setFromObject(model),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),scale=size.y>0?Math.min(2.5,2.35/size.y):1,wrapper=new T.Group();model.scale.setScalar(scale);model.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);wrapper.add(model);scene.add(wrapper);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});
  const mixer=new T.AnimationMixer(model),clips=gltf.animations??[];active={wrapper,model,mixer,clips,clip:null};tuneMaterials();$('clip').replaceChildren();for(const clip of clips){const option=document.createElement('option');option.value=clip.name;option.textContent=`${clip.name} · ${clip.duration.toFixed(1)} s`;$('clip').append(option);}if(clips.length){const idle=clips.find(clip=>clip.name==='idle')??clips[0];$('clip').value=idle.name;playClip(idle.name);}else $('model-status').textContent='Modèle chargé sans animation';
 }catch(error){if(request!==token)return;disposeActive();$('model-status').textContent='Impossible de charger le modèle';$('issues').replaceChildren();const item=document.createElement('li');item.textContent=error.message;$('issues').append(item);}
}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(!document.hidden){if(active&&!paused)active.mixer.update(dt);renderer.render(scene,camera);}requestAnimationFrame(frame);}requestAnimationFrame(frame);
renderer.domElement.addEventListener('pointerdown',event=>{drag=event.clientX;renderer.domElement.setPointerCapture(event.pointerId);});renderer.domElement.addEventListener('pointermove',event=>{if(drag!==null&&active){active.wrapper.rotation.y+=(event.clientX-drag)*.009;drag=event.clientX;}});for(const type of ['pointerup','pointercancel','lostpointercapture'])renderer.domElement.addEventListener(type,()=>{drag=null;});
$('hero').addEventListener('change',event=>load(event.target.value));$('skin-pilot').addEventListener('click',()=>load('seraphine',null,'skin'));$('atelier-v2').addEventListener('click',()=>load('seraphine',null,'atelier'));$('surface-v3').addEventListener('click',()=>load('seraphine',null,'surface'));$('silhouette-v4').addEventListener('click',()=>load('seraphine',null,'silhouette'));$('groom-v4-1').addEventListener('click',()=>load('seraphine',null,'groom'));$('candidate').addEventListener('change',event=>{const file=event.target.files?.[0];if(file)load($('hero').value,file);});$('clip').addEventListener('change',event=>playClip(event.target.value));$('replay').addEventListener('click',()=>playClip($('clip').value));$('pause').textContent=paused?'Reprendre':'Pause';$('pause').setAttribute('aria-pressed',String(paused));$('pause').addEventListener('click',()=>{paused=!paused;$('pause').textContent=paused?'Reprendre':'Pause';$('pause').setAttribute('aria-pressed',String(paused));});$('angle').addEventListener('click',()=>{face=!face;positionCamera();$('angle').textContent=face?'Vue trois quarts':'Vue de face';});$('head-detail').addEventListener('click',()=>{headDetail=!headDetail;if(headDetail)combatScale=false;positionCamera();});$('combat-scale').addEventListener('click',()=>{combatScale=!combatScale;if(combatScale)headDetail=false;positionCamera();});
$('roughness').addEventListener('input',tuneMaterials);$('metalness').addEventListener('input',tuneMaterials);$('material-reset').addEventListener('click',()=>{$('roughness').value='100';$('metalness').value='100';tuneMaterials();});
window.addEventListener('pagehide',()=>{token++;disposeActive();renderer.dispose();renderer.forceContextLoss();});void load(heroIds.includes(initial)?initial:'seraphine',null,initialModel);
