// All timelines are presentation-only: rewards are committed once before entry.
export function ritualStage(progress){return progress<.22?'seal':progress<.48?'gather':progress<.73?'silhouette':progress<1?'unveil':'revealed';}
export function mountRitual(host,hero,ritual,portrait,{reduced=false,onSound=()=>{}}={}){
 host.innerHTML=`<div class="ritual tier-${ritual.id}" data-stage="seal" style="--accent:${hero.accent}"><div class="ritual-stars">${Array.from({length:36},(_,i)=>`<i style="--i:${i};--r:${20+i%5*12}%"></i>`).join('')}</div><div class="ritual-circle one"></div><div class="ritual-circle two"></div><div class="ritual-circle three"></div><div class="ritual-flare"></div><div class="ritual-heading"><p class="eyebrow">RITUEL ${ritual.id} · ${ritual.name.toUpperCase()}</p><p class="ritual-status" role="status">Le sceau s’éveille…</p></div><div class="ritual-actor"></div><div class="ritual-result"><p class="eyebrow">✦ MYTHIQUE · ${hero.element}</p><h2>${hero.name}</h2><p>${hero.title}</p><strong>+${ritual.fragments} fragments · Écho lié</strong><button class="gold-button" data-close-modal>Accueillir cet écho</button></div><button class="ritual-skip">Passer la mise en scène →</button></div>`;
 const root=host.firstElementChild,skip=root.querySelector('.ritual-skip'),status=root.querySelector('.ritual-status');const destroyPortrait=portrait(root.querySelector('.ritual-actor'),hero.id);
 let frame,elapsed=0,last=performance.now(),stopped=false,previous='';
 const words={seal:'Le sceau s’éveille…',gather:ritual.id===3?'Les constellations convergent…':'Les échos se rassemblent…',silhouette:'Une présence traverse le voile…',unveil:'Le serment prend forme…',revealed:`${hero.name} a répondu à votre appel.`};
 function update(progress){const stage=ritualStage(progress);root.dataset.stage=stage;root.style.setProperty('--progress',Math.min(1,progress));if(stage!==previous){status.textContent=words[stage];previous=stage;if(stage==='unveil')onSound();}skip.hidden=stage==='revealed';root.querySelector('.ritual-result button').tabIndex=stage==='revealed'?0:-1;}
 function tick(now){if(!document.hidden)elapsed+=Math.max(0,now-last);last=now;update(reduced?1:elapsed/ritual.duration);if(!stopped&&elapsed<ritual.duration&&!reduced)frame=requestAnimationFrame(tick);}
 skip.onclick=()=>{elapsed=ritual.duration;cancelAnimationFrame(frame);update(1);root.querySelector('[data-close-modal]').focus();};
 frame=requestAnimationFrame(tick);return()=>{stopped=true;cancelAnimationFrame(frame);destroyPortrait();};
}
export function transitionView(view,kind,reduced){if(reduced)return;view.getAnimations().forEach(a=>a.cancel());view.animate(kind==='play'?[{opacity:0,filter:'blur(10px)',transform:'scale(.96)'},{opacity:1,filter:'blur(0px)',transform:'scale(1)'}]:[{opacity:0,transform:'translateY(15px)'},{opacity:1,transform:'translateY(0)'}],{duration:kind==='play'?650:350,easing:'cubic-bezier(.2,.65,.25,1)'});}
