import {HEROES} from './heroes.mjs';
import {EQUIPMENT,SLOTS,ENEMIES} from './edition-data.mjs';
import {heroBonuses} from './profile.mjs';
import {KITS,ACTION_COOLDOWNS} from './ruins-rules.mjs';
import {levelCap,xpRequired,availablePoints,talentsFor,talentEffect,talentCheck,ascensionCheck,ascensionCost} from './progression.mjs';
const art=id=>`../../03_assets/characters/${id}/presentation-v1.png`,fmt=n=>Math.round(n).toLocaleString('fr-FR');
const tabs=[['info','♙','Infos'],['equipment','⚔','Équipement'],['talents','✥','Talents'],['ascension','✧','Ascension'],['powers','☽','Compétences']];
const gearArt=e=>`<span class="gear-art" style="--col:${e.index%3};--row:${Math.floor(e.index/3)}"></span>`;
function ruinsPowers(id,b){
 const kit=KITS[id],hit=n=>`${fmt(n*b.attack)} dégâts`,heal=n=>`${fmt(n*b.healing)} PV`,shield=n=>`${fmt(n*b.shield)} bouclier`;
 const second={seraphine:`${shield(360)} personnel · 1,8 s de protection`,nyxara:`${hit(260)} · ${heal(210)} rendus à Nyxara`,lysael:`${heal(240)} rendus à chaque allié`,voren:`${shield(360)} personnel`}[id];
 const third=id==='lysael'?`${shield(200)} à chaque allié`:`${hit(190)} · ennemis étourdis pendant 2,5 s`;
 const ultimate={seraphine:`${hit(780*b.ultimate)} en zone`,nyxara:`${hit(780*b.ultimate)} en zone · ${heal(330)} rendus à Nyxara`,lysael:`${heal(500*b.ultimate)} et ${shield(250*b.ultimate)} à chaque allié`,voren:`${hit(780*b.ultimate)} en zone · ${shield(500)} personnel`}[id];
 const actions=[
  {key:'J',category:'ATTAQUE DE BASE',name:'Enchaînement',effect:`Trois gestes successifs · ${hit(kit.basic)} par frappe`,energy:`+${14+b.energy} énergie`},
  {key:'1',category:'COMPÉTENCE I',name:kit.skills[0],effect:`${hit(220)} aux ennemis proches`,energy:`+${20+b.energy} énergie`},
  {key:'2',category:'COMPÉTENCE II',name:kit.skills[1],effect:second,energy:`+${15+b.energy} énergie`},
  {key:'3',category:'COMPÉTENCE III',name:kit.skills[2],effect:third,energy:`+${18+b.energy} énergie`},
  {key:'R',category:'SUPER',name:kit.ultimate,effect:ultimate,energy:'100 énergie requise'}
 ];
 return actions.map((a,i)=>`<article><span class="power-rank">${a.key}</span><div><p class="eyebrow">${a.category}</p><h2>${a.name}</h2><p>${a.effect}</p><div class="effective-stats"><b>${(ACTION_COOLDOWNS[i]*b.cooldown).toFixed(1)} s de recharge</b><b>${a.energy}</b></div></div></article>`).join('');
}
export function renderHeroSheet(host,profile,heroId,tab='info',node='edge',portrait){
 const h=HEROES.find(h=>h.id===heroId)??HEROES.find(h=>h.id===profile.selected),v=profile.heroes[h.id],b=heroBonuses(profile,h.id),cap=levelCap(v),atCap=v.level>=cap,need=xpRequired(v.level),rank=v.ascension??0;
 if(!tabs.some(t=>t[0]===tab))tab='info';const route=(t,n)=>`#heroes/${h.id}/${t}${n?'/'+n:''}`;
 const xp=`<div class="sheet-xp"><div><strong>Niv. ${v.level} <small>/ ${cap}</small></strong><span>${atCap?'Palier atteint':`${fmt(v.xp)} / ${fmt(need)} XP`}</span></div><div class="progress"><i style="width:${atCap?100:Math.min(100,v.xp/need*100)}%"></i></div><p>${atCap&&rank<2?`${fmt(v.xp)} XP en réserve · accomplissez l’ascension.`:atCap?'Niveau maximal de cette édition.':'L’expérience gagnée en aventure fait monter le niveau automatiquement.'}</p></div>`;
 let content='';
 if(tab==='info')content=`<p class="eyebrow">✦ MYTHIQUE · ${h.element}</p><h1>${h.name}</h1><h2>${h.title}</h2><p class="sheet-role">${h.role} · Ascension ${rank} / 2</p><p class="sheet-description">${h.description}</p>${xp}<div class="sheet-stat-table"><div><span>Vie maximale · Pont des Serments</span><strong>${fmt(KITS[h.id].hp*b.health)}</strong></div><div><span>Attaque de base · Pont des Serments</span><strong>${fmt(KITS[h.id].basic*b.attack)}</strong></div><div><span>Bonus de soins</span><strong>+${Math.round((b.healing-1)*100)} %</strong></div><div><span>Recharge</span><strong>−${Math.round((1-b.cooldown)*100)} %</strong></div><div><span>Points de talent disponibles</span><a href="${route('talents')}">${availablePoints(v)} →</a></div></div><button class="gold-button" data-select="${h.id}">${profile.selected===h.id?'✓ Héros d’aventure sélectionné':'Choisir pour les aventures'}</button><div class="sheet-training"><h3>Améliorer le niveau</h3><p>${v.fragments} fragments d’âme · ${v.copies} échos liés</p><button data-upgrade="${h.id}" ${atCap?'disabled':''}>Entraîner · ${v.level*100} or + 20 fragments</button><small>Complète l’XP du niveau actuel. Le combat permet aussi de progresser sans dépenser de fragments.</small></div>`;
 if(tab==='equipment')content=`<p class="eyebrow">L’HÉRITAGE DU MYTHIQUE</p><h1>Équipement</h1><p class="sheet-description">Trois emplacements, une relique. Les pièces peuvent être transférées entre les porteurs compatibles.</p><div class="sheet-equipment">${Object.entries(SLOTS).map(([slot,label])=>{const item=EQUIPMENT.find(e=>e.id===v.gear[slot]),upgrade=item?(profile.gearRanks[item.id]??0):0;return `<article><div class="gear-slot">${item?gearArt(item):'<span class="empty-slot">◇</span>'}<div><small>${label}</small><strong>${item?.name??'Emplacement libre'}${item?` +${upgrade}`:''}</strong><span>${item?[item.attack?`+${(item.attack*(1+upgrade*.3)*100).toFixed(1)} % dégâts`:'',item.health?`+${(item.health*(1+upgrade*.3)*100).toFixed(1)} % vie`:''].filter(Boolean).join(' · '):'Aucune pièce équipée'}</span></div></div><label>Choisir une pièce<select data-sheet-equip="${slot}" data-owner="${h.id}"><option value="">Retirer l’équipement</option>${EQUIPMENT.filter(e=>e.slot===slot&&profile.equipment.includes(e.id)&&(!e.hero||e.hero===h.id)).map(e=>{const owner=HEROES.find(x=>profile.heroes[x.id].gear[slot]===e.id);return `<option value="${e.id}" ${v.gear[slot]===e.id?'selected':''}>${e.name}${owner&&owner.id!==h.id?' · porté par '+owner.name:''}</option>`;}).join('')}</select></label>${item?`<button data-enhance="${item.id}" data-owner="${h.id}" ${upgrade>=3||profile.gold<60*(upgrade+1)?'disabled':''}>${upgrade>=3?'Amélioration maximale +3':`Améliorer +${upgrade+1} · ${60*(upgrade+1)} or`}</button>`:''}</article>`;}).join('')}</div><p class="muted">Chaque amélioration ajoute 30 % aux bonus de base de la pièce. Les bonus de vie et de dégâts cumulés sont plafonnés à ×2. La tenue illustrée reste celle du Mythique.</p><div class="button-row"><a href="#equipment/${h.id}">Forger et retrouver des objets →</a><a href="#relics">Équiper une relique →</a></div>`;
 if(tab==='talents'){const nodes=talentsFor(h.id),chosen=nodes.find(t=>t.id===node)??nodes[0],check=talentCheck(v,h.id,chosen.id),learned=v.talents[chosen.id]??0;content=`<p class="eyebrow">FAÇONNEZ VOTRE LÉGENDE</p><h1>Arbre de talents</h1><p class="talent-wallet"><b>${availablePoints(v)}</b> point(s) disponible(s) · 1 point tous les 2 niveaux, +2 par ascension.</p><div class="talent-tree">${['Puissance','Protection','Maîtrise'].map(branch=>`<div class="talent-branch"><h3>${branch}</h3>${nodes.filter(t=>t.branch===branch).map(t=>{const count=v.talents[t.id]??0,ready=talentCheck(v,h.id,t.id).ok;return `<a class="talent-node ${count?'learned':''} ${ready?'available':''} ${t.id===chosen.id?'selected':''}" href="${route('talents',t.id)}" aria-label="${t.name} · rang ${count} sur 3"><b>${t.icon}</b><span>${t.name}</span><small>${count} / 3 ${!count&&!ready?'· verrouillé':''}</small></a>`;}).join('')}</div>`).join('')}</div><article class="talent-detail"><p class="eyebrow">${chosen.branch} · RANG ${learned} / 3</p><h2>${chosen.name}</h2><p>${learned?`Actuel : ${talentEffect(chosen,learned)}.`:'Aucun rang appris.'}</p>${learned<3?`<p class="next-bonus">Prochain rang : ${talentEffect(chosen,learned+1)}</p>`:''}<ul><li>Niveau ${chosen.level} ${v.level>=chosen.level?'✓':''}</li>${chosen.parent?`<li>${nodes.find(t=>t.id===chosen.parent).name} · rang 2 ${(v.talents[chosen.parent]??0)>=2?'✓':''}</li>`:''}${chosen.ascension?`<li>Ascension ${chosen.ascension} ${rank>=chosen.ascension?'✓':''}</li>`:''}</ul><button class="gold-button" data-learn="${chosen.id}" data-owner="${h.id}" ${check.ok?'':'disabled'}>${check.reason}</button></article><button class="talent-reset" data-reset-talents="${h.id}" ${Object.keys(v.talents).length?'':'disabled'}>Réinitialiser les talents · gratuit</button><p class="muted">Les points sont intégralement rendus. Les choix et bonus sont enregistrés, puis appliqués au prochain combat.</p>`;}
 if(tab==='ascension'){const cost=ascensionCost(v),check=ascensionCheck(profile,h.id);content=`<p class="eyebrow">AU-DELÀ DES LIMITES</p><h1>Ascension</h1><div class="ascension-stars" aria-label="Ascension ${rank} sur 2">${[0,1,2].map(i=>`<span class="${i<=rank?'lit':''}">✦</span>`).join('')}</div><h2>${rank===0?'Éveil du serment':rank===1?'Résonance des mondes':'Mythique accompli'}</h2>${xp}<div class="ascension-track">${[0,1,2].map(i=>`<article class="${rank===i?'active':''}"><small>PALIER ${i}</small><b>Niv. ${10+i*10}</b><span>${i===0?'Origine':'+5 % dégâts et vie · +2 points'}</span></article>`).join('')}</div>${rank<2?`<p class="sheet-description">L’ascension ouvre les dix niveaux suivants. L’XP en réserve est immédiatement utilisée et les talents supérieurs deviennent accessibles.</p><div class="ascension-cost"><span class="${profile.gold>=cost.gold?'enough':''}">Or <b>${fmt(profile.gold)} / ${cost.gold}</b></span><span class="${v.fragments>=cost.fragments?'enough':''}">Fragments <b>${v.fragments} / ${cost.fragments}</b></span><span class="${profile.essence>=cost.essence?'enough':''}">Essences <b>${profile.essence} / ${cost.essence}</b></span></div><button class="gold-button" data-ascend="${h.id}" ${check.ok?'':'disabled'}>${check.reason}</button><p class="muted">Fragments : invocations du héros. Essences : 2 par victoire en campagne, 1 dans chaque autre aventure.</p>`:'<p class="sheet-description">Les deux ascensions sont accomplies. Continuez à perfectionner vos talents et votre équipement.</p>'}<a href="#activities">Gagner de l’expérience en aventure →</a>`;}
 if(tab==='powers')content=`<p class="eyebrow">LE STYLE DU MYTHIQUE</p><h1>Compétences</h1><p class="sheet-description">Actions jouables dans le Pont des Serments en 2,5D, avec les bonus actuels de niveau, équipement, relique et talents. Valeurs de combat provisoires.</p><div class="sheet-powers">${ruinsPowers(h.id,b)}</div><button class="gold-button" data-mode="campaign">Mettre les pouvoirs à l’épreuve →</button><a href="#codex">Lire les règles et connaître les ennemis →</a>`;
 host.innerHTML=`<section class="hero-sheet" style="--accent:${h.accent}"><a class="volume-entry" href="./motion-3d.html?hero=${h.id}">Les Mythiques prennent vie<small>Explorer les 42 mouvements · tourner le personnage · comparer au design</small></a><a class="target-reference-link" href="./targets.html?board=${h.id==='seraphine'?'seraphine-final':h.id}">Voir la cible artistique du personnage ↗</a><div class="sheet-roster">${HEROES.map(x=>`<a href="#heroes/${x.id}/${tab}" class="${x.id===h.id?'active':''}"><img src="${art(x.id)}" alt=""><span>${x.name}<small>Niv. ${profile.heroes[x.id].level} · Asc. ${profile.heroes[x.id].ascension}</small></span></a>`).join('')}</div><div class="sheet-frame"><nav class="sheet-nav" aria-label="Fiche de ${h.name}">${tabs.map(([id,icon,label])=>`<a href="${route(id)}" class="${tab===id?'active':''}" ${tab===id?'aria-current="page"':''}><b>${icon}</b><span>${label}</span>${id==='talents'&&availablePoints(v)>0?`<i>${availablePoints(v)}</i>`:''}</a>`).join('')}</nav><div class="sheet-layout ${tab==='talents'?'tree-layout':''}"><div class="sheet-art"><div class="sheet-moon"></div><div class="sheet-portrait"></div><div class="sheet-caption"><p class="eyebrow">✦ MYTHIQUE · ${h.role}</p><h2>${h.name}</h2><p>« ${h.quote} »</p></div></div><div class="sheet-panel">${content}</div></div></div></section>`;
 return portrait(host.querySelector('.sheet-portrait'),h.id);
}
