import {WIDTH,HEROES,ACTION_RULES,rankOf,createTacticalRun,enterNode,continueRoute,selectHero,reachableTiles,legalTargets,moveHero,useAction,endTurn,eventChance} from './tactics-rules.mjs';
import {createTacticsScene3D} from './tactics-scene-3d.mjs';

const $=id=>document.getElementById(id),storageKey='shadow-echoes:tactics:v2';
const html=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function readRun(){try{const value=JSON.parse(localStorage.getItem(storageKey));if(value?.version===2&&Array.isArray(value.route)&&Array.isArray(value.roster)&&['route','battle','event','victory','won','lost'].includes(value.phase))return value;}catch{}return createTacticalRun();}
let run=readRun(),selectedAction='move',useOmen=false,noticeTimer,volume=null,volumeAttempted=false,renderMode=localStorage.getItem('shadow-echoes:tactics:render:v1')==='volume'?'volume':'art';
const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(run));}catch{}}
function notify(message){const node=$('notice');node.textContent=message;node.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>node.classList.remove('visible'),2500);}
function unitAt(x,lane){const battle=run.battle;return battle?.heroes.find(h=>h.hp>0&&h.x===x&&h.lane===lane)??battle?.enemies.find(e=>e.hp>0&&e.x===x&&e.lane===lane);}
function history(){return `<div class="route-history">${run.route.map((node,i)=>`<b>${i+1} · ${html(node.name)}</b>`).join('<span>→</span>')}</div>`;}
function routePanel(){const node=$('route-panel');node.hidden=run.phase==='battle';if(node.hidden)return;
 if(run.phase==='route'){node.innerHTML=`<span class="eyebrow">Étape ${run.depth+1} / 7 · le retour est impossible</span><h2>${run.depth?'Choisissez la prochaine voie.':'Franchissez les portes.'}</h2><p>La nature du risque est visible ; les adversaires et le contenu exact restent inconnus jusqu’à l’entrée.</p><p>En combat, deux formations de quatre rangs se font face. Le rang 1 est au contact ; échanger deux alliés voisins coûte 1 PA. Les compétences indiquent leurs rangs de départ et leurs cibles possibles.</p>${history()}<div class="route-options">${run.options.map(option=>`<button class="route-option" data-node="${html(option.id)}"><span class="risk">${html(option.risk)}</span><strong>${html(option.name)}</strong><small>${html(option.hint)}</small></button>`).join('')}</div>${run.options.some(option=>option.kind==='mystery')?`<label><input id="use-omen" type="checkbox" ${useOmen?'checked':''} ${run.omens<1?'disabled':''}> Dépenser un Sceau du Destin (${run.omens}) sur une voie Mystère</label><p class="chance">Chance d’événement spécial : ${Math.round(eventChance(useOmen&&run.omens>0)*100)} % pour cette voie.</p>`:''}`;return;}
 if(run.phase==='event'){node.innerHTML=`<span class="eyebrow">Emplacement ${run.depth} / 7 · chemin verrouillé</span><h2>${html(run.event?.title??'Événement')}</h2><p>${html(run.event?.text??'')}</p>${run.event?.chance!=null?`<p class="chance">Chance appliquée : ${Math.round(run.event.chance*100)} %. Tirage fixé pour cette expédition.</p>`:''}${history()}<button class="continue" data-continue>Continuer →</button>`;return;}
 if(run.phase==='victory'){const last=run.route.at(-1);node.innerHTML=`<span class="eyebrow">Victoire · étape ${run.depth} / 7</span><h2>${html(last?.name??'Rencontre')} libéré.</h2><p>Le groupe conserve ses blessures et son énergie. La route déjà empruntée reste fermée.</p>${history()}<button class="continue" data-continue>${run.depth>=7?'Terminer l’expédition':'Voir les prochaines voies'} →</button>`;return;}
 node.innerHTML=run.phase==='won'?`<span class="eyebrow">Chapitre I · victoire</span><h2>Le trône brisé est tombé.</h2><p>Expédition témoin terminée. Aucun or ni XP de la Citadelle n’est attribué par ce prototype tactique.</p>${history()}<button class="continue" data-restart>Nouvelle expédition</button>`:`<span class="eyebrow">Chapitre I · défaite</span><h2>Le Voile referme la route.</h2><p>Les quatre Mythiques sont tombés. Votre chemin reste inscrit dans la chronique, sans récompense de la Citadelle.</p>${history()}<button class="continue" data-restart>Recommencer</button>`;
}
function battleBoard(){const arena=$('arena'),top=$('battle-top');arena.hidden=top.hidden=run.phase!=='battle';if(run.phase!=='battle'){arena.innerHTML='';return;}const battle=run.battle,reach=new Set(selectedAction==='move'?reachableTiles(run,battle.selected).map(slot=>slot.x):[]),targets=new Set(selectedAction!=='move'?legalTargets(run,battle.selected,selectedAction):[]),intents=new Set(battle.enemies.filter(enemy=>enemy.hp>0&&enemy.intent?.kind==='strike').map(enemy=>enemy.intent.x));
 top.innerHTML=`<span class="eyebrow">${html(run.route.at(-1)?.name??'Combat')}</span><strong>Tour ${battle.round}</strong><p>${battle.enemies.filter(enemy=>enemy.hp>0).length} adversaire(s) · rangs visés en rouge</p>`;
 arena.innerHTML=Array.from({length:WIDTH},(_,x)=>{const unit=unitAt(x,0),rank=x<4?4-x:x-3,side=x<4?'ally-slot':'enemy-slot',classes=['tile',side,rank===1?'front':'',reach.has(x)?'reachable':'',intents.has(x)?'intent':''].filter(Boolean).join(' '),tag=`<span class="rank-label">${x<4?'ALLIÉS':'ENNEMIS'} · R${rank}</span>`;
  if(!unit)return `<button class="${classes}" data-x="${x}" data-lane="0" role="gridcell" aria-label="Rang ${rank} ${x<4?'allié':'ennemi'} libre">${tag}</button>`;
  const hero=!!HEROES[unit.id],name=hero?HEROES[unit.id].name:unit.name,legal=targets.has(unit.id),selectedUnit=hero&&battle.selected===unit.id,effect=battle.effect?.target===unit.id?`effect-${battle.effect.kind}`:battle.effect?.actor===unit.id?'effect-cast':'',portrait=hero?`<img src="../../03_assets/characters/${unit.id}/presentation-v1.png" alt="">`:`<span class="enemy-art ${unit.boss?'boss':battle.kind==='elite'?'elite':'common'}" aria-hidden="true"></span><span class="sigil" aria-hidden="true">${unit.boss?'✹':'✦'}</span>`,intent=unit.intent?.kind==='strike'?`<span class="intent-mark">⚠ ${unit.damage}</span>`:'';
  return `<button class="${classes}" data-x="${x}" data-lane="0" data-unit="${html(unit.id)}" role="gridcell" aria-label="${html(name)}, ${unit.hp} points de vie, rang ${rank}">${tag}<span class="unit ${hero?'hero':'enemy'} ${legal?'legal':''} ${selectedUnit?'selected':''} ${effect}">${portrait}${intent}<span class="name">${html(name)}</span><span class="hpbar"><i style="width:${Math.max(0,Math.round(unit.hp/unit.maxHp*100))}%"></i></span></span></button>`;}).join('');
}
function party(){const heroes=run.phase==='battle'?run.battle.heroes:run.roster;const selected=run.battle?.selected;$('party').innerHTML=heroes.map(hero=>`<button data-hero="${hero.id}" aria-pressed="${run.phase==='battle'&&selected===hero.id}" class="${hero.hp<=0?'fallen':''}"><img src="../../03_assets/characters/${hero.id}/presentation-v1.png" alt=""><span><b>${HEROES[hero.id].name}</b><small>${Math.ceil(hero.hp)} / ${hero.maxHp} PV${run.phase==='battle'?` · ${hero.ap} PA · R${rankOf(hero)}`:''}</small><small>✧ ${hero.energy} / 100${hero.shield?` · ⛨ ${hero.shield}`:''}</small></span></button>`).join('');}
function actions(){const battle=run.battle,active=run.phase==='battle',hero=battle?.heroes.find(h=>h.id===battle.selected),kit=HEROES[hero?.id];$('action-title').textContent=active?`${kit.name} · rang ${rankOf(hero)} · ${hero.ap} PA`:'Choisissez votre chemin';$('action-hint').textContent=active?`${kit.role} · R = rang, A = alliés, E = ennemis. Un échange coûte 1 PA.`:'Un seul chemin mène au demi-boss puis au boss.';
 const items=[['move','Déplacer','1 PA · 1 rang / échange'],['basic','Attaque','1 PA · +30 ✧'],['skill1',kit?.skills[0]??'Compétence I','2 PA · +10 ✧'],['skill2',kit?.skills[1]??'Compétence II','2 PA · +10 ✧'],['skill3',kit?.skills[2]??'Compétence III','2 PA · +10 ✧'],['super',kit?.super??'Super','2 PA · 100 ✧'],['end','Fin du tour','Ennemis →']];$('actions').innerHTML=items.map(([action,label,detail])=>{const rule=ACTION_RULES[hero?.id]?.[action],availability=action==='move'?reachableTiles(run,hero?.id).length:action==='end'?1:legalTargets(run,hero?.id,action).length,position=rule?` · R${rule.from.join('/')}${rule.to?` → ${rule.ally?'A':'E'}${rule.to.join('/')}`:''}`:'';return `<button data-action="${action}" class="${selectedAction===action&&action!=='end'?'active':''}" ${!active||action!=='end'&&!availability?'disabled':''}><strong>${html(label)}</strong><small>${detail}${position}</small></button>`;}).join('');}
function render(){const place=run.route.at(-1)?.name??'Aux portes des ruines';$('chapter-status').textContent=run.phase==='battle'?`${place} · tour ${run.battle.round}`:run.phase==='route'?'Choisissez un embranchement. Aucun retour possible.':place;routePanel();battleBoard();party();actions();$('log').innerHTML=[...(run.battle?.log??[]),...run.log].slice(0,8).map(entry=>`<p>${html(entry)}</p>`).join('');if(run.phase==='battle'&&renderMode==='volume'&&!volumeAttempted){volumeAttempted=true;try{volume=createTacticsScene3D($('arena-volume'),{reduced:matchMedia('(prefers-reduced-motion:reduce)').matches});}catch(error){console.warn('Plateau 3D indisponible ; plateau illustré conservé.',error);renderMode='art';$('arena-volume').hidden=true;}}volume?.sync(renderMode==='volume'?run:{phase:'route'});document.querySelector('.scene').classList.toggle('volume-ready',renderMode==='volume'&&!!volume&&run.phase==='battle');$('toggle-render').textContent=renderMode==='volume'?'Vue illustrée':'Voir étude 3D';$('toggle-render').setAttribute('aria-pressed',String(renderMode==='volume'));const model=new URLSearchParams(location.search).get('seraphine');$('scene-note').textContent=renderMode==='volume'?model==='lookdev-v1'?'Séraphine 2,5D issue de la référence · essai visuel, animations complètes à produire':model==='groom-v4-1'?'Quatre rangs par camp · Séraphine V4.1 et décor en volume, revue artistique requise':model==='silhouette-v4'?'Quatre rangs par camp · Séraphine V4 et décor en volume, revue à taille de combat':model==='surface-v3'?'Quatre rangs par camp · Séraphine V3 en revue à taille de combat':'Quatre rangs par camp · décor en volume, personnage V2 en étude':'Quatre rangs par camp · changez de position pour débloquer les compétences';save();}
function positions(){return new Map([...$('arena').querySelectorAll('[data-unit]')].map(cell=>[cell.dataset.unit,cell.querySelector('.unit').getBoundingClientRect()]));}
function animatePositions(before){if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;for(const cell of $('arena').querySelectorAll('[data-unit]')){const old=before.get(cell.dataset.unit);if(!old)continue;const unit=cell.querySelector('.unit'),now=unit.getBoundingClientRect(),dx=old.left-now.left,dy=old.top-now.top;if(Math.hypot(dx,dy)<2)continue;unit.animate([{transform:`translate(${dx}px,${dy}px) scale(.94)`,filter:'brightness(1.4)'},{transform:'translate(0,0) scale(1)',filter:'brightness(1)'}],{duration:340,easing:'cubic-bezier(.2,.8,.2,1)'});}}
function applyAction(targetId){const id=run.battle.selected,result=useAction(run,id,selectedAction,targetId);if(!result.ok){notify('Cette action demande une autre position, une cible à portée ou assez de points d’action.');return;}volume?.action(id,selectedAction,targetId);render();}
function restart(){if(run.phase!=='won'&&run.phase!=='lost'&&!confirm('Abandonner cette expédition et recommencer ?'))return;run=createTacticalRun((Math.random()*4294967296)>>>0);selectedAction='move';useOmen=false;render();}
$('route-panel').addEventListener('click',event=>{const choice=event.target.closest('[data-node]');if(choice){const option=run.options.find(o=>o.id===choice.dataset.node),result=enterNode(run,choice.dataset.node,{useOmen:option?.kind==='mystery'&&useOmen});if(!result.ok){notify('Cette voie n’est plus accessible.');return;}selectedAction='move';useOmen=false;render();return;}if(event.target.closest('[data-continue]')){continueRoute(run);render();return;}if(event.target.closest('[data-restart]'))restart();});
$('route-panel').addEventListener('change',event=>{if(event.target.id==='use-omen'){useOmen=event.target.checked;render();}});
$('party').addEventListener('click',event=>{const button=event.target.closest('[data-hero]');if(button&&selectHero(run,button.dataset.hero)){selectedAction='move';render();}});
$('actions').addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action;if(action==='end'){const before=positions();endTurn(run);volume?.enemyTurn();selectedAction='move';render();animatePositions(before);return;}selectedAction=action;render();const id=run.battle?.selected;if(['lysael','voren'].includes(id)&&action==='super'&&legalTargets(run,id,action).includes(id))applyAction(id);});
$('arena').addEventListener('click',event=>{const cell=event.target.closest('.tile');if(!cell||run.phase!=='battle')return;const unit=cell.dataset.unit,hero=unit&&HEROES[unit],selected=run.battle.selected,x=+cell.dataset.x;if(hero&&selectedAction.startsWith('skill')&&legalTargets(run,selected,selectedAction).includes(unit)){applyAction(unit);return;}if(selectedAction==='move'&&x<4&&reachableTiles(run,selected).some(slot=>slot.x===x)){const before=positions(),result=moveHero(run,selected,x,0);if(result.ok){volume?.action(selected,'move');render();animatePositions(before);}return;}if(hero){if(selectHero(run,unit)){selectedAction='move';render();}return;}if(unit&&selectedAction!=='move'){applyAction(unit);return;}notify(selectedAction==='move'?'Seuls les rangs alliés adjacents sont accessibles.':'Choisissez une cible surlignée.');});
$('restart').addEventListener('click',restart);
$('toggle-render').addEventListener('click',()=>{renderMode=renderMode==='art'?'volume':'art';try{localStorage.setItem('shadow-echoes:tactics:render:v1',renderMode);}catch{}render();});
document.addEventListener('keydown',event=>{if(run.phase!=='battle'||event.target instanceof HTMLInputElement)return;const mapped={KeyM:'move',KeyJ:'basic',Digit1:'skill1',Digit2:'skill2',Digit3:'skill3',KeyR:'super',Enter:'end'}[event.code];if(!mapped)return;event.preventDefault();$('actions').querySelector(`[data-action="${mapped}"]`)?.click();});
render();
