import test from 'node:test';import assert from 'node:assert/strict';
import {Box3,Vector3} from './vendor/three.module.js';
import {createHeroModel,MODEL_STYLE} from './hero-model-3d.mjs';
import {MOTIONS,sampleHeroPose,mixPoses} from './hero-motion-3d.mjs';
import {invocationRates,simulateInvocation,firstMythicDistribution,heroCostTotal} from './foundation-rules.mjs';
test('Tous les mouvements des quatre héros produisent des poses finies et déterministes',()=>{
 assert.equal(Object.keys(MOTIONS).length,42);
 for(const id of Object.keys(MODEL_STYLE))for(const [clip,def]of Object.entries(MOTIONS))for(const t of [0,.17,.43,.81,1]){const p=sampleHeroPose(id,clip,t*def.duration);assert.deepEqual(p,sampleHeroPose(id,clip,t*def.duration));const numbers=[...Object.values(p.joints).flat(),...p.offset,p.yaw,p.effect];assert.ok(numbers.every(Number.isFinite),id+'/'+clip);assert.ok(numbers.every(n=>Math.abs(n)<7),id+'/'+clip);}
});
test('Corps volumétriques, articulations connectées, armes attachées et mouvements dans un volume borné',()=>{
 for(const id of Object.keys(MODEL_STYLE)){const model=createHeroModel(id);assert.equal(model.bones.lowerArmR.parent,model.bones.upperArmR);assert.equal(model.bones.handR.parent,model.bones.lowerArmR);assert.equal(model.root.getObjectByName('weapon').parent,model.bones.handR);model.apply(sampleHeroPose(id,'idle',0));const start=model.bones.handR.getWorldPosition(new Vector3());model.apply(sampleHeroPose(id,'attack3',.4));assert.ok(start.distanceTo(model.bones.handR.getWorldPosition(new Vector3()))>.12,id);for(const clip of ['idle','run','dodgeLeft','ultimateCast','death','revive']){model.apply(sampleHeroPose(id,clip,MOTIONS[clip].duration*.6),1);const size=new Box3().setFromObject(model.root).getSize(new Vector3());assert.ok(size.x>0&&size.y>0&&size.z>.2);assert.ok(size.x<5&&size.y<5&&size.z<5,id+'/'+clip);}model.dispose();}
});
test('Fondu entre gestes sans saut de pose, et pas de dépendance au nombre de frames',()=>{const a=sampleHeroPose('seraphine','attack1',.3),b=sampleHeroPose('seraphine','idle',1);assert.deepEqual(mixPoses(a,b,0),a);assert.deepEqual(mixPoses(a,b,1).offset,b.offset);assert.deepEqual(sampleHeroPose('voren','run',2),sampleHeroPose('voren','run',120/60));});
test('Probabilités normalisées pour tous les compteurs et garanties prioritaires',()=>{for(let m=0;m<80;m++)for(let e=0;e<10;e++){const r=invocationRates({mythicDry:m,epicDry:e});assert.ok(Math.abs(Object.values(r).reduce((a,b)=>a+b,0)-1)<1e-10);if(e===9)assert.equal(r.common+r.rare,0);if(m===79)assert.equal(r.mythic,1);}assert.equal(invocationRates({mythicDry:65}).mythic,.052000000000000005);assert.throws(()=>invocationRates({mythicDry:-1}));});
test('La perte du 50/50 garantit le Mythique de bannière suivant et les tirages consécutifs conservent les compteurs',()=>{let state={mythicDry:79,epicDry:9};const first=simulateInvocation(state,.99,.99);assert.equal(first.featured,false);assert.equal(first.state.featuredGuaranteed,true);const second=simulateInvocation({...first.state,mythicDry:79},.99,.99);assert.equal(second.featured,true);assert.equal(second.state.featuredGuaranteed,false);assert.throws(()=>simulateInvocation({},1));});
test('Coûts de la bible et distribution exacte incluant la garantie Épique+',()=>{assert.deepEqual(heroCostTotal(),{gold:2850000,xp:1078000,essences:465,stones:130});const d=firstMythicDistribution();assert.ok(Math.abs(d.totalProbability-1)<1e-9);assert.ok(d.mean>1&&d.mean<80);assert.equal(d.distribution.length,80);});
