/**
 * Registre des capacités Ellipse — source de vérité pour agents et Studio.
 * Décrit ce qui existe vs ce qui manque pour passer de la vectorisation procédurale
 * à un éditeur nouvelle génération (concept art → jeu shippable HD).
 */
import { z } from 'zod';

export const CapabilityStatusSchema = z.enum([
  'missing',
  'stub',
  'partial',
  'production_ready',
]);

export const CapabilityPrioritySchema = z.enum(['P0', 'P1', 'P2', 'P3']);

export const StudioCapabilitySchema = z.object({
  id: z.string(),
  stratum: z.string(),
  title: z.string(),
  status: CapabilityStatusSchema,
  priority: CapabilityPrioritySchema,
  maturity_pct: z.number().min(0).max(100),
  problem: z.string(),
  target: z.string(),
  owner_packages: z.array(z.string()),
  agent_roles: z.array(z.string()).default([]),
  blocking_for: z.array(z.string()).default([]),
  implementation_notes: z.array(z.string()).default([]),
});

export type StudioCapability = z.infer<typeof StudioCapabilitySchema>;

/** Moteurs à construire — chaque moteur est un sous-système que l'IA/agents doivent savoir invoquer. */
export const EVOLUTION_ENGINES = [
  {
    id: 'concept_fidelity_engine',
    title: 'Moteur fidélité concept → HD',
    status: 'partial' as const,
    description:
      'Planche → extraction sujet → cleanup neuronal/heuristique → pixel-diff gate → hybrid ou inpaint. Veloria IoU gate existe hors orchestrator.',
    packages: ['packages/pipeline', 'tools/lib/veloria'],
    entrypoints: ['generateHeroRuntimePack', 'produceRefinedHeroPack', 'compareSilhouettes'],
    missing: ['SAM2/BiRefNet', 'inpainting ComfyUI', 'gate bloquant stage 07_qa', 'style-lock embedding'],
  },
  {
    id: 'rig_animation_engine',
    title: 'Moteur rig & animation 2D',
    status: 'stub' as const,
    description: 'rig.json + atlas + state machine → runtime Pixi skeletal. Exporté mais non consommé par engine.',
    packages: ['packages/pipeline', 'packages/engine'],
    entrypoints: ['hero-runtime/assembly.ts', 'run-stages animation stage'],
    missing: ['Skeletal2DRenderer', 'anim-state-machine runtime', 'IK 2D', 'timeline Studio'],
  },
  {
    id: 'environment_tile_engine',
    title: 'Moteur environnements tileables',
    status: 'partial' as const,
    description: 'Extraction modules depuis planches → tileset + collision + parallax GDL + hazard zones.',
    packages: ['packages/pipeline', 'packages/engine', 'tools/lib/veloria'],
    entrypoints: ['buildEnvironmentSpec', 'generate-decor', 'levels.mjs', 'render/parallax-layers.ts'],
    missing: ['TilemapLayer renderer', 'tile_collision sim', 'Tiled export'],
  },
  {
    id: 'gameplay_systems_engine',
    title: 'Moteur systèmes gameplay data-driven',
    status: 'partial' as const,
    description: 'GDL systems[] → sim modules + rendu 2.5D (parallax, Y-sort, lanes). Veloria lane_runner dans engine.',
    packages: ['packages/engine', 'packages/shared/src/codegen', 'packages/shared/src/gdl/mechanics-registry.ts'],
    entrypoints: ['sim/systems.ts', 'sim/veloria-survival.ts', 'render/parallax-layers.ts', 'render/depth-sort.ts'],
    missing: ['gacha_summon', 'summon_units', 'loot_system', 'tile_collision sim', 'meta_systems runes/relics'],
  },
  {
    id: 'agent_orchestration_engine',
    title: 'Moteur orchestration durable agents',
    status: 'partial' as const,
    description: 'Workflows, work orders, itération projet, handoffs QA.',
    packages: ['packages/orchestrator', 'packages/agents'],
    entrypoints: ['master-ai.ts', 'durable-workflows.ts', 'project-iteration.ts'],
    missing: ['workflow_runs DB', 'executeWorkflow branché routes', 'GDL path multi-projet', 'retries QA PDF'],
  },
  {
    id: 'knowledge_rag_engine',
    title: 'Moteur connaissance projet (RAG)',
    status: 'missing' as const,
    description: 'Index GDD, art bible, specs, échecs QA → retrieval pour Cortex et agents.',
    packages: ['packages/cortex', 'packages/shared'],
    entrypoints: ['knowledge-base.ts (static only)', 'execution-memory.ts'],
    missing: ['vector store', 'workspace doc indexer', 'QA failure memory', 'CLIP style embedding'],
  },
  {
    id: 'qa_compliance_engine',
    title: 'Moteur QA & compliance bloquant',
    status: 'partial' as const,
    description: 'Pixel-diff, engine smoke, gates export, provenance.',
    packages: ['packages/pipeline', 'packages/shared', 'packages/agents'],
    entrypoints: ['pixel-diff-gate.mjs', 'qa-agent.ts', 'provenance.ts'],
    missing: ['export blocked on fail', 'headless engine smoke', 'game_tests runner', 'telemetry persistée'],
  },
  {
    id: 'studio_action_engine',
    title: 'Moteur actions Studio (factory actionnable)',
    status: 'partial' as const,
    description: 'UI déclenche stages, work orders, preview hot-reload — pas seulement lecture JSON.',
    packages: ['packages/studio', 'packages/orchestrator'],
    entrypoints: ['AssetsTab', 'ProductionTab', 'GenerateTab'],
    missing: ['ProductionTab run work order', 'Scene editor + engine embed', 'tilemap editor', 'rig timeline'],
  },
] as const;

export const STUDIO_CAPABILITY_GAPS: StudioCapability[] = [
  {
    id: 'asset.concept_to_hd',
    stratum: 'asset_factory_2d',
    title: 'Concept art → asset HD fidèle',
    status: 'partial',
    priority: 'P0',
    maturity_pct: 58,
    problem: 'Veloria/Echoes produisent surtout du vectoriel procédural ou des crops — très loin des planches.',
    target: 'IoU ≥ 0.72 vs planche OU inpaint validé humain ; master = pixels planche enrichis, pas silhouettes DSL.',
    owner_packages: ['pipeline', 'tools/lib/veloria'],
    agent_roles: ['Character', 'Art Direction', 'Animation'],
    blocking_for: ['runtime.sprites', 'studio.assets_tab_truth'],
    implementation_notes: [
      'hero-runtime-pack default stage 03_cleanup (orchestrator)',
      'runFidelityQa intégré stage 07_qa (@ellipse/pipeline)',
      'Veloria stage-08-inpaint.mjs CPU — 29/29 shipping IoU ≥ 0.72',
    ],
  },
  {
    id: 'asset.board_decomposition',
    stratum: 'asset_factory_2d',
    title: 'Décomposition planches → familles assets',
    status: 'partial',
    priority: 'P0',
    maturity_pct: 55,
    problem: 'Crops bbox OK ; pas de découpe intelligente multi-entités ni props modulaires.',
    target: 'Board → N packs avec manifest + style-lock par entité.',
    owner_packages: ['pipeline', 'studio'],
    agent_roles: ['Character', 'Decor', 'Integration'],
    blocking_for: ['asset.concept_to_hd'],
    implementation_notes: ['board-cutter.ts', 'ExtractionTab', 'catalog.mjs Veloria'],
  },
  {
    id: 'animation.rig_runtime',
    stratum: 'animation',
    title: 'Animation riggée consommée par le runtime',
    status: 'stub',
    priority: 'P0',
    maturity_pct: 12,
    problem: 'rig.json et atlas exportés ; engine = rectangles ou strip horizontal.',
    target: 'Pixi lit runtime_atlas.json + clips ; boss phases visuelles.',
    owner_packages: ['engine', 'pipeline'],
    agent_roles: ['Animation', 'Integration'],
    blocking_for: ['gameplay.boss_phases', 'gameplay.combat_feel'],
    implementation_notes: ['hero-runtime/assembly.ts', 'packages/engine skeletal-2D à créer'],
  },
  {
    id: 'world.tilemaps',
    stratum: 'world_factory',
    title: 'Tilemaps + collision + hazards spatialisés',
    status: 'partial',
    priority: 'P0',
    maturity_pct: 35,
    problem: 'Veloria arènes PNG ; TilemapLayer engine ajouté — collision grid sim à brancher.',
    target: 'GDL layout.tilemap + tile_collision sim + export Tiled.',
    owner_packages: ['engine', 'tools/lib/veloria'],
    agent_roles: ['Level', 'Decor'],
    blocking_for: ['gameplay.lane_survival'],
    implementation_notes: ['render/tilemap-layer.ts', 'platformsToTileLayer', 'generate-decor.ts'],
  },
  {
    id: 'gameplay.systems_catalog',
    stratum: 'gameplay_systems',
    title: 'Catalogue systèmes → sim implémentée',
    status: 'partial',
    priority: 'P0',
    maturity_pct: 72,
    problem: 'Codegen 40+ systèmes ; Veloria survivors branché dans engine (veloria-survival.ts) + tests headless.',
    target: 'Chaque system GDL survivors_like implémenté dans @ellipse/engine OU bridge Veloria→engine.',
    owner_packages: ['engine', 'shared/codegen'],
    agent_roles: ['Gameplay', 'Level'],
    blocking_for: ['runtime.shipping'],
    implementation_notes: ['sim/veloria-survival.ts', 'Studio runtime.ts EllipseEngine'],
  },
  {
    id: 'audio.gdl_playback',
    stratum: 'audio',
    title: 'Audio GDL (BGM/SFX/adaptive)',
    status: 'partial',
    priority: 'P1',
    maturity_pct: 48,
    problem: 'WAV procédural généré ; engine lit désormais URLs GDL avec repli oscillateurs.',
    target: 'Lecture /audio/* depuis GDL ; bus SFX ; musique adaptive par vague.',
    owner_packages: ['engine', 'agents'],
    agent_roles: ['Audio'],
    blocking_for: ['runtime.shipping'],
    implementation_notes: ['game-feel-audio.ts', 'agents AudioAgent WAV output'],
  },
  {
    id: 'meta.gacha_relics',
    stratum: 'gameplay_systems',
    title: 'Méta gacha / runes / reliques jouable',
    status: 'stub',
    priority: 'P1',
    maturity_pct: 25,
    problem: 'Catalogues JSON Veloria ; pas UI ni sim collection.',
    target: 'Draft blessings + gacha_summon + roster persistence.',
    owner_packages: ['studio', 'engine'],
    agent_roles: ['Gameplay', 'Integration'],
    blocking_for: ['studio.production_actions'],
    implementation_notes: ['Veloria blessings JSON', 'gacha_summon codegen TODO'],
  },
  {
    id: 'studio.production_actions',
    stratum: 'studio_editing',
    title: 'Studio actionne la fabrique (pas lecture seule)',
    status: 'partial',
    priority: 'P1',
    maturity_pct: 68,
    problem: 'ProductionTab exécute ordres via POST work-orders/run ; tools Veloria branchés orchestrator.',
    target: 'Boutons lancer sprint/stage/work-order ; WS feedback comme GenerateTab.',
    owner_packages: ['studio', 'orchestrator'],
    agent_roles: ['Integration', 'QA'],
    blocking_for: ['agents.durable_workflows'],
    implementation_notes: ['ProductionTab.tsx', 'run-veloria-sprints-cde.mjs → API route'],
  },
  {
    id: 'studio.scene_visual_editor',
    stratum: 'studio_editing',
    title: 'Éditeur scène visuel + preview engine embed',
    status: 'partial',
    priority: 'P1',
    maturity_pct: 35,
    problem: 'SceneEditorTab = champs numériques ; preview en modal iframe.',
    target: 'Canvas lanes/tiles + hot-reload GDL + @ellipse/engine embed.',
    owner_packages: ['studio', 'engine'],
    agent_roles: ['Level', 'Integration'],
    blocking_for: ['world.tilemaps'],
    implementation_notes: ['SceneEditorTab.tsx', 'PlayablePreviewSurface.tsx'],
  },
  {
    id: 'agents.durable_workflows',
    stratum: 'durable_orchestration',
    title: 'Workflows durables persistés & reprise',
    status: 'partial',
    priority: 'P1',
    maturity_pct: 30,
    problem: 'DurableExecutor JSON file ; pas workflow_runs en DB.',
    target: 'Temporal ou DB steps ; automation_targets branchés.',
    owner_packages: ['orchestrator', 'db'],
    agent_roles: ['MasterAI', 'QA'],
    blocking_for: ['studio.production_actions'],
    implementation_notes: ['durable-workflows.ts', 'durable-executor.ts', 'migration workflow_runs'],
  },
  {
    id: 'agents.project_knowledge',
    stratum: 'knowledge_graph',
    title: 'RAG projet (GDD, art bible, échecs QA)',
    status: 'partial',
    priority: 'P2',
    maturity_pct: 38,
    problem: 'Index workspace JSON + API search ; pas encore embedding vectoriel.',
    target: 'Index workspace → Cortex plan + asset briefs contextualisés.',
    owner_packages: ['cortex', 'orchestrator'],
    agent_roles: ['MasterAI', 'Art Direction', 'Character'],
    blocking_for: ['asset.concept_to_hd'],
    implementation_notes: ['workspace-indexer.ts', '08_ops/knowledge/index.json', 'API /knowledge/search'],
  },
  {
    id: 'qa.blocking_gates',
    stratum: 'qa_validation',
    title: 'Gates QA bloquants export/build',
    status: 'partial',
    priority: 'P1',
    maturity_pct: 62,
    problem: 'QA fidelity IoU bloque stage 07 et export html5/pwa (422).',
    target: 'passed=false → no PWA ; pixel-diff par famille asset.',
    owner_packages: ['agents', 'pipeline', 'shared/provenance'],
    agent_roles: ['QA'],
    blocking_for: ['runtime.multi_platform_export'],
    implementation_notes: ['fidelity-qa.ts', 'export-gate.ts', 'qa-agent.ts'],
  },
  {
    id: 'observability.real_kpis',
    stratum: 'observability_mlops',
    title: 'KPIs réels (prompt→preview, qa_score, IoU)',
    status: 'partial',
    priority: 'P2',
    maturity_pct: 38,
    problem: 'Telemetry events.jsonl workspace + migration DB 004 ; ObservabilityTab labels sans dashboards.',
    target: 'Persistance DB + dashboards Studio.',
    owner_packages: ['shared/telemetry', 'studio'],
    agent_roles: ['Integration'],
    blocking_for: [],
    implementation_notes: ['telemetry.ts', 'ObservabilityTab.tsx', 'DB table telemetry_events'],
  },
  {
    id: 'runtime.multi_platform_export',
    stratum: 'runtime_shipping',
    title: 'Export PWA/mobile/desktop complet',
    status: 'partial',
    priority: 'P2',
    maturity_pct: 52,
    problem: 'Route export PWA + gate QA compliance ; bundling build incomplet.',
    target: 'Capacitor/Electron pipelines ; store compliance.',
    owner_packages: ['orchestrator', 'shared/export'],
    agent_roles: ['Integration'],
    blocking_for: ['qa.blocking_gates'],
    implementation_notes: ['export/pwa.ts', 'routes export PWA'],
  },
];

export function summarizeGapRegistry() {
  const byStatus = { missing: 0, stub: 0, partial: 0, production_ready: 0 };
  let maturitySum = 0;
  for (const cap of STUDIO_CAPABILITY_GAPS) {
    byStatus[cap.status]++;
    maturitySum += cap.maturity_pct;
  }
  return {
    total_capabilities: STUDIO_CAPABILITY_GAPS.length,
    engines: EVOLUTION_ENGINES.length,
    average_maturity_pct: Math.round(maturitySum / STUDIO_CAPABILITY_GAPS.length),
    by_status: byStatus,
    p0_count: STUDIO_CAPABILITY_GAPS.filter((c) => c.priority === 'P0').length,
  };
}
