export function buildConstructionGraph({ checkedAt, designStrata, agentHandoffs }) {
  return {
    checked_at: checkedAt,
    title: 'Echoes construction graph',
    workspace: 'echoes-of-the-mushroom-realm',
    views: {
      strata_flow: {
        title: 'Layer flow',
        description: 'From vision to release, each layer depends on the previous one and exposes clickable manifests.',
        nodes: [
          { id: 'brief', label: 'Brief', group: 'design', file: '00_brief/documents/00_pitch.md', summary: 'Vision, pillars, target, constraints.' },
          { id: 'wireframe', label: 'Wireframe', group: 'design', file: '02_design/specs/wireframe-blueprint.json', summary: 'Critical path, anchors, pacing map.' },
          { id: 'mechanics', label: 'Mechanics', group: 'design', file: '02_design/specs/game-feel-stack.json', summary: 'Movement, combat, reward, feel.' },
          { id: 'scene_assembly', label: 'Scene Assembly', group: 'scene', file: '04_scenes/level_01/scene-assembly.json', summary: 'Asset placement, zones, camera coupling.' },
          { id: 'narrative', label: 'Narrative', group: 'design', file: '02_design/specs/story-architecture.json', summary: 'Story graph, codex, delivery modes.' },
          { id: 'audio', label: 'Audio', group: 'runtime', file: '02_design/specs/audio-architecture.json', summary: 'Music states, buses, SFX families.' },
          { id: 'fx_hd', label: 'HD FX', group: 'runtime', file: '02_design/specs/vfx-hd-stack.json', summary: 'Particles, glows, impacts, device tiers.' },
          { id: 'ui_menu', label: 'Menus', group: 'runtime', file: '02_design/specs/menu-architecture.json', summary: 'Main menu, codex, settings, accessibility.' },
          { id: 'runtime', label: 'Runtime', group: 'runtime', file: '05_runtime/config/runtime-systems.json', summary: 'Systems, load order, dimension adapters.' },
          { id: 'qa_release', label: 'QA Release', group: 'qa', file: '06_qa/checklists/production-gates.json', summary: 'Ship gates, blockers, validation.' },
        ],
        edges: [
          ['brief', 'wireframe'],
          ['wireframe', 'mechanics'],
          ['mechanics', 'scene_assembly'],
          ['scene_assembly', 'narrative'],
          ['narrative', 'audio'],
          ['audio', 'fx_hd'],
          ['fx_hd', 'ui_menu'],
          ['ui_menu', 'runtime'],
          ['runtime', 'qa_release'],
        ],
      },
      agent_flow: {
        title: 'Agent handoffs',
        description: 'How responsibility flows between agents as the game matures.',
        nodes: [
          { id: 'producer', label: 'Producer', lane: 0, file: '08_ops/manifests/agent-capabilities.json' },
          { id: 'game_design', label: 'Game Design', lane: 1, file: '08_ops/manifests/agent-handoffs.json' },
          { id: 'level_design', label: 'Level Design', lane: 2, file: '04_scenes/level_01/wireframe-map.json' },
          { id: 'art_direction', label: 'Art Direction', lane: 0, file: '02_design/specs/style-guide.json' },
          { id: 'asset_direction', label: 'Asset Direction', lane: 1, file: '03_assets/registry/asset-production-plan.json' },
          { id: 'animation', label: 'Animation', lane: 2, file: '03_assets/registry/animation-specs.json' },
          { id: 'narrative', label: 'Narrative', lane: 0, file: '02_design/specs/story-architecture.json' },
          { id: 'gameplay_programming', label: 'Gameplay', lane: 1, file: '05_runtime/config/runtime-systems.json' },
          { id: 'audio', label: 'Audio', lane: 0, file: '05_runtime/config/audio-banks.json' },
          { id: 'qa', label: 'QA', lane: 1, file: '06_qa/checklists/production-gates.json' },
          { id: 'build_release', label: 'Build Release', lane: 2, file: '08_ops/manifests/construction-stack.json' },
        ],
        edges: agentHandoffs.handoffs.map((handoff) => ({
          from: handoff.from,
          to: handoff.to,
          label: handoff.deliver.join(', '),
        })),
      },
      runtime_sequence: {
        title: 'Runtime sequence',
        description: 'What gets loaded and activated, in order, when the game boots or enters a scene.',
        lanes: ['Boot', 'Scene', 'Story', 'Audio', 'FX', 'UI'],
        steps: [
          { lane: 'Boot', title: 'Load config', file: '05_runtime/config/runtime-systems.json', detail: 'Load primary runtime profile and system list.' },
          { lane: 'Scene', title: 'Load layout', file: '04_scenes/level_01/layout.json', detail: 'Bring scene geometry, zones, goal, hazards.' },
          { lane: 'Scene', title: 'Bind assets', file: '04_scenes/level_01/scene-assembly.json', detail: 'Connect playfield, parallax, hero and environment packs.' },
          { lane: 'Story', title: 'Story graph live', file: '05_runtime/config/story-graph.json', detail: 'Attach zone and interaction triggers.' },
          { lane: 'Audio', title: 'Audio state machine', file: '05_runtime/config/audio-banks.json', detail: 'Select music and ambient buses.' },
          { lane: 'FX', title: 'FX presets', file: '05_runtime/config/fx-presets.json', detail: 'Map event ids to visual responses.' },
          { lane: 'UI', title: 'Menus and codex', file: '05_runtime/config/menu-config.json', detail: 'Mount title flow, codex, settings, overlays.' },
          { lane: 'Boot', title: 'QA gate check', file: '06_qa/checklists/production-gates.json', detail: 'Confirm required outputs and blockers.' },
        ],
      },
      workspace_surfaces: {
        title: 'Workspace surfaces',
        description: 'The project is distributed across stable surfaces instead of one giant editor file.',
        groups: [
          { id: 'design', label: 'Design', files: ['02_design/specs/game-construction-stack.md', '02_design/specs/camera-language.json', '02_design/specs/menu-architecture.json', '02_design/specs/story-architecture.json'] },
          { id: 'scene', label: 'Scene', files: ['04_scenes/level_01/layout.json', '04_scenes/level_01/scene-assembly.json', '04_scenes/level_01/wireframe-map.json'] },
          { id: 'runtime', label: 'Runtime', files: ['05_runtime/config/runtime-systems.json', '05_runtime/config/menu-config.json', '05_runtime/config/story-graph.json', '05_runtime/config/audio-banks.json'] },
          { id: 'systems', label: 'Systems Board', files: ['02_design/specs/interactive-systems-blueprint.md', '04_scenes/level_01/interaction-schema.json', '05_runtime/config/addable-elements-catalog.json', '05_runtime/config/trigger-library.json', '05_runtime/config/asset-call-graph.json', '05_runtime/config/world-composition.json', '08_ops/manifests/systems-board.json'] },
          { id: 'operating', label: 'Game Operating Model', files: ['02_design/specs/game-operating-model.md', '05_runtime/config/progression-economy.json', '05_runtime/config/save-profile.schema.json', '05_runtime/config/accessibility-presets.json', '05_runtime/config/localization-plan.json', '05_runtime/config/quest-graph.json', '05_runtime/config/world-state-machine.json', '05_runtime/config/build-targets.json', '05_runtime/config/telemetry-plan.json', '08_ops/manifests/game-operating-model.json'] },
          { id: 'ops', label: 'Ops', files: ['08_ops/manifests/agent-capabilities.json', '08_ops/manifests/agent-handoffs.json', '08_ops/manifests/construction-stack.json'] },
        ],
      },
    },
  };
}

export function buildConstructionManifest({ checkedAt, designStrata }) {
  return {
    checked_at: checkedAt,
    workspace: 'echoes-of-the-mushroom-realm',
    focus: 'full stack mobile-first game construction',
    strata: designStrata.strata,
    runtime_primary: '2D',
    runtime_next: '2.5D',
    runtime_deferred: '3D',
    manifests: [
      '02_design/specs/design-strata.json',
      '02_design/specs/wireframe-blueprint.json',
      '02_design/specs/camera-language.json',
      '02_design/specs/menu-architecture.json',
      '02_design/specs/story-architecture.json',
      '02_design/specs/game-feel-stack.json',
      '02_design/specs/audio-architecture.json',
      '02_design/specs/vfx-hd-stack.json',
      '02_design/specs/dimension-strategy.json',
      '04_scenes/level_01/scene-assembly.json',
      '05_runtime/config/runtime-systems.json',
      '05_runtime/config/mobile-presets.json',
      '05_runtime/config/menu-config.json',
      '05_runtime/config/story-graph.json',
      '05_runtime/config/audio-banks.json',
      '05_runtime/config/fx-presets.json',
      '02_design/specs/interactive-systems-blueprint.md',
      '04_scenes/level_01/interaction-schema.json',
      '05_runtime/config/addable-elements-catalog.json',
      '05_runtime/config/trigger-library.json',
      '05_runtime/config/asset-call-graph.json',
      '05_runtime/config/world-composition.json',
      '08_ops/manifests/systems-board.json',
      '02_design/specs/game-operating-model.md',
      '05_runtime/config/progression-economy.json',
      '05_runtime/config/save-profile.schema.json',
      '05_runtime/config/accessibility-presets.json',
      '05_runtime/config/localization-plan.json',
      '05_runtime/config/quest-graph.json',
      '05_runtime/config/world-state-machine.json',
      '05_runtime/config/build-targets.json',
      '05_runtime/config/telemetry-plan.json',
      '08_ops/manifests/game-operating-model.json',
      '06_qa/checklists/production-gates.json',
      '08_ops/manifests/agent-handoffs.json',
    ],
  };
}

export function buildSurfaceManifests({ checkedAt }) {
  return {
    constructionMapManifest: {
      checked_at: checkedAt,
      title: 'Echoes construction map',
      graph_url: '/workspaces/echoes-of-the-mushroom-realm/08_ops/manifests/construction-graph.json',
      stack_url: '/workspaces/echoes-of-the-mushroom-realm/08_ops/manifests/construction-stack.json',
      handoffs_url: '/workspaces/echoes-of-the-mushroom-realm/08_ops/manifests/agent-handoffs.json',
      design_url: '/workspaces/echoes-of-the-mushroom-realm/02_design/specs/design-strata.json',
      systems_url: '/workspaces/echoes-of-the-mushroom-realm/07_exports/web/systems-board.html',
      operating_url: '/workspaces/echoes-of-the-mushroom-realm/07_exports/web/operating-model.html',
    },
    systemsBoardManifest: {
      checked_at: checkedAt,
      title: 'Echoes systems board',
      board_url: '/workspaces/echoes-of-the-mushroom-realm/08_ops/manifests/systems-board.json',
      trigger_url: '/workspaces/echoes-of-the-mushroom-realm/05_runtime/config/trigger-library.json',
      asset_graph_url: '/workspaces/echoes-of-the-mushroom-realm/05_runtime/config/asset-call-graph.json',
      world_url: '/workspaces/echoes-of-the-mushroom-realm/05_runtime/config/world-composition.json',
    },
    operatingModelManifest: {
      checked_at: checkedAt,
      title: 'Echoes operating model',
      model_url: '/workspaces/echoes-of-the-mushroom-realm/08_ops/manifests/game-operating-model.json',
      progression_url: '/workspaces/echoes-of-the-mushroom-realm/05_runtime/config/progression-economy.json',
      quest_url: '/workspaces/echoes-of-the-mushroom-realm/05_runtime/config/quest-graph.json',
      world_url: '/workspaces/echoes-of-the-mushroom-realm/05_runtime/config/world-state-machine.json',
      build_url: '/workspaces/echoes-of-the-mushroom-realm/05_runtime/config/build-targets.json',
    },
  };
}
